# Generated by Django 6.0.2 on 2026-06-03 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castor_ifc_insights', '0003_rename_to_castor'),
        ('environments', '0007_add_audit_name_cache_to_project'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='level',
            new_name='castor_ifc__project_0640eb_idx',
            old_name='castor_ifc_i_project_c13295_idx',
        ),
        migrations.RenameIndex(
            model_name='qtocache',
            new_name='castor_ifc__project_13138e_idx',
            old_name='castor_ifc_i_project_0ef46d_idx',
        ),
        migrations.AlterField(
            model_name='level',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islam_levels', to='environments.project'),
        ),
        migrations.AlterModelTable(
            name='level',
            table=None,
        ),
        migrations.AlterModelTable(
            name='qtocache',
            table=None,
        ),
    ]
