# facilities/tests/factories.py
"""Factory Boy factories for facilities models."""

from __future__ import annotations

import factory

from environments.tests.factories import ProjectFactory
from ifc_processor.tests.factories import IFCEntityFactory, IFCFileFactory


class ClassificationFactory(factory.django.DjangoModelFactory):
    """Factory for ``facilities.Classification`` — a taxonomy system."""

    class Meta:
        model = "facilities.Classification"

    project = factory.SubFactory(ProjectFactory)
    name = factory.Sequence(lambda n: f"Uniclass-{n}")
    edition = "2015"


class ClassificationReferenceFactory(factory.django.DjangoModelFactory):
    """Factory for ``facilities.ClassificationReference`` — one code inside a system."""

    class Meta:
        model = "facilities.ClassificationReference"

    classification = factory.SubFactory(ClassificationFactory)
    code = factory.Sequence(lambda n: f"Ss_25_10_{n:02d}")
    name = factory.Sequence(lambda n: f"Reference {n}")


class FacilityAssetFactory(factory.django.DjangoModelFactory):
    """Factory for ``facilities.FacilityAsset``.

    Both ``project`` and ``ifc_entity`` need to share an IFCFile for the asset
    to be consistent with the deployed data model. The factory wires them
    through a common IFCFile instance by default.
    """

    class Meta:
        model = "facilities.FacilityAsset"

    project = factory.SubFactory(ProjectFactory)
    ifc_entity = factory.LazyAttribute(
        lambda o: IFCEntityFactory(ifc_file=IFCFileFactory(project=o.project))
    )
    asset_tag = factory.Sequence(lambda n: f"AST-{n:04d}")
    manufacturer = "Acme"
    model_number = factory.Sequence(lambda n: f"MODEL-{n:04d}")


class OrphanAssetFactory(factory.django.DjangoModelFactory):
    """Factory for an orphan ``facilities.FacilityAsset`` — no IFC link.

    Name + ifc_type are required by the model's check constraint; asset_tag is
    left unique per project so two orphans don't collide.
    """

    class Meta:
        model = "facilities.FacilityAsset"

    project = factory.SubFactory(ProjectFactory)
    ifc_entity = None
    name = factory.Sequence(lambda n: f"Orphan-{n:04d}")
    ifc_type = "IfcFurniture"
    asset_tag = factory.Sequence(lambda n: f"ORPH-{n:04d}")


class AssetInventoryFactory(factory.django.DjangoModelFactory):
    """Factory for ``facilities.AssetInventory``."""

    class Meta:
        model = "facilities.AssetInventory"

    asset = factory.SubFactory(FacilityAssetFactory)


# ── Work Orders (M3) ──────────────────────────────────────────────────────


class ActionRequestFactory(factory.django.DjangoModelFactory):
    """Factory for ``facilities.ActionRequest``."""

    class Meta:
        model = "facilities.ActionRequest"

    project = factory.SubFactory(ProjectFactory)
    title = factory.Sequence(lambda n: f"Action request #{n}")
    description = "Auto-generated request."
    severity = "medium"
    status = "open"


class WorkOrderFactory(factory.django.DjangoModelFactory):
    """Factory for ``facilities.WorkOrder``.

    Creates a DRAFT work order by default. ``wo_number`` is auto-generated by
    the model's ``save()`` so the factory does not set it. ``affected_asset``
    is left null so the factory works for both linked and orphan-style WOs.
    """

    class Meta:
        model = "facilities.WorkOrder"

    project = factory.SubFactory(ProjectFactory)
    title = factory.Sequence(lambda n: f"Work order #{n}")
    description = "Auto-generated work order."
    priority = 3
    category = "corrective"


class WorkOrderStatusEventFactory(factory.django.DjangoModelFactory):
    """Factory for ``facilities.WorkOrderStatusEvent`` — append-only."""

    class Meta:
        model = "facilities.WorkOrderStatusEvent"

    work_order = factory.SubFactory(WorkOrderFactory)
    from_status = None
    to_status = 0  # WorkOrderStatus.DRAFT
    actor_role = ""


class WorkOrderAttachmentFactory(factory.django.DjangoModelFactory):
    """Factory for ``facilities.WorkOrderAttachment``."""

    class Meta:
        model = "facilities.WorkOrderAttachment"

    work_order = factory.SubFactory(WorkOrderFactory)
    file = factory.django.FileField(filename="placeholder.txt")
    caption = "Auto-generated attachment"
    kind = "photo"


class PermitFactory(factory.django.DjangoModelFactory):
    """Factory for ``facilities.Permit``."""

    class Meta:
        model = "facilities.Permit"

    project = factory.SubFactory(ProjectFactory)
    permit_number = factory.Sequence(lambda n: f"PRM-{n:04d}")
    kind = "other"
    title = factory.Sequence(lambda n: f"Permit #{n}")
    status = "active"
