# Generated by Django 6.0.2 on 2026-05-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("castor_scheduling", "0005_task_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="activity_type",
            field=models.CharField(
                blank=True,
                help_text="Raw activity type from the schedule file (e.g. WBS Summary, Milestone, Task Dependent).",
                max_length=100,
                verbose_name="Activity Type",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="is_non_physical",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Excluded from IFC linking — pure schedule activity with no physical element.",
                verbose_name="Non-Physical",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="non_physical_locked",
            field=models.BooleanField(
                default=False,
                help_text="True when is_non_physical was set manually by the user; prevents Layer 0 from overriding it.",
                verbose_name="Non-Physical Locked",
            ),
        ),
    ]
