# Generated by Django 6.0.2 on 2026-05-18 09:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0005_projectrole_assigned_space"),
        ("castor_scheduling", "0010_cpm_fields_and_dependencies"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleSource",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=500, verbose_name="Filename")),
                (
                    "source_format",
                    models.CharField(
                        choices=[
                            ("excel", "Excel (.xlsx)"),
                            ("csv", "CSV (.csv)"),
                            ("xer", "Primavera P6 (.xer)"),
                            ("msp", "MS Project (.xml)"),
                            ("manual", "Manual entry"),
                        ],
                        default="excel",
                        max_length=20,
                        verbose_name="Format",
                    ),
                ),
                ("task_count", models.IntegerField(default=0, verbose_name="Tasks in file")),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_sources",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Source",
                "verbose_name_plural": "Schedule Sources",
                "ordering": ["-imported_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "imported_at"], name="islam_sched_project_41bbae_idx"
                    )
                ],
            },
        ),
    ]
