# Generated by Django 6.0.2 on 2026-05-18 13:56

import uuid

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("castor_scheduling", "0012_schedulesource_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskEmbedding",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vector",
                    pgvector.django.vector.VectorField(
                        dimensions=1024, verbose_name="Embedding Vector"
                    ),
                ),
                (
                    "embedded_text",
                    models.TextField(
                        help_text="The text that was embedded — used to detect staleness.",
                        verbose_name="Embedded Text",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="castor_scheduling.task",
                        verbose_name="Task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Embedding",
                "verbose_name_plural": "Task Embeddings",
            },
        ),
    ]
