# Generated by Django 6.0.2 on 2026-05-22 09:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0005_projectrole_assigned_space"),
        ("castor_scheduling", "0014_columnmappinglookup"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectComprehension",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wbs_levels", models.IntegerField(default=0, verbose_name="WBS Levels")),
                (
                    "wbs_structure",
                    models.JSONField(
                        default=dict,
                        help_text='Hierarchy by level, e.g. {"L1": ["Structure", "MEP"]}',
                        verbose_name="WBS Structure",
                    ),
                ),
                (
                    "code_pattern",
                    models.CharField(
                        blank=True,
                        help_text='Detected pattern, e.g. "[ALPHA][N]-[N].[N]"',
                        max_length=500,
                        verbose_name="Code Pattern",
                    ),
                ),
                (
                    "code_segments",
                    models.JSONField(
                        default=dict,
                        help_text="Most-common values per positional segment",
                        verbose_name="Code Segments",
                    ),
                ),
                (
                    "total_activities",
                    models.IntegerField(default=0, verbose_name="Total Activities"),
                ),
                (
                    "physical_activities",
                    models.IntegerField(default=0, verbose_name="Physical Activities"),
                ),
                (
                    "non_physical_activities",
                    models.IntegerField(default=0, verbose_name="Non-Physical Activities"),
                ),
                (
                    "critical_activities",
                    models.IntegerField(default=0, verbose_name="Critical Activities"),
                ),
                (
                    "project_start",
                    models.DateField(blank=True, null=True, verbose_name="Project Start"),
                ),
                (
                    "project_finish",
                    models.DateField(blank=True, null=True, verbose_name="Project Finish"),
                ),
                (
                    "avg_duration_days",
                    models.FloatField(default=0.0, verbose_name="Avg Duration (days)"),
                ),
                (
                    "type_distribution",
                    models.JSONField(
                        default=dict,
                        help_text="Stage or activity-type counts",
                        verbose_name="Type Distribution",
                    ),
                ),
                (
                    "naming_conventions",
                    models.JSONField(
                        default=dict,
                        help_text='Code prefix meanings, e.g. {"GENDA": "Admin approval"}',
                        verbose_name="Naming Conventions",
                    ),
                ),
                ("phases", models.JSONField(default=list, verbose_name="Phases")),
                ("milestones", models.JSONField(default=list, verbose_name="Milestones")),
                ("ai_summary", models.TextField(blank=True, verbose_name="AI Summary")),
                (
                    "confidence_score",
                    models.FloatField(default=0.0, verbose_name="Confidence Score"),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_comprehension",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Comprehension",
                "verbose_name_plural": "Project Comprehensions",
            },
        ),
    ]
