# Generated by Django 6.0.2 on 2026-06-03 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castor_scheduling', '0021_rename_to_castor'),
        ('environments', '0007_add_audit_name_cache_to_project'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='columnmappinglookup',
            new_name='castor_sche_project_e728f6_idx',
            old_name='castor_sched_project_b9efd3_idx',
        ),
        migrations.RenameIndex(
            model_name='linkfeedback',
            new_name='castor_sche_task_id_6f2ad6_idx',
            old_name='castor_sched_task_id_bec3ed_idx',
        ),
        migrations.RenameIndex(
            model_name='p6calendar',
            new_name='castor_sche_project_441fff_idx',
            old_name='castor_sched_project_f68a20_idx',
        ),
        migrations.RenameIndex(
            model_name='p6calendar',
            new_name='castor_sche_project_265ec4_idx',
            old_name='castor_sched_project_991a7e_idx',
        ),
        migrations.RenameIndex(
            model_name='p6resourceassignment',
            new_name='castor_sche_project_58bb13_idx',
            old_name='castor_sched_project_5d1af0_idx',
        ),
        migrations.RenameIndex(
            model_name='p6resourceassignment',
            new_name='castor_sche_task_id_eece3e_idx',
            old_name='castor_sched_task_id_9f4742_idx',
        ),
        migrations.RenameIndex(
            model_name='p6resourceassignment',
            new_name='castor_sche_p6_acti_063e79_idx',
            old_name='castor_sched_p6_acti_0b0401_idx',
        ),
        migrations.RenameIndex(
            model_name='p6wbsnode',
            new_name='castor_sche_project_91350d_idx',
            old_name='castor_sched_project_490cae_idx',
        ),
        migrations.RenameIndex(
            model_name='p6wbsnode',
            new_name='castor_sche_project_621d5f_idx',
            old_name='castor_sched_project_7723fb_idx',
        ),
        migrations.RenameIndex(
            model_name='schedulesource',
            new_name='castor_sche_project_3c0b82_idx',
            old_name='castor_sched_project_41bbae_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='castor_sche_project_2a24ff_idx',
            old_name='castor_sched_project_345b2f_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='castor_sche_project_696f81_idx',
            old_name='castor_sched_project_ac1c29_idx',
        ),
        migrations.RenameIndex(
            model_name='taskentitybinding',
            new_name='castor_sche_task_id_cecbeb_idx',
            old_name='castor_sched_task_id_f70ae1_idx',
        ),
        migrations.RenameIndex(
            model_name='taskentitybinding',
            new_name='castor_sche_entity__acb8e3_idx',
            old_name='castor_sched_entity__bdcf30_idx',
        ),
        migrations.AlterField(
            model_name='progressmode',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='islam_progress_mode', to='environments.project', verbose_name='Project'),
        ),
        migrations.AlterModelTable(
            name='columnmappinglookup',
            table=None,
        ),
        migrations.AlterModelTable(
            name='linkfeedback',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mappingprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='p6calendar',
            table=None,
        ),
        migrations.AlterModelTable(
            name='p6resourceassignment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='p6wbsnode',
            table=None,
        ),
        migrations.AlterModelTable(
            name='progressmode',
            table=None,
        ),
        migrations.AlterModelTable(
            name='projectcomprehension',
            table=None,
        ),
        migrations.AlterModelTable(
            name='schedulesource',
            table=None,
        ),
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
        migrations.AlterModelTable(
            name='taskdependency',
            table=None,
        ),
        migrations.AlterModelTable(
            name='taskembedding',
            table=None,
        ),
        migrations.AlterModelTable(
            name='taskentitybinding',
            table=None,
        ),
    ]
