# Generated by Django 6.0.2 on 2026-06-13 11:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_binding_lifecycle_states(apps, schema_editor) -> None:
    """Map existing needs_review flags to E2-E lifecycle fields without M2M or event backfill."""
    binding = apps.get_model("castor_scheduling", "TaskEntityBinding")
    binding.objects.filter(needs_review=False).update(
        governance_status="trusted",
        is_active=True,
    )
    binding.objects.filter(needs_review=True).update(
        governance_status="active_review",
        is_active=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("castor_scheduling", "0023_fix_related_names"),
        ("environments", "0008_alter_project_owner"),
        ("ifc_processor", "0011_ifcentity_ifc_description_ifcentity_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BindingGovernanceEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_global_id",
                    models.CharField(db_index=True, max_length=64, verbose_name="Entity GlobalId"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("reaffirmed", "Reaffirmed"),
                            ("reversed", "Reversed"),
                            ("superseded", "Superseded"),
                            ("superseding_acceptance", "Superseding acceptance"),
                            ("m2m_added", "M2M added"),
                            ("m2m_removed", "M2M removed"),
                            ("parity_repaired", "Parity repaired"),
                            ("conflict_acknowledged", "Conflict acknowledged"),
                            ("migration_initialized", "Migration initialized"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("previous_state", models.CharField(max_length=32)),
                ("resulting_state", models.CharField(max_length=32)),
                ("reason_code", models.CharField(max_length=64)),
                ("reason_text", models.TextField(blank=True)),
                ("policy_id", models.CharField(default="trusted-binding-v1", max_length=64)),
                ("decision_reference_id", models.CharField(db_index=True, max_length=64)),
                ("batch_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                ("request_source", models.CharField(blank=True, default="", max_length=64)),
                ("trusted_before", models.BooleanField(null=True)),
                ("trusted_after", models.BooleanField(null=True)),
                ("m2m_before", models.BooleanField(null=True)),
                ("m2m_after", models.BooleanField(null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Binding Governance Event",
                "verbose_name_plural": "Binding Governance Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="taskentitybinding",
            name="governance_status",
            field=models.CharField(
                choices=[
                    ("active_review", "Active review"),
                    ("trusted", "Trusted"),
                    ("rejected", "Rejected"),
                    ("reversed", "Reversed"),
                    ("superseded", "Superseded"),
                ],
                db_index=True,
                default="active_review",
                max_length=20,
                verbose_name="Governance Status",
            ),
        ),
        migrations.AddField(
            model_name="taskentitybinding",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="False when rejected, reversed, or superseded.",
                verbose_name="Active",
            ),
        ),
        migrations.AddField(
            model_name="taskentitybinding",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Rejected At"),
        ),
        migrations.AddField(
            model_name="taskentitybinding",
            name="reversed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Reversed At"),
        ),
        migrations.AddField(
            model_name="taskentitybinding",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supersedes",
                to="castor_scheduling.taskentitybinding",
                verbose_name="Superseded By",
            ),
        ),
        migrations.AddIndex(
            model_name="taskentitybinding",
            index=models.Index(
                fields=["governance_status", "is_active"], name="castor_sche_governa_1881a9_idx"
            ),
        ),
        migrations.AddField(
            model_name="bindinggovernanceevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="binding_governance_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actor",
            ),
        ),
        migrations.AddField(
            model_name="bindinggovernanceevent",
            name="binding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="governance_events",
                to="castor_scheduling.taskentitybinding",
                verbose_name="Binding",
            ),
        ),
        migrations.AddField(
            model_name="bindinggovernanceevent",
            name="ifc_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="binding_governance_events",
                to="ifc_processor.ifcfile",
                verbose_name="IFC File",
            ),
        ),
        migrations.AddField(
            model_name="bindinggovernanceevent",
            name="parent_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_events",
                to="castor_scheduling.bindinggovernanceevent",
                verbose_name="Parent Event",
            ),
        ),
        migrations.AddField(
            model_name="bindinggovernanceevent",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="binding_governance_events",
                to="environments.project",
                verbose_name="Project",
            ),
        ),
        migrations.AddField(
            model_name="bindinggovernanceevent",
            name="related_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_events",
                to="castor_scheduling.bindinggovernanceevent",
                verbose_name="Related Event",
            ),
        ),
        migrations.AddField(
            model_name="bindinggovernanceevent",
            name="replacement_binding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replacement_events",
                to="castor_scheduling.taskentitybinding",
                verbose_name="Replacement Binding",
            ),
        ),
        migrations.AddField(
            model_name="bindinggovernanceevent",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="binding_governance_events",
                to="castor_scheduling.task",
                verbose_name="Task",
            ),
        ),
        migrations.AddIndex(
            model_name="bindinggovernanceevent",
            index=models.Index(
                fields=["project", "created_at"], name="castor_sche_project_55742a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bindinggovernanceevent",
            index=models.Index(
                fields=["project", "event_type", "created_at"],
                name="castor_sche_project_1ec0bf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bindinggovernanceevent",
            index=models.Index(
                fields=["binding", "created_at"], name="castor_sche_binding_6cedee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bindinggovernanceevent",
            index=models.Index(
                fields=["task", "created_at"], name="castor_sche_task_id_7686fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bindinggovernanceevent",
            index=models.Index(
                fields=["entity_global_id", "created_at"], name="castor_sche_entity__edcddf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bindinggovernanceevent",
            index=models.Index(
                fields=["decision_reference_id"], name="castor_sche_decisio_6cb9cf_idx"
            ),
        ),
        migrations.RunPython(
            code=_backfill_binding_lifecycle_states,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
