# Generated by Django 6.0.2 on 2026-06-14 08:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("castor_scheduling", "0024_binding_governance_events"),
        ("environments", "0008_alter_project_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleActivity",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canonical_activity_key",
                    models.CharField(
                        db_index=True,
                        help_text="Project-scoped stable key — never derived from name or dates alone.",
                        max_length=255,
                        verbose_name="Canonical Activity Key",
                    ),
                ),
                (
                    "external_activity_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="External Activity ID"
                    ),
                ),
                (
                    "activity_code",
                    models.CharField(blank=True, max_length=255, verbose_name="Activity Code"),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=500, verbose_name="Display Name"),
                ),
                (
                    "source_identity_hint",
                    models.CharField(
                        blank=True,
                        help_text="Importer hint: p6xml, xer, msp, column, manual, etc.",
                        max_length=32,
                        verbose_name="Source Identity Hint",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("imported", "Imported"),
                            ("manual", "Manual"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        default="imported",
                        max_length=16,
                        verbose_name="Origin",
                    ),
                ),
                (
                    "identity_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("unresolved", "Unresolved"),
                            ("superseded", "Superseded"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                        verbose_name="Identity Status",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadata")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_activities",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Activity",
                "verbose_name_plural": "Schedule Activities",
                "ordering": ["canonical_activity_key"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="schedule_activity",
            field=models.ForeignKey(
                blank=True,
                help_text="Logical activity identity across source versions (nullable until linked).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="castor_scheduling.scheduleactivity",
                verbose_name="Schedule Activity",
            ),
        ),
        migrations.CreateModel(
            name="ScheduleSourceVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(default=1, verbose_name="Version Number"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("excel", "Excel (.xlsx)"),
                            ("csv", "CSV (.csv)"),
                            ("xer", "Primavera P6 (.xer)"),
                            ("msp", "MS Project (.xml)"),
                            ("p6xml", "Primavera P6 XML (.xml)"),
                            ("manual", "Manual entry"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Source Type",
                    ),
                ),
                (
                    "source_filename",
                    models.CharField(max_length=500, verbose_name="Source Filename"),
                ),
                (
                    "content_hash",
                    models.CharField(blank=True, max_length=64, verbose_name="Content Hash"),
                ),
                (
                    "external_project_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="External Project ID"
                    ),
                ),
                (
                    "external_schedule_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="External Schedule ID"
                    ),
                ),
                (
                    "external_revision",
                    models.CharField(blank=True, max_length=255, verbose_name="External Revision"),
                ),
                ("data_date", models.DateField(blank=True, null=True, verbose_name="Data Date")),
                ("imported_at", models.DateTimeField(verbose_name="Imported At")),
                (
                    "importer_version",
                    models.CharField(blank=True, max_length=64, verbose_name="Importer Version"),
                ),
                (
                    "parser_version",
                    models.CharField(blank=True, max_length=64, verbose_name="Parser Version"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("current", "Current"),
                            ("superseded", "Superseded"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="candidate",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "source_metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Source Metadata"),
                ),
                (
                    "validation_summary",
                    models.JSONField(blank=True, default=dict, verbose_name="Validation Summary"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_source_versions_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_source_versions",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "schedule_source",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to legacy import audit row during transition.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_versions",
                        to="castor_scheduling.schedulesource",
                        verbose_name="Legacy Schedule Source",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by_versions",
                        to="castor_scheduling.schedulesourceversion",
                        verbose_name="Supersedes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Source Version",
                "verbose_name_plural": "Schedule Source Versions",
                "ordering": ["-imported_at", "-version_number"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleImportRun",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("excel", "Excel (.xlsx)"),
                            ("csv", "CSV (.csv)"),
                            ("xer", "Primavera P6 (.xer)"),
                            ("msp", "MS Project (.xml)"),
                            ("p6xml", "Primavera P6 XML (.xml)"),
                            ("manual", "Manual entry"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Source Type",
                    ),
                ),
                (
                    "source_filename",
                    models.CharField(max_length=500, verbose_name="Source Filename"),
                ),
                (
                    "content_hash",
                    models.CharField(blank=True, max_length=64, verbose_name="Content Hash"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("append", "Append"),
                            ("update", "Update"),
                            ("replace", "Replace"),
                            ("preview", "Preview"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                        verbose_name="Import Mode",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="Started At")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Completed At"),
                ),
                (
                    "importer_version",
                    models.CharField(blank=True, max_length=64, verbose_name="Importer Version"),
                ),
                (
                    "parser_version",
                    models.CharField(blank=True, max_length=64, verbose_name="Parser Version"),
                ),
                ("task_count", models.IntegerField(default=0, verbose_name="Task Count")),
                (
                    "dependency_count",
                    models.IntegerField(default=0, verbose_name="Dependency Count"),
                ),
                ("skipped_count", models.IntegerField(default=0, verbose_name="Skipped Count")),
                ("warning_count", models.IntegerField(default=0, verbose_name="Warning Count")),
                ("error_count", models.IntegerField(default=0, verbose_name="Error Count")),
                (
                    "validation_summary",
                    models.JSONField(blank=True, default=dict, verbose_name="Validation Summary"),
                ),
                ("error_summary", models.TextField(blank=True, verbose_name="Error Summary")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_import_runs",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_import_runs_requested",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
                (
                    "schedule_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_runs",
                        to="castor_scheduling.schedulesource",
                        verbose_name="Legacy Schedule Source",
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_runs",
                        to="castor_scheduling.schedulesourceversion",
                        verbose_name="Accepted Source Version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Import Run",
                "verbose_name_plural": "Schedule Import Runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="source_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Accepted schedule source version that last touched this task (nullable).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="castor_scheduling.schedulesourceversion",
                verbose_name="Source Version",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleactivity",
            index=models.Index(
                fields=["project", "identity_status"], name="castor_sche_project_277acf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleactivity",
            index=models.Index(
                fields=["project", "external_activity_id"], name="castor_sche_project_397bc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleactivity",
            index=models.Index(
                fields=["project", "activity_code"], name="castor_sche_project_a9b083_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleactivity",
            constraint=models.UniqueConstraint(
                fields=("project", "canonical_activity_key"),
                name="castor_scheduling_unique_activity_key_per_project",
            ),
        ),
        migrations.AddIndex(
            model_name="schedulesourceversion",
            index=models.Index(fields=["project", "status"], name="castor_sche_project_c03e2c_idx"),
        ),
        migrations.AddIndex(
            model_name="schedulesourceversion",
            index=models.Index(
                fields=["project", "imported_at"], name="castor_sche_project_c351c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schedulesourceversion",
            index=models.Index(
                fields=["project", "version_number"], name="castor_sche_project_f1edbc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulesourceversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "current")),
                fields=("project",),
                name="castor_scheduling_unique_current_ssv_per_project",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleimportrun",
            index=models.Index(fields=["project", "status"], name="castor_sche_project_4f27bf_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduleimportrun",
            index=models.Index(
                fields=["project", "started_at"], name="castor_sche_project_2658cf_idx"
            ),
        ),
    ]
