# Generated by Django 6.0.2 on 2026-06-14 12:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("castor_scheduling", "0025_source_version_foundation"),
        ("environments", "0008_alter_project_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaselineVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "code",
                    models.CharField(blank=True, max_length=64, verbose_name="Code / Reference"),
                ),
                (
                    "baseline_type",
                    models.CharField(
                        choices=[
                            ("imported_reference", "Imported reference"),
                            ("working", "Working"),
                            ("approved", "Approved"),
                            ("comparison_only", "Comparison only"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Baseline Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("superseded", "Superseded"),
                            ("archived", "Archived"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("data_date", models.DateField(blank=True, null=True, verbose_name="Data Date")),
                (
                    "effective_date",
                    models.DateField(blank=True, null=True, verbose_name="Effective Date"),
                ),
                (
                    "revision_number",
                    models.PositiveIntegerField(default=1, verbose_name="Revision"),
                ),
                ("currency", models.CharField(blank=True, max_length=8, verbose_name="Currency")),
                (
                    "methodology_version",
                    models.CharField(blank=True, max_length=64, verbose_name="Methodology Version"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "is_selected_for_analysis",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Selected for Analysis"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Published At"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Approved At"),
                ),
                (
                    "superseded_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Superseded At"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadata")),
                (
                    "validation_summary",
                    models.JSONField(blank=True, default=dict, verbose_name="Validation Summary"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_versions_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_versions_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "parent_baseline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_revisions",
                        to="castor_scheduling.baselineversion",
                        verbose_name="Parent Baseline",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baseline_versions",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_versions_published",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Published By",
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baseline_versions",
                        to="castor_scheduling.schedulesourceversion",
                        verbose_name="Source Version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baseline Version",
                "verbose_name_plural": "Baseline Versions",
                "ordering": ["-created_at", "-revision_number"],
            },
        ),
        migrations.CreateModel(
            name="BaselineTaskState",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_task_id",
                    models.CharField(
                        blank=True, max_length=36, verbose_name="Source Task ID Reference"
                    ),
                ),
                (
                    "activity_code",
                    models.CharField(blank=True, max_length=255, verbose_name="Activity Code"),
                ),
                ("name_snapshot", models.CharField(max_length=500, verbose_name="Name Snapshot")),
                (
                    "planned_start",
                    models.DateField(blank=True, null=True, verbose_name="Planned Start"),
                ),
                (
                    "planned_finish",
                    models.DateField(blank=True, null=True, verbose_name="Planned Finish"),
                ),
                (
                    "duration_days",
                    models.IntegerField(blank=True, null=True, verbose_name="Duration (days)"),
                ),
                (
                    "calendar_reference",
                    models.CharField(blank=True, max_length=128, verbose_name="Calendar Reference"),
                ),
                (
                    "baseline_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Baseline Cost / BAC",
                    ),
                ),
                (
                    "planned_resource_units",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Planned Resource Units",
                    ),
                ),
                (
                    "progress_basis",
                    models.CharField(blank=True, max_length=64, verbose_name="Progress Basis"),
                ),
                (
                    "activity_type",
                    models.CharField(blank=True, max_length=100, verbose_name="Activity Type"),
                ),
                (
                    "source_metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Source Metadata"),
                ),
                (
                    "field_provenance",
                    models.JSONField(blank=True, default=dict, verbose_name="Field Provenance"),
                ),
                (
                    "schedule_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baseline_task_states",
                        to="castor_scheduling.scheduleactivity",
                        verbose_name="Schedule Activity",
                    ),
                ),
                (
                    "baseline_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_states",
                        to="castor_scheduling.baselineversion",
                        verbose_name="Baseline Version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baseline Task State",
                "verbose_name_plural": "Baseline Task States",
            },
        ),
        migrations.CreateModel(
            name="BaselineAuditEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("baseline_created", "Baseline created"),
                            ("baseline_population_completed", "Population completed"),
                            ("baseline_published", "Baseline published"),
                            ("baseline_approved", "Baseline approved"),
                            ("baseline_selected", "Baseline selected"),
                            ("baseline_superseded", "Baseline superseded"),
                            ("baseline_archived", "Baseline archived"),
                            ("baseline_rejected", "Baseline rejected"),
                        ],
                        db_index=True,
                        max_length=48,
                    ),
                ),
                ("previous_status", models.CharField(blank=True, max_length=16)),
                ("new_status", models.CharField(blank=True, max_length=16)),
                ("reason", models.TextField(blank=True, verbose_name="Reason / Reference")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadata")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_audit_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baseline_audit_events",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_audit_events",
                        to="castor_scheduling.schedulesourceversion",
                        verbose_name="Source Version",
                    ),
                ),
                (
                    "baseline_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="castor_scheduling.baselineversion",
                        verbose_name="Baseline Version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baseline Audit Event",
                "verbose_name_plural": "Baseline Audit Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="baselineversion",
            index=models.Index(fields=["project", "status"], name="castor_sche_project_c2c0f2_idx"),
        ),
        migrations.AddIndex(
            model_name="baselineversion",
            index=models.Index(
                fields=["project", "baseline_type"], name="castor_sche_project_91469c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="baselineversion",
            index=models.Index(
                fields=["project", "is_selected_for_analysis"],
                name="castor_sche_project_67d9ec_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="baselineversion",
            constraint=models.UniqueConstraint(
                fields=("project", "revision_number"),
                name="castor_scheduling_unique_baseline_revision_per_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="baselineversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_selected_for_analysis", True)),
                fields=("project",),
                name="castor_scheduling_unique_selected_baseline_per_project",
            ),
        ),
        migrations.AddIndex(
            model_name="baselinetaskstate",
            index=models.Index(
                fields=["baseline_version", "schedule_activity"],
                name="castor_sche_baselin_8000d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="baselinetaskstate",
            index=models.Index(
                fields=["baseline_version", "activity_code"], name="castor_sche_baselin_061c6c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="baselinetaskstate",
            constraint=models.UniqueConstraint(
                fields=("baseline_version", "schedule_activity"),
                name="castor_scheduling_unique_baseline_task_per_activity",
            ),
        ),
        migrations.AddIndex(
            model_name="baselineauditevent",
            index=models.Index(
                fields=["project", "event_type"], name="castor_sche_project_44d0fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="baselineauditevent",
            index=models.Index(
                fields=["baseline_version", "created_at"], name="castor_sche_baselin_75b15b_idx"
            ),
        ),
    ]
