# Generated by Django 6.0.2 on 2026-06-14 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castor_scheduling', '0026_baseline_domain'),
        ('environments', '0008_alter_project_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticalSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('snapshot_type', models.CharField(choices=[('import_snapshot', 'Import snapshot'), ('manual_checkpoint', 'Manual checkpoint'), ('scheduled_checkpoint', 'Scheduled checkpoint'), ('report_freeze', 'Report freeze'), ('pre_import_safety', 'Pre-import safety'), ('release_checkpoint', 'Release checkpoint')], db_index=True, max_length=32, verbose_name='Snapshot Type')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('calculating', 'Calculating'), ('completed', 'Completed'), ('failed', 'Failed'), ('published', 'Published'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=16, verbose_name='Status')),
                ('sequence_number', models.PositiveIntegerField(default=1, verbose_name='Sequence')),
                ('data_date', models.DateField(blank=True, null=True, verbose_name='Data Date')),
                ('as_of_date', models.DateField(verbose_name='As-Of Date')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('calculation_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Calculation Started At')),
                ('calculation_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Calculation Completed At')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('superseded_at', models.DateTimeField(blank=True, null=True, verbose_name='Superseded At')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived At')),
                ('methodology_version', models.CharField(max_length=64, verbose_name='Methodology Version')),
                ('capability_profile_version', models.CharField(max_length=64, verbose_name='Capability Profile Version')),
                ('trust_policy_version', models.CharField(max_length=64, verbose_name='Trust Policy Version')),
                ('calculation_engine_version', models.CharField(blank=True, max_length=64, verbose_name='Calculation Engine Version')),
                ('source_content_hash', models.CharField(blank=True, max_length=128, verbose_name='Source Content Hash')),
                ('input_fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='Input Fingerprint')),
                ('scope_fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='Scope Fingerprint')),
                ('repeatability_status', models.CharField(choices=[('fully_repeatable', 'Fully repeatable'), ('source_repeatable', 'Source repeatable'), ('partially_repeatable', 'Partially repeatable'), ('manifest_only', 'Manifest only')], default='manifest_only', max_length=32, verbose_name='Repeatability Status')),
                ('filter_context', models.JSONField(blank=True, default=dict, verbose_name='Filter Context')),
                ('input_manifest', models.JSONField(blank=True, default=dict, verbose_name='Input Manifest')),
                ('validation_summary', models.JSONField(blank=True, default=dict, verbose_name='Validation Summary')),
                ('coverage_summary', models.JSONField(blank=True, default=dict, verbose_name='Coverage Summary')),
                ('caveats', models.JSONField(blank=True, default=list, verbose_name='Caveats')),
                ('failure_summary', models.TextField(blank=True, verbose_name='Failure Summary')),
                ('artifact_manifest', models.JSONField(blank=True, default=dict, verbose_name='Artifact Manifest')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytical_snapshots_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archived By')),
                ('baseline_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytical_snapshots', to='castor_scheduling.baselineversion', verbose_name='Baseline Version')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytical_snapshots_calculated', to=settings.AUTH_USER_MODEL, verbose_name='Calculated By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytical_snapshots', to='environments.project', verbose_name='Project')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytical_snapshots_published', to=settings.AUTH_USER_MODEL, verbose_name='Published By')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytical_snapshots_requested', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytical_snapshots', to='castor_scheduling.schedulesourceversion', verbose_name='Source Version')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='castor_scheduling.analyticalsnapshot', verbose_name='Supersedes')),
            ],
            options={
                'verbose_name': 'Analytical Snapshot',
                'verbose_name_plural': 'Analytical Snapshots',
                'ordering': ['-requested_at', '-sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticalSnapshotAuditEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('snapshot_requested', 'Snapshot requested'), ('snapshot_calculation_started', 'Calculation started'), ('snapshot_completed', 'Snapshot completed'), ('snapshot_failed', 'Snapshot failed'), ('snapshot_published', 'Snapshot published'), ('snapshot_superseded', 'Snapshot superseded'), ('snapshot_archived', 'Snapshot archived')], db_index=True, max_length=48)),
                ('previous_status', models.CharField(blank=True, max_length=16)),
                ('new_status', models.CharField(blank=True, max_length=16)),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('methodology_version', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytical_snapshot_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('baseline_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_audit_events', to='castor_scheduling.baselineversion', verbose_name='Baseline Version')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytical_snapshot_audit_events', to='environments.project', verbose_name='Project')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='castor_scheduling.analyticalsnapshot', verbose_name='Snapshot')),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_audit_events', to='castor_scheduling.schedulesourceversion', verbose_name='Source Version')),
            ],
            options={
                'verbose_name': 'Analytical Snapshot Audit Event',
                'verbose_name_plural': 'Analytical Snapshot Audit Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='analyticalsnapshot',
            index=models.Index(fields=['project', 'status'], name='castor_sche_project_310bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticalsnapshot',
            index=models.Index(fields=['project', 'snapshot_type'], name='castor_sche_project_6d4e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticalsnapshot',
            index=models.Index(fields=['project', 'data_date'], name='castor_sche_project_db695a_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticalsnapshot',
            index=models.Index(fields=['project', 'input_fingerprint'], name='castor_sche_project_09897a_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticalsnapshot',
            constraint=models.UniqueConstraint(fields=('project', 'sequence_number'), name='castor_scheduling_unique_snapshot_sequence_per_project'),
        ),
        migrations.AddIndex(
            model_name='analyticalsnapshotauditevent',
            index=models.Index(fields=['project', 'event_type'], name='castor_sche_project_f6cc4d_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticalsnapshotauditevent',
            index=models.Index(fields=['snapshot', 'created_at'], name='castor_sche_snapsho_97203b_idx'),
        ),
    ]
