# Generated by Django 6.0.2 on 2026-06-15 06:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castor_scheduling', '0028_snapshot_results_and_series'),
        ('environments', '0008_alter_project_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WBSNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Planner-native object identity when known.', max_length=255, verbose_name='External ID')),
                ('external_parent_id', models.CharField(blank=True, max_length=255, verbose_name='External Parent ID')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='WBS Code')),
                ('name', models.CharField(max_length=500, verbose_name='WBS Name')),
                ('path', models.CharField(blank=True, db_index=True, help_text='Stable ancestor chain using node UUIDs — not display names.', max_length=2048, verbose_name='Materialized Path')),
                ('depth', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Depth')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='Sequence')),
                ('node_type', models.CharField(choices=[('root', 'Root'), ('summary', 'Summary'), ('work_package', 'Work package'), ('leaf', 'Leaf'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20, verbose_name='Node Type')),
                ('identity_status', models.CharField(choices=[('resolved', 'Resolved'), ('unresolved', 'Unresolved'), ('generated', 'Generated'), ('retired', 'Retired')], default='resolved', max_length=16, verbose_name='Identity Status')),
                ('authority', models.CharField(choices=[('source', 'Source'), ('manual', 'Manual'), ('governed', 'Governed'), ('inferred', 'Inferred')], default='manual', max_length=16, verbose_name='Authority')),
                ('source_metadata', models.JSONField(blank=True, default=dict, verbose_name='Source Metadata')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='castor_scheduling.wbsnode', verbose_name='Parent Node')),
            ],
            options={
                'verbose_name': 'WBS Node',
                'verbose_name_plural': 'WBS Nodes',
                'ordering': ['sequence', 'code', 'name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='wbs_node',
            field=models.ForeignKey(blank=True, help_text='Canonical WBS assignment (nullable until DF-C2 population or manual assign).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='castor_scheduling.wbsnode', verbose_name='WBS Node'),
        ),
        migrations.CreateModel(
            name='WBSVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=64, verbose_name='Code / Reference')),
                ('origin', models.CharField(choices=[('p6_xml', 'Primavera P6 XML'), ('p6_xer', 'Primavera P6 XER'), ('msp_xml', 'MS Project XML'), ('column_mapping', 'Column mapping'), ('manual', 'Manual'), ('system', 'System')], db_index=True, default='manual', max_length=20, verbose_name='Origin')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16, verbose_name='Status')),
                ('revision_number', models.PositiveIntegerField(default=1, verbose_name='Revision')),
                ('data_date', models.DateField(blank=True, null=True, verbose_name='Data Date')),
                ('is_selected_for_analysis', models.BooleanField(db_index=True, default=False, verbose_name='Selected for Analysis')),
                ('source_metadata', models.JSONField(blank=True, default=dict, verbose_name='Source Metadata')),
                ('validation_summary', models.JSONField(blank=True, default=dict, verbose_name='Validation Summary')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Activated At')),
                ('superseded_at', models.DateTimeField(blank=True, null=True, verbose_name='Superseded At')),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbs_versions_activated', to=settings.AUTH_USER_MODEL, verbose_name='Activated By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbs_versions_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_revisions', to='castor_scheduling.wbsversion', verbose_name='Parent Version')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_versions', to='environments.project', verbose_name='Project')),
                ('source_version', models.ForeignKey(blank=True, help_text='Nullable for manual WBS hierarchies.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wbs_versions', to='castor_scheduling.schedulesourceversion', verbose_name='Source Version')),
            ],
            options={
                'verbose_name': 'WBS Version',
                'verbose_name_plural': 'WBS Versions',
                'ordering': ['-created_at', '-revision_number'],
            },
        ),
        migrations.AddField(
            model_name='wbsnode',
            name='wbs_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='castor_scheduling.wbsversion', verbose_name='WBS Version'),
        ),
        migrations.AddIndex(
            model_name='wbsversion',
            index=models.Index(fields=['project', 'status'], name='castor_sche_project_9d3090_idx'),
        ),
        migrations.AddIndex(
            model_name='wbsversion',
            index=models.Index(fields=['project', 'revision_number'], name='castor_sche_project_bf1741_idx'),
        ),
        migrations.AddIndex(
            model_name='wbsversion',
            index=models.Index(fields=['project', 'is_selected_for_analysis'], name='castor_sche_project_bc7e6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='wbsversion',
            constraint=models.UniqueConstraint(fields=('project', 'revision_number'), name='castor_scheduling_unique_wbs_revision_per_project'),
        ),
        migrations.AddConstraint(
            model_name='wbsversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_selected_for_analysis', True)), fields=('project',), name='castor_scheduling_unique_selected_wbs_per_project'),
        ),
        migrations.AddIndex(
            model_name='wbsnode',
            index=models.Index(fields=['wbs_version', 'parent'], name='castor_sche_wbs_ver_db8938_idx'),
        ),
        migrations.AddIndex(
            model_name='wbsnode',
            index=models.Index(fields=['wbs_version', 'path'], name='castor_sche_wbs_ver_f807d7_idx'),
        ),
        migrations.AddIndex(
            model_name='wbsnode',
            index=models.Index(fields=['wbs_version', 'code'], name='castor_sche_wbs_ver_b598c8_idx'),
        ),
        migrations.AddIndex(
            model_name='wbsnode',
            index=models.Index(fields=['wbs_version', 'depth'], name='castor_sche_wbs_ver_ba75b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='wbsnode',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('wbs_version', 'external_id'), name='castor_scheduling_unique_wbs_external_id_per_version'),
        ),
    ]
