# Generated by Django 6.0.2 on 2026-06-15 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castor_scheduling', '0030_governed_mapping_domain'),
        ('ifc_processor', '0011_ifcentity_ifc_description_ifcentity_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analyticalmappingassignment',
            name='castor_scheduling_mapping_assignment_one_target',
        ),
        migrations.AddField(
            model_name='analyticalmappingassignment',
            name='schedule_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytical_mapping_assignments', to='castor_scheduling.scheduleactivity', verbose_name='Schedule Activity'),
        ),
        migrations.AlterField(
            model_name='analyticalmappingassignment',
            name='target_type',
            field=models.CharField(choices=[('task', 'Task'), ('wbs_node', 'WBS Node'), ('ifc_entity', 'IFC Entity'), ('schedule_activity', 'Schedule Activity')], db_index=True, max_length=20, verbose_name='Target Type'),
        ),
        migrations.AlterField(
            model_name='mappinggovernanceevent',
            name='event_type',
            field=models.CharField(choices=[('dimension_created', 'Dimension created'), ('dimension_activated', 'Dimension activated'), ('dimension_superseded', 'Dimension superseded'), ('value_created', 'Value created'), ('value_retired', 'Value retired'), ('mapping_set_created', 'Mapping set created'), ('mapping_set_submitted', 'Mapping set submitted'), ('mapping_set_approved', 'Mapping set approved'), ('mapping_set_activated', 'Mapping set activated'), ('mapping_set_rejected', 'Mapping set rejected'), ('assignment_proposed', 'Assignment proposed'), ('assignment_approved', 'Assignment approved'), ('assignment_rejected', 'Assignment rejected'), ('conflict_detected', 'Conflict detected'), ('revision_superseded', 'Revision superseded'), ('mapping_population_started', 'Population started'), ('mapping_population_completed', 'Population completed'), ('mapping_population_failed', 'Population failed'), ('proposal_adopted', 'Proposal adopted'), ('proposal_duplicate_skipped', 'Proposal duplicate skipped'), ('mapping_set_activation_failed', 'Mapping set activation failed'), ('cross_version_mapping_resolved', 'Cross-version resolved'), ('cross_version_mapping_blocked', 'Cross-version blocked'), ('adoption_dry_run', 'Adoption dry run'), ('authoritative_mapping_imported', 'Authoritative imported')], db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='analyticalmappingassignment',
            index=models.Index(fields=['schedule_activity', 'governance_status'], name='castor_sche_schedul_ab5c48_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticalmappingassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entity_global_id', ''), ('schedule_activity_id__isnull', True), ('target_type', 'task'), ('task_id__isnull', False), ('wbs_node_id__isnull', True)), models.Q(('entity_global_id', ''), ('schedule_activity_id__isnull', True), ('target_type', 'wbs_node'), ('task_id__isnull', True), ('wbs_node_id__isnull', False)), models.Q(('entity_global_id__gt', ''), ('schedule_activity_id__isnull', True), ('target_type', 'ifc_entity'), ('task_id__isnull', True), ('wbs_node_id__isnull', True)), models.Q(('entity_global_id', ''), ('schedule_activity_id__isnull', False), ('target_type', 'schedule_activity'), ('task_id__isnull', True), ('wbs_node_id__isnull', True)), _connector='OR'), name='castor_scheduling_mapping_assignment_one_target'),
        ),
    ]
