# Generated by Django 6.0.2 on 2026-07-18 19:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("castor_scheduling", "0032_event_target_type_length"),
        ("environments", "0008_alter_project_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional project-scoped code; unique per project when non-blank.",
                        max_length=128,
                        verbose_name="Resource Code",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("labor", "Labor"),
                            ("material", "Material"),
                            ("equipment", "Equipment"),
                            ("subcontract", "Subcontract"),
                            ("cost", "Cost"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=20,
                        verbose_name="Resource Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Importer hint: p6xml, xer, msp, manual, etc.",
                        max_length=32,
                        verbose_name="Source System",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="External ID"
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Unit of Measure"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ISO-like currency code when known; blank if unknown.",
                        max_length=16,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "default_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Optional reference rate — not used by EVM in DF-E1.",
                        max_digits=16,
                        null=True,
                        verbose_name="Default Rate",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadata")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
                "ordering": ["name", "resource_code"],
            },
        ),
        migrations.CreateModel(
            name="ResourceAssignment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="Source System"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stable assignment identity from the source planner when available.",
                        max_length=255,
                        verbose_name="External Assignment ID",
                    ),
                ),
                (
                    "p6_resource_object_id",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="P6 Resource ObjectId"
                    ),
                ),
                (
                    "p6_assignment_object_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Future-proof P6 ResourceAssignment ObjectId when available.",
                        max_length=50,
                        verbose_name="P6 Assignment ObjectId",
                    ),
                ),
                (
                    "planned_units",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=16,
                        null=True,
                        verbose_name="Planned Units",
                    ),
                ),
                (
                    "planned_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="Planned Cost",
                    ),
                ),
                (
                    "actual_units",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=16,
                        null=True,
                        verbose_name="Actual Units",
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="Actual Cost",
                    ),
                ),
                (
                    "remaining_units",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=16,
                        null=True,
                        verbose_name="Remaining Units",
                    ),
                ),
                (
                    "remaining_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="Remaining Cost",
                    ),
                ),
                (
                    "at_completion_units",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=16,
                        null=True,
                        verbose_name="At Completion Units",
                    ),
                ),
                (
                    "at_completion_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="At Completion Cost",
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Unit of Measure"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="Currency"
                    ),
                ),
                (
                    "is_pending",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="True until import/population is confirmed (DF-E2).",
                        verbose_name="Pending",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadata")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_assignments",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="castor_scheduling.resource",
                        verbose_name="Resource",
                    ),
                ),
                (
                    "schedule_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_assignments",
                        to="castor_scheduling.scheduleactivity",
                        verbose_name="Schedule Activity",
                    ),
                ),
                (
                    "schedule_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canonical_resource_assignments",
                        to="castor_scheduling.schedulesource",
                        verbose_name="Legacy Schedule Source",
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_assignments",
                        to="castor_scheduling.schedulesourceversion",
                        verbose_name="Source Version",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canonical_resource_assignments",
                        to="castor_scheduling.task",
                        verbose_name="Task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Assignment",
                "verbose_name_plural": "Resource Assignments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["project", "status"], name="castor_sche_project_807d2d_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["project", "resource_type"], name="castor_sche_project_a77e68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["project", "external_id"], name="castor_sche_project_210f94_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resource_code__gt", "")),
                fields=("project", "resource_code"),
                name="castor_scheduling_unique_resource_code_per_project",
            ),
        ),
        migrations.AddIndex(
            model_name="resourceassignment",
            index=models.Index(fields=["project", "task"], name="castor_sche_project_dd447c_idx"),
        ),
        migrations.AddIndex(
            model_name="resourceassignment",
            index=models.Index(
                fields=["project", "resource"], name="castor_sche_project_a6d436_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceassignment",
            index=models.Index(
                fields=["project", "source_version"], name="castor_sche_project_c7d937_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceassignment",
            index=models.Index(fields=["project", "status"], name="castor_sche_project_0da331_idx"),
        ),
        migrations.AddIndex(
            model_name="resourceassignment",
            index=models.Index(
                fields=["project", "is_pending"], name="castor_sche_project_9fcef6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="resourceassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__gt", ""), ("source_version__isnull", False)),
                fields=("project", "source_version", "source_system", "external_id"),
                name="castor_scheduling_unique_ra_source_identity",
            ),
        ),
    ]
