# Generated by Django 5.2.11 on 2026-09-07 11:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("environments", "0008_alter_project_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationSchema",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("platform", "Platform"), ("project", "Project")],
                        db_index=True,
                        max_length=20,
                        verbose_name="Scope",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable slug within scope/project.",
                        max_length=64,
                        verbose_name="Key",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "edition",
                    models.CharField(
                        help_text="Required version / edition marker. Do not silently overwrite published codes.",
                        max_length=64,
                        verbose_name="Edition",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("external_standard", "External standard"),
                            ("internal_element", "Internal element"),
                            ("package", "Package"),
                            ("work_package", "Work package"),
                            ("document_metadata", "Document metadata"),
                            ("asset_fm", "Asset / FM"),
                            ("external_reference", "External reference"),
                            ("custom", "Custom"),
                            ("boq_cost_later", "BOQ / cost (reserved — not current readiness)"),
                        ],
                        db_index=True,
                        help_text="Schema purpose. boq_cost_later is reserved/future only — not BOQ generation, not cost estimate, not 5D/EVM.",
                        max_length=32,
                        verbose_name="Purpose",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("builtin_template", "Built-in template"),
                            ("imported", "Imported"),
                            ("user_defined", "User defined"),
                            ("forked", "Forked"),
                        ],
                        db_index=True,
                        help_text="builtin_template is reserved; do not treat as an official Uniclass/OmniClass/MasterFormat pack unless verified.",
                        max_length=32,
                        verbose_name="Origin",
                    ),
                ),
                ("source_uri", models.URLField(blank=True, default="", verbose_name="Source URI")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_editable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether nodes may be edited by users.",
                        verbose_name="Editable",
                    ),
                ),
                (
                    "is_official_claim",
                    models.BooleanField(
                        default=False,
                        help_text="Default false. Set true only after licensing/verification of an external standard pack. Not an automatic certification flag.",
                        verbose_name="Official claim",
                    ),
                ),
                (
                    "contract_version",
                    models.CharField(
                        default="classification-registry-c1-v1",
                        max_length=64,
                        verbose_name="Contract version",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classification_schemas_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required when scope is project; must be empty for platform scope.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification_schemas",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classification Schema",
                "verbose_name_plural": "Classification Schemas",
                "ordering": ["key", "edition"],
            },
        ),
        migrations.CreateModel(
            name="ClassificationNode",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=128, verbose_name="Code")),
                ("label", models.CharField(max_length=255, verbose_name="Label")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Description"),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional denormalized path.",
                        max_length=512,
                        verbose_name="Path",
                    ),
                ),
                ("depth", models.PositiveIntegerField(default=0, verbose_name="Depth")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sort order")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="External ID"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Sparse JSON; future locale labels may live here. Not multilingual MVP.",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional parent node; must belong to the same schema.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="classification.classificationnode",
                        verbose_name="Parent",
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="classification.classificationschema",
                        verbose_name="Schema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classification Node",
                "verbose_name_plural": "Classification Nodes",
                "ordering": ["schema", "sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="ProjectClassificationSchema",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose_role",
                    models.CharField(
                        choices=[
                            ("element", "Element"),
                            ("package", "Package"),
                            ("work_package", "Work package"),
                            ("document_metadata", "Document metadata"),
                            ("asset_fm", "Asset / FM"),
                            ("external_reference", "External reference"),
                            ("custom", "Custom"),
                            ("boq_cost_later", "BOQ / cost (reserved — not current readiness)"),
                        ],
                        db_index=True,
                        help_text="Adoption role for this project. boq_cost_later is reserved/future — not current BOQ/cost/5D readiness.",
                        max_length=32,
                        verbose_name="Purpose role",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="At most one primary active adoption per project + purpose_role.",
                        verbose_name="Primary",
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="Priority")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "adopted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Adopted at"),
                ),
                (
                    "adopted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classification_schemas_adopted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Adopted by",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification_schema_adoptions",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_adoptions",
                        to="classification.classificationschema",
                        verbose_name="Schema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Classification Schema",
                "verbose_name_plural": "Project Classification Schemas",
                "ordering": ["project", "purpose_role", "-is_primary", "priority"],
            },
        ),
        migrations.AddIndex(
            model_name="classificationschema",
            index=models.Index(fields=["scope", "status"], name="classificat_scope_29af72_idx"),
        ),
        migrations.AddIndex(
            model_name="classificationschema",
            index=models.Index(fields=["purpose", "origin"], name="classificat_purpose_36d47b_idx"),
        ),
        migrations.AddIndex(
            model_name="classificationschema",
            index=models.Index(fields=["project", "key"], name="classificat_project_b02468_idx"),
        ),
        migrations.AddConstraint(
            model_name="classificationschema",
            constraint=models.UniqueConstraint(
                fields=("scope", "project", "key", "edition"),
                name="uniq_classification_schema_scope_project_key_edition",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="classificationschema",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("project__isnull", True), ("scope", "platform")),
                    models.Q(("project__isnull", False), ("scope", "project")),
                    _connector="OR",
                ),
                name="classification_schema_scope_project_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="classificationnode",
            index=models.Index(fields=["schema", "status"], name="classificat_schema__feb0fd_idx"),
        ),
        migrations.AddIndex(
            model_name="classificationnode",
            index=models.Index(fields=["schema", "parent"], name="classificat_schema__ceebd8_idx"),
        ),
        migrations.AddConstraint(
            model_name="classificationnode",
            constraint=models.UniqueConstraint(
                fields=("schema", "code"), name="uniq_classification_node_schema_code"
            ),
        ),
        migrations.AddIndex(
            model_name="projectclassificationschema",
            index=models.Index(
                fields=["project", "purpose_role", "status"], name="classificat_project_d977fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectclassificationschema",
            index=models.Index(
                fields=["project", "is_primary"], name="classificat_project_70c1da_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectclassificationschema",
            constraint=models.UniqueConstraint(
                fields=("project", "purpose_role", "schema"),
                name="uniq_project_classification_schema_role_schema",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectclassificationschema",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True), ("status", "active")),
                fields=("project", "purpose_role"),
                name="uniq_primary_active_class_schema_per_project_role",
            ),
        ),
    ]
