# Generated by Django 6.0.2 on 2026-05-14 06:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("environments", "0005_projectrole_assigned_space"),
        ("ifc_processor", "0011_ifcentity_ifc_description_ifcentity_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=500, verbose_name="Task Name")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("start_date", models.DateField(db_index=True, verbose_name="Start Date")),
                ("end_date", models.DateField(db_index=True, verbose_name="End Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("complete", "Complete"),
                            ("delayed", "Delayed"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("excel", "Excel (.xlsx)"),
                            ("xer", "Primavera P6 (.xer)"),
                            ("msp", "MS Project (.xml)"),
                            ("manual", "Manual entry"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                (
                    "activity_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Used to match this task to IFC elements by parameter value",
                        max_length=255,
                        verbose_name="Activity Code",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Hex colour shown in the Gantt and 3D viewer",
                        max_length=20,
                        verbose_name="Bar Colour",
                    ),
                ),
                (
                    "ifc_entities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Read-only from the IFC perspective — set only by the TimeLiner",
                        related_name="schedule_tasks",
                        to="ifc_processor.ifcentity",
                        verbose_name="Linked IFC Entities",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_tasks",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Task",
                "verbose_name_plural": "Schedule Tasks",
                "ordering": ["start_date", "name"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"], name="islam_sched_project_345b2f_idx"
                    ),
                    models.Index(
                        fields=["project", "start_date", "end_date"],
                        name="islam_sched_project_ac1c29_idx",
                    ),
                ],
            },
        ),
    ]
