# Generated by Django 6.0.2 on 2026-06-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("castor_scheduling", "0019_add_percent_complete_to_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulesource",
            name="data_date",
            field=models.DateField(
                blank=True,
                help_text="DataDate from P6 XML — the date through which progress was recorded. Absent for CSV/Excel imports. All EVM metrics are computed as-of this date.",
                null=True,
                verbose_name="P6 Data Date",
            ),
        ),
    ]
