# Generated by Django 6.0.2 on 2026-05-14 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0005_projectrole_assigned_space'),
    ]

    operations = [
        migrations.CreateModel(
            name='IslamLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('z_elevation', models.FloatField()),
                ('ifc_storey_global_id', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(choices=[('ifc', 'From IFC'), ('suggested', 'Suggested'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islam_levels', to='environments.project')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'ordering': ['z_elevation'],
                'indexes': [models.Index(fields=['project'], name='islam_ifc_i_project_c13295_idx')],
            },
        ),
    ]
