# facilities/urls.py
"""URL routes for the Facilities tab (7D FM)."""

from django.urls import path

from . import views

app_name = "facilities"

urlpatterns = [
    # Dashboard sub-tab (role-aware landing) — default Facilities entry.
    path("<uuid:pk>/facilities/", views.FacilitiesView.as_view(), name="tab"),
    path(
        "<uuid:pk>/facilities/role/switch/",
        views.RoleSwitchView.as_view(),
        name="role_switch",
    ),
    # Asset Register (M1).
    path(
        "<uuid:pk>/facilities/assets/",
        views.AssetListView.as_view(),
        name="assets_list",
    ),
    path(
        "<uuid:pk>/facilities/assets/promote/",
        views.AssetPromoteView.as_view(),
        name="assets_promote",
    ),
    path(
        "<uuid:pk>/facilities/assets/create-manual/",
        views.AssetCreateManualView.as_view(),
        name="assets_create_manual",
    ),
    path(
        "<uuid:pk>/facilities/assets/bulk/",
        views.AssetBulkView.as_view(),
        name="assets_bulk",
    ),
    path(
        "<uuid:pk>/facilities/assets/import/",
        views.AssetCSVImportView.as_view(),
        name="assets_import",
    ),
    path(
        "<uuid:pk>/facilities/assets/qr/",
        views.AssetQRLabelsView.as_view(),
        name="assets_qr_labels",
    ),
    path(
        "<uuid:pk>/facilities/assets/<uuid:asset_pk>/",
        views.AssetDetailView.as_view(),
        name="assets_detail",
    ),
    path(
        "<uuid:pk>/facilities/assets/<uuid:asset_pk>/update/",
        views.AssetUpdateView.as_view(),
        name="assets_update",
    ),
    # Export Reconciliation (M2).
    path(
        "<uuid:pk>/facilities/export/preview/",
        views.ExportPreviewView.as_view(),
        name="export_preview",
    ),
    path(
        "<uuid:pk>/facilities/export/apply/",
        views.ExportApplyView.as_view(),
        name="export_apply",
    ),
    # Work Orders (M3).
    path(
        "<uuid:pk>/facilities/work/",
        views.WorkOrderListView.as_view(),
        name="work_list",
    ),
    path(
        "<uuid:pk>/facilities/work/kanban/",
        views.WorkOrderKanbanView.as_view(),
        name="work_kanban",
    ),
    path(
        "<uuid:pk>/facilities/work/calendar/",
        views.WorkOrderCalendarView.as_view(),
        name="work_calendar",
    ),
    path(
        "<uuid:pk>/facilities/work/create/",
        views.WorkOrderCreateView.as_view(),
        name="work_create",
    ),
    path(
        "<uuid:pk>/facilities/work/bulk/",
        views.WorkOrderBulkView.as_view(),
        name="work_bulk",
    ),
    path(
        "<uuid:pk>/facilities/work/<uuid:wo_pk>/",
        views.WorkOrderDetailView.as_view(),
        name="work_detail",
    ),
    path(
        "<uuid:pk>/facilities/work/<uuid:wo_pk>/update/",
        views.WorkOrderUpdateView.as_view(),
        name="work_update",
    ),
    path(
        "<uuid:pk>/facilities/work/<uuid:wo_pk>/transition/<str:transition>/",
        views.WorkOrderTransitionView.as_view(),
        name="work_transition",
    ),
    path(
        "<uuid:pk>/facilities/work/<uuid:wo_pk>/attachments/",
        views.WorkOrderAttachmentView.as_view(),
        name="work_attachment",
    ),
    path(
        "<uuid:pk>/facilities/work/<uuid:wo_pk>/permits/link/",
        views.WorkOrderPermitLinkView.as_view(),
        name="work_permit_link",
    ),
    path(
        "<uuid:pk>/facilities/work/<uuid:wo_pk>/permits/<uuid:permit_pk>/unlink/",
        views.WorkOrderPermitUnlinkView.as_view(),
        name="work_permit_unlink",
    ),
    # Permits (M3).
    path(
        "<uuid:pk>/facilities/permits/",
        views.PermitListView.as_view(),
        name="permit_list",
    ),
    path(
        "<uuid:pk>/facilities/permits/create/",
        views.PermitCreateView.as_view(),
        name="permit_create",
    ),
    path(
        "<uuid:pk>/facilities/permits/<uuid:permit_pk>/",
        views.PermitDetailView.as_view(),
        name="permit_detail",
    ),
    path(
        "<uuid:pk>/facilities/permits/<uuid:permit_pk>/update/",
        views.PermitUpdateView.as_view(),
        name="permit_update",
    ),
    path(
        "<uuid:pk>/facilities/permits/<uuid:permit_pk>/revoke/",
        views.PermitRevokeView.as_view(),
        name="permit_revoke",
    ),
    # Action Requests (M3).
    path(
        "<uuid:pk>/facilities/action-requests/",
        views.ActionRequestListView.as_view(),
        name="ar_list",
    ),
    path(
        "<uuid:pk>/facilities/action-requests/create/",
        views.ActionRequestCreateView.as_view(),
        name="ar_create",
    ),
    path(
        "<uuid:pk>/facilities/action-requests/<uuid:ar_pk>/",
        views.ActionRequestDetailView.as_view(),
        name="ar_detail",
    ),
    path(
        "<uuid:pk>/facilities/action-requests/<uuid:ar_pk>/update/",
        views.ActionRequestUpdateView.as_view(),
        name="ar_update",
    ),
    path(
        "<uuid:pk>/facilities/action-requests/<uuid:ar_pk>/triage/",
        views.ActionRequestTriageView.as_view(),
        name="ar_triage",
    ),
    path(
        "<uuid:pk>/facilities/action-requests/<uuid:ar_pk>/dismiss/",
        views.ActionRequestDismissView.as_view(),
        name="ar_dismiss",
    ),
    path(
        "<uuid:pk>/facilities/action-requests/<uuid:ar_pk>/escalate/",
        views.ActionRequestEscalateView.as_view(),
        name="ar_escalate",
    ),
    # Occupant Portal (M4).
    path(
        "<uuid:pk>/facilities/portal/intake/",
        views.OccupantPortalIntakeView.as_view(),
        name="portal_intake",
    ),
    path(
        "<uuid:pk>/facilities/portal/intake/confirm/",
        views.OccupantPortalConfirmView.as_view(),
        name="portal_intake_confirm",
    ),
    # Intent-to-WO (M3.E).
    path(
        "<uuid:pk>/facilities/work/intent/",
        views.WorkOrderIntentView.as_view(),
        name="work_intent",
    ),
    path(
        "<uuid:pk>/facilities/work/intent/<uuid:proposal_pk>/confirm/",
        views.WorkOrderIntentConfirmView.as_view(),
        name="work_intent_confirm",
    ),
    path(
        "<uuid:pk>/facilities/work/intent/<uuid:proposal_pk>/reject/",
        views.WorkOrderIntentRejectView.as_view(),
        name="work_intent_reject",
    ),
    # Explore — floor-plan + photo / 360° viewer (iframe-embedded).
    path(
        "<uuid:pk>/facilities/explore/",
        views.ExploreView.as_view(),
        name="explore",
    ),
    # Serves Pavla's vendored module assets from facilities/explore/ (NOT
    # under collectstatic — peer module, not Django static). The iframe loads
    # `embed/index.html`; every relative asset Pavla's code references is
    # delivered through the same `<path:resource>` capture.
    path(
        "<uuid:pk>/facilities/explore/embed/<path:resource>",
        views.ExploreEmbedView.as_view(),
        name="explore_embed",
    ),
    path(
        "<uuid:pk>/facilities/explore/floors/",
        views.ExploreFloorsApiView.as_view(),
        name="explore_floors",
    ),
    path(
        "<uuid:pk>/facilities/explore/rooms/<uuid:storey_pk>/",
        views.ExploreRoomsApiView.as_view(),
        name="explore_rooms",
    ),
    path(
        "<uuid:pk>/facilities/explore/catalog/",
        views.ExploreCatalogApiView.as_view(),
        name="explore_catalog",
    ),
    path(
        "<uuid:pk>/facilities/explore/state/",
        views.ExploreUserStateApiView.as_view(),
        name="explore_state",
    ),
    path(
        "<uuid:pk>/facilities/explore/floor-plans/<uuid:storey_pk>/upload/",
        views.ExploreFloorPlanUploadView.as_view(),
        name="explore_floor_plan_upload",
    ),
    path(
        "<uuid:pk>/facilities/explore/floor-plans/<uuid:storey_pk>/delete/",
        views.ExploreFloorPlanDeleteView.as_view(),
        name="explore_floor_plan_delete",
    ),
    path(
        "<uuid:pk>/facilities/explore/floor-plans/<uuid:storey_pk>/visibility/",
        views.ExploreFloorVisibilityView.as_view(),
        name="explore_floor_visibility",
    ),
    path(
        "<uuid:pk>/facilities/explore/floor-plans/<uuid:storey_pk>/rename/",
        views.ExploreFloorRenameView.as_view(),
        name="explore_floor_rename",
    ),
]
