# scheduling/urls.py
"""URL routes for the 4D Scheduling app — tasks, parsers, CPM, EVM, Monte Carlo,
intelligence, writeback, and manual element linking.
"""

from django.urls import path

from . import (
    views,
    views_analytical_snapshot,
    views_baseline,
    views_executive_controls,
    views_source_provenance,
)

app_name = "scheduling"

urlpatterns = [
    # Main entry point
    path("projects/<uuid:pk>/", views.ScheduleView.as_view(), name="schedule"),
    # Data sources / parsers
    path(
        "projects/<uuid:pk>/preview/",
        views.SchedulePreviewView.as_view(),
        name="schedule_preview",
    ),
    path(
        "projects/<uuid:pk>/upload/",
        views.TaskUploadView.as_view(),
        name="schedule_upload",
    ),
    path(
        "projects/<uuid:pk>/save/",
        views.TaskSaveView.as_view(),
        name="schedule_save",
    ),
    path(
        "projects/<uuid:pk>/clear/",
        views.ScheduleClearView.as_view(),
        name="schedule_clear",
    ),
    path(
        "projects/<uuid:pk>/source/<uuid:source_pk>/delete/",
        views.ScheduleSourceDeleteView.as_view(),
        name="schedule_source_delete",
    ),
    path(
        "projects/<uuid:pk>/source/<uuid:source_pk>/preview/",
        views.ScheduleSourcePreviewView.as_view(),
        name="schedule_source_preview",
    ),
    path(
        "projects/<uuid:pk>/source-versions/",
        views_source_provenance.SourceVersionListView.as_view(),
        name="schedule_source_versions",
    ),
    path(
        "projects/<uuid:pk>/import-runs/",
        views_source_provenance.ImportRunListView.as_view(),
        name="schedule_import_runs",
    ),
    path(
        "projects/<uuid:pk>/tasks/<uuid:task_pk>/provenance/",
        views_source_provenance.TaskProvenanceView.as_view(),
        name="task_provenance",
    ),
    path(
        "projects/<uuid:pk>/baselines/",
        views_baseline.BaselineListView.as_view(),
        name="schedule_baselines",
    ),
    path(
        "projects/<uuid:pk>/baselines/selected/",
        views_baseline.BaselineSelectedView.as_view(),
        name="schedule_baseline_selected",
    ),
    path(
        "projects/<uuid:pk>/baselines/comparison/",
        views_baseline.BaselineComparisonView.as_view(),
        name="schedule_baseline_comparison",
    ),
    path(
        "projects/<uuid:pk>/baselines/<uuid:baseline_pk>/",
        views_baseline.BaselineDetailView.as_view(),
        name="schedule_baseline_detail",
    ),
    path(
        "projects/<uuid:pk>/baselines/<uuid:baseline_pk>/task-states/",
        views_baseline.BaselineTaskStateListView.as_view(),
        name="schedule_baseline_task_states",
    ),
    path(
        "projects/<uuid:pk>/analytical-snapshots/",
        views_analytical_snapshot.AnalyticalSnapshotListView.as_view(),
        name="schedule_analytical_snapshots",
    ),
    path(
        "projects/<uuid:pk>/analytical-snapshots/latest/",
        views_analytical_snapshot.AnalyticalSnapshotLatestView.as_view(),
        name="schedule_analytical_snapshots_latest",
    ),
    path(
        "projects/<uuid:pk>/analytical-snapshots/<uuid:snapshot_pk>/",
        views_analytical_snapshot.AnalyticalSnapshotDetailView.as_view(),
        name="schedule_analytical_snapshot_detail",
    ),
    path(
        "projects/<uuid:pk>/analytical-snapshots/<uuid:snapshot_pk>/result/",
        views_analytical_snapshot.AnalyticalSnapshotResultView.as_view(),
        name="schedule_analytical_snapshot_result",
    ),
    path(
        "projects/<uuid:pk>/analytical-snapshots/<uuid:snapshot_pk>/series/",
        views_analytical_snapshot.AnalyticalSnapshotSeriesView.as_view(),
        name="schedule_analytical_snapshot_series",
    ),
    path(
        "projects/<uuid:pk>/analytical-snapshots/<uuid:snapshot_pk>/periods/",
        views_analytical_snapshot.AnalyticalSnapshotPeriodsView.as_view(),
        name="schedule_analytical_snapshot_periods",
    ),
    path(
        "projects/<uuid:pk>/analytical-snapshots/compare/",
        views_analytical_snapshot.AnalyticalSnapshotCompareView.as_view(),
        name="schedule_analytical_snapshots_compare",
    ),
    path(
        "projects/<uuid:pk>/analytical-snapshots/<uuid:snapshot_pk>/report-data/",
        views_analytical_snapshot.AnalyticalSnapshotReportDataView.as_view(),
        name="schedule_analytical_snapshot_report_data",
    ),
    path(
        "projects/<uuid:pk>/all-tasks-preview/",
        views.AllTasksPreviewView.as_view(),
        name="all_tasks_preview",
    ),
    # Mapping
    path(
        "projects/<uuid:pk>/mapping/submit/",
        views.MappingSubmitView.as_view(),
        name="schedule_mapping_submit",
    ),
    path(
        "projects/<uuid:pk>/detect-columns/",
        views.DetectColumnsView.as_view(),
        name="schedule_detect_columns",
    ),
    path(
        "projects/<uuid:pk>/mapping-lookup/save/",
        views.SaveMappingLookupView.as_view(),
        name="schedule_save_mapping_lookup",
    ),
    # Analytics
    path(
        "projects/<uuid:pk>/wbs-heatmap/",
        views.WBSHeatmapView.as_view(),
        name="wbs_heatmap",
    ),
    path(
        "projects/<uuid:pk>/delay-distribution/",
        views.DelayDistributionView.as_view(),
        name="delay_distribution",
    ),
    path(
        "projects/<uuid:pk>/trend-analysis/",
        views.TrendAnalysisView.as_view(),
        name="trend_analysis",
    ),
    path(
        "projects/<uuid:pk>/monte-carlo/",
        views.MonteCarloView.as_view(),
        name="monte_carlo",
    ),
    path(
        "projects/<uuid:pk>/completion-ml/",
        views.CompletionMLView.as_view(),
        name="completion_ml",
    ),
    path(
        "projects/<uuid:pk>/timelocation/",
        views.TimeLocationView.as_view(),
        name="timelocation",
    ),
    path(
        "projects/<uuid:pk>/audit/section-mismatches/",
        views.ScheduleAuditSectionMismatchView.as_view(),
        name="audit_section_mismatches",
    ),
    path(
        "projects/<uuid:pk>/delay-rootcause/",
        views.DelayRootCauseView.as_view(),
        name="delay_rootcause",
    ),
    path(
        "projects/<uuid:pk>/cashflow/",
        views.CashFlowView.as_view(),
        name="cashflow",
    ),
    path(
        "projects/<uuid:pk>/dcma-check/",
        views.DCMACheckView.as_view(),
        name="dcma_check",
    ),
    path(
        "projects/<uuid:pk>/anomalies/",
        views.AnomalyDetectionView.as_view(),
        name="anomaly_detection",
    ),
    path(
        "projects/<uuid:pk>/floor-health/",
        views.FloorHealthView.as_view(),
        name="floor_health",
    ),
    path(
        "projects/<uuid:pk>/decision-summary/",
        views.DecisionSummaryView.as_view(),
        name="decision_summary",
    ),
    path(
        "projects/<uuid:pk>/report/",
        views.ScheduleReportView.as_view(),
        name="schedule_report",
    ),
    # Autolink / param-link
    path(
        "projects/<uuid:pk>/link/smart/",
        views.AutoLinkView.as_view(),
        name="schedule_link_smart",
    ),
    path(
        "projects/<uuid:pk>/link/param/",
        views.LinkParamView.as_view(),
        name="schedule_link_param",
    ),
    path(
        "projects/<uuid:pk>/link/preview-param/",
        views.MatchPreviewView.as_view(),
        name="schedule_link_preview_param",
    ),
    path(
        "projects/<uuid:pk>/link/apply-approved-param/",
        views.ApplyApprovedMatchView.as_view(),
        name="schedule_link_apply_approved_param",
    ),
    # Task list / detail / Gantt / CPM
    path(
        "projects/<uuid:pk>/tasks/",
        views.TaskListPartialView.as_view(),
        name="task_list_partial",
    ),
    path(
        "projects/<uuid:pk>/tasks/<uuid:task_pk>/delete/",
        views.TaskDeleteView.as_view(),
        name="task_delete",
    ),
    path(
        "projects/<uuid:pk>/tasks/<uuid:task_pk>/actual-dates/",
        views.TaskActualDateView.as_view(),
        name="task_actual_dates",
    ),
    path(
        "projects/<uuid:pk>/gantt-data/",
        views.GanttDataView.as_view(),
        name="gantt_data",
    ),
    path(
        "projects/<uuid:pk>/task-detail/<uuid:task_pk>/",
        views.TaskDetailView.as_view(),
        name="task_detail",
    ),
    path(
        "projects/<uuid:pk>/critical-path/",
        views.CriticalPathView.as_view(),
        name="critical_path",
    ),
    path(
        "projects/<uuid:pk>/evm/",
        views.EVMDataView.as_view(),
        name="evm_data",
    ),
    # Intelligence (folded from castor.intelligence)
    path(
        "projects/<uuid:pk>/intelligence/",
        views.ScheduleIntelligenceView.as_view(),
        name="schedule_intelligence",
    ),
    path(
        "projects/<uuid:pk>/intelligence/status/",
        views.IntelligenceStatusView.as_view(),
        name="intelligence_status",
    ),
    path(
        "projects/<uuid:pk>/intelligence/embed/",
        views.IntelligenceEmbedView.as_view(),
        name="intelligence_embed",
    ),
    path(
        "projects/<uuid:pk>/intelligence/ask/",
        views.IntelligenceAskView.as_view(),
        name="intelligence_ask",
    ),
    path(
        "projects/<uuid:pk>/chat/",
        views.ScheduleChatView.as_view(),
        name="schedule_chat",
    ),
    path(
        "projects/<uuid:pk>/lookahead/",
        views.LookaheadDataView.as_view(),
        name="lookahead_data",
    ),
    path(
        "projects/<uuid:pk>/health-check/",
        views.ScheduleHealthCheckView.as_view(),
        name="schedule_health_check",
    ),
    path(
        "projects/<uuid:pk>/link-governance/summary/",
        views.LinkGovernanceSummaryView.as_view(),
        name="link_governance_summary",
    ),
    path(
        "projects/<uuid:pk>/link-governance/review-queue/",
        views.LinkGovernanceReviewQueueView.as_view(),
        name="link_governance_review_queue",
    ),
    path(
        "projects/<uuid:pk>/link-governance/workspace/",
        views.LinkGovernanceWorkspaceView.as_view(),
        name="link_governance_workspace",
    ),
    path(
        "projects/<uuid:pk>/link-governance/tasks/<uuid:task_pk>/",
        views.LinkGovernanceTaskView.as_view(),
        name="link_governance_task",
    ),
    path(
        "projects/<uuid:pk>/link-governance/entities/<str:global_id>/",
        views.LinkGovernanceEntityView.as_view(),
        name="link_governance_entity",
    ),
    path(
        "projects/<uuid:pk>/link-governance/decisions/<uuid:binding_pk>/preview/",
        views.LinkDecisionPreviewOneView.as_view(),
        name="link_decision_preview_one",
    ),
    path(
        "projects/<uuid:pk>/link-governance/decisions/<uuid:binding_pk>/apply/",
        views.LinkDecisionApplyOneView.as_view(),
        name="link_decision_apply_one",
    ),
    path(
        "projects/<uuid:pk>/link-governance/decisions/bulk/preview/",
        views.LinkDecisionBulkPreviewView.as_view(),
        name="link_decision_bulk_preview",
    ),
    path(
        "projects/<uuid:pk>/link-governance/decisions/bulk/apply/",
        views.LinkDecisionBulkApplyView.as_view(),
        name="link_decision_bulk_apply",
    ),
    path(
        "projects/<uuid:pk>/link-governance/reconciliation/",
        views.LinkGovernanceReconciliationView.as_view(),
        name="link_governance_reconciliation",
    ),
    path(
        "projects/<uuid:pk>/link-governance/reconciliation/<uuid:binding_pk>/",
        views.LinkGovernanceReconciliationDetailView.as_view(),
        name="link_governance_reconciliation_detail",
    ),
    path(
        "projects/<uuid:pk>/link-governance/lifecycle/<uuid:binding_pk>/reject/preview/",
        views.LinkLifecycleRejectPreviewView.as_view(),
        name="link_lifecycle_reject_preview",
    ),
    path(
        "projects/<uuid:pk>/link-governance/lifecycle/<uuid:binding_pk>/reject/apply/",
        views.LinkLifecycleRejectApplyView.as_view(),
        name="link_lifecycle_reject_apply",
    ),
    path(
        "projects/<uuid:pk>/link-governance/lifecycle/<uuid:binding_pk>/reaffirm/preview/",
        views.LinkLifecycleReaffirmPreviewView.as_view(),
        name="link_lifecycle_reaffirm_preview",
    ),
    path(
        "projects/<uuid:pk>/link-governance/lifecycle/<uuid:binding_pk>/reaffirm/apply/",
        views.LinkLifecycleReaffirmApplyView.as_view(),
        name="link_lifecycle_reaffirm_apply",
    ),
    path(
        "projects/<uuid:pk>/link-governance/lifecycle/<uuid:binding_pk>/reverse/preview/",
        views.LinkLifecycleReversePreviewView.as_view(),
        name="link_lifecycle_reverse_preview",
    ),
    path(
        "projects/<uuid:pk>/link-governance/lifecycle/<uuid:binding_pk>/reverse/apply/",
        views.LinkLifecycleReverseApplyView.as_view(),
        name="link_lifecycle_reverse_apply",
    ),
    path(
        "projects/<uuid:pk>/link-governance/lifecycle/<uuid:binding_pk>/supersede/preview/",
        views.LinkLifecycleSupersedePreviewView.as_view(),
        name="link_lifecycle_supersede_preview",
    ),
    path(
        "projects/<uuid:pk>/link-governance/lifecycle/<uuid:binding_pk>/supersede/apply/",
        views.LinkLifecycleSupersedeApplyView.as_view(),
        name="link_lifecycle_supersede_apply",
    ),
    path(
        "projects/<uuid:pk>/link-governance/lifecycle/<uuid:binding_pk>/supersede/pair/",
        views.LinkLifecycleSupersedePairView.as_view(),
        name="link_lifecycle_supersede_pair",
    ),
    path(
        "projects/<uuid:pk>/link-governance/lifecycle/parity/bulk/preview/",
        views.LinkLifecycleParityBulkPreviewView.as_view(),
        name="link_lifecycle_parity_bulk_preview",
    ),
    path(
        "projects/<uuid:pk>/link-governance/lifecycle/parity/bulk/apply/",
        views.LinkLifecycleParityBulkApplyView.as_view(),
        name="link_lifecycle_parity_bulk_apply",
    ),
    path(
        "projects/<uuid:pk>/link-governance/lifecycle/parity/preview/",
        views.LinkLifecycleParityPreviewView.as_view(),
        name="link_lifecycle_parity_preview",
    ),
    path(
        "projects/<uuid:pk>/link-governance/lifecycle/parity/apply/",
        views.LinkLifecycleParityApplyView.as_view(),
        name="link_lifecycle_parity_apply",
    ),
    path(
        "projects/<uuid:pk>/link-governance/audit/",
        views.LinkGovernanceAuditHistoryView.as_view(),
        name="link_governance_audit",
    ),
    path(
        "projects/<uuid:pk>/link-governance/overview/",
        views.LinkGovernanceOverviewView.as_view(),
        name="link_governance_overview",
    ),
    # E8-A — Executive controls analytical foundation (read-only)
    path(
        "projects/<uuid:pk>/executive-controls/",
        views_executive_controls.ExecutiveControlsOverviewPageView.as_view(),
        name="executive_controls",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/overview/",
        views_executive_controls.ExecutiveControlsOverviewJSONView.as_view(),
        name="executive_controls_overview",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/overview/schedule/",
        views_executive_controls.ExecutiveControlsOverviewScheduleView.as_view(),
        name="executive_controls_overview_schedule",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/overview/cost/",
        views_executive_controls.ExecutiveControlsOverviewCostView.as_view(),
        name="executive_controls_overview_cost",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/overview/delays/",
        views_executive_controls.ExecutiveControlsOverviewDelaysView.as_view(),
        name="executive_controls_overview_delays",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/overview/model-impact/",
        views_executive_controls.ExecutiveControlsOverviewModelView.as_view(),
        name="executive_controls_overview_model",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/overview/coverage/",
        views_executive_controls.ExecutiveControlsOverviewCoverageView.as_view(),
        name="executive_controls_overview_coverage",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/matrix/",
        views_executive_controls.ExecutiveControlsMatrixPageView.as_view(),
        name="executive_controls_matrix",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/matrix/rows/",
        views_executive_controls.ExecutiveControlsMatrixRowsView.as_view(),
        name="executive_controls_matrix_rows",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/matrix/activities/",
        views_executive_controls.ExecutiveControlsMatrixActivitiesView.as_view(),
        name="executive_controls_matrix_activities",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/trades/",
        views_executive_controls.ExecutiveControlsTradesPageView.as_view(),
        name="executive_controls_trades",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/trades/analysis/",
        views_executive_controls.ExecutiveControlsTradesAnalysisView.as_view(),
        name="executive_controls_trades_analysis",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/capabilities/",
        views_executive_controls.ExecutiveControlsCapabilitiesView.as_view(),
        name="executive_controls_capabilities",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/context/",
        views_executive_controls.ExecutiveControlsContextView.as_view(),
        name="executive_controls_context",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/methodology/",
        views_executive_controls.ExecutiveControlsMethodologyView.as_view(),
        name="executive_controls_methodology",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/coverage/",
        views_executive_controls.ExecutiveControlsCoverageView.as_view(),
        name="executive_controls_coverage",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/delays/summary/",
        views_executive_controls.ExecutiveControlsDelaySummaryView.as_view(),
        name="executive_controls_delay_summary",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/delays/",
        views_executive_controls.ExecutiveControlsDelayDetailView.as_view(),
        name="executive_controls_delays",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/evm/",
        views_executive_controls.ExecutiveControlsEVMPageView.as_view(),
        name="executive_controls_evm",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/evm/current/",
        views_executive_controls.ExecutiveControlsEVMCurrentView.as_view(),
        name="executive_controls_evm_current",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/evm/s-curve/",
        views_executive_controls.ExecutiveControlsEVMSCureView.as_view(),
        name="executive_controls_evm_scurve",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/evm/periods/",
        views_executive_controls.ExecutiveControlsEVMPeriodsView.as_view(),
        name="executive_controls_evm_periods",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/evm/methodology/",
        views_executive_controls.ExecutiveControlsEVMMethodologyView.as_view(),
        name="executive_controls_evm_methodology",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/evm-availability/",
        views_executive_controls.ExecutiveControlsEVMAvailabilityView.as_view(),
        name="executive_controls_evm_availability",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/resource-availability/",
        views_executive_controls.ExecutiveControlsResourceAvailabilityView.as_view(),
        name="executive_controls_resource_availability",
    ),
    path(
        "projects/<uuid:pk>/executive-controls/foundation/",
        views_executive_controls.ExecutiveControlsFoundationView.as_view(),
        name="executive_controls_foundation",
    ),
    path(
        "projects/<uuid:pk>/comprehension/",
        views.ProjectComprehensionView.as_view(),
        name="schedule_comprehension",
    ),
    # Link Review — binding review tab
    path(
        "projects/<uuid:pk>/review/",
        views.LinkReviewView.as_view(),
        name="review",
    ),
    path(
        "projects/<uuid:pk>/review/<uuid:binding_pk>/accept/",
        views.BindingAcceptView.as_view(),
        name="binding_accept",
    ),
    path(
        "projects/<uuid:pk>/review/<uuid:binding_pk>/remove/",
        views.BindingRemoveView.as_view(),
        name="binding_remove",
    ),
    path(
        "projects/<uuid:pk>/review/bulk-accept/",
        views.BulkAcceptView.as_view(),
        name="binding_bulk_accept",
    ),
    path(
        "projects/<uuid:pk>/review/export/",
        views.BindingExportView.as_view(),
        name="binding_export",
    ),
    path(
        "projects/<uuid:pk>/review/add/",
        views.BindingAddView.as_view(),
        name="binding_add",
    ),
    path(
        "projects/<uuid:pk>/review/search/",
        views.BindingSearchView.as_view(),
        name="binding_search",
    ),
    path(
        "projects/<uuid:pk>/review/task/<uuid:task_pk>/toggle-physical/",
        views.TaskToggleNonPhysicalView.as_view(),
        name="task_toggle_physical",
    ),
    # Schedule writeback
    path(
        "projects/<uuid:pk>/writeback/",
        views.ScheduleWritebackView.as_view(),
        name="schedule_writeback",
    ),
    # Manual element linking (tasks ↔ IFC entities)
    path(
        "projects/<uuid:pk>/tasks/<uuid:task_pk>/link-element/",
        views.LinkElementView.as_view(),
        name="link_element",
    ),
    path(
        "projects/<uuid:pk>/tasks/<uuid:task_pk>/unlink-element/",
        views.UnlinkElementView.as_view(),
        name="unlink_element",
    ),
    path(
        "projects/<uuid:pk>/elements/unlink-all/",
        views.UnlinkAllElementView.as_view(),
        name="unlink_all_element",
    ),
    path(
        "projects/<uuid:pk>/elements/tasks-for-link/",
        views.TasksForLinkView.as_view(),
        name="tasks_for_link",
    ),
    path(
        "projects/<uuid:pk>/elements/bulk-link/",
        views.BulkLinkElementView.as_view(),
        name="bulk_link_element",
    ),
]
