# scheduling/urls.py
"""URL routes for the 4D Scheduling app — tasks, parsers, CPM, EVM, Monte Carlo,
intelligence, writeback, and manual element linking.
"""

from django.urls import path

from . import views

app_name = "scheduling"

urlpatterns = [
    # Main entry point
    path("projects/<uuid:pk>/", views.ScheduleView.as_view(), name="schedule"),
    # Data sources / parsers
    path(
        "projects/<uuid:pk>/preview/",
        views.SchedulePreviewView.as_view(),
        name="schedule_preview",
    ),
    path(
        "projects/<uuid:pk>/upload/",
        views.TaskUploadView.as_view(),
        name="schedule_upload",
    ),
    path(
        "projects/<uuid:pk>/save/",
        views.TaskSaveView.as_view(),
        name="schedule_save",
    ),
    path(
        "projects/<uuid:pk>/clear/",
        views.ScheduleClearView.as_view(),
        name="schedule_clear",
    ),
    path(
        "projects/<uuid:pk>/source/<uuid:source_pk>/delete/",
        views.ScheduleSourceDeleteView.as_view(),
        name="schedule_source_delete",
    ),
    path(
        "projects/<uuid:pk>/source/<uuid:source_pk>/preview/",
        views.ScheduleSourcePreviewView.as_view(),
        name="schedule_source_preview",
    ),
    path(
        "projects/<uuid:pk>/all-tasks-preview/",
        views.AllTasksPreviewView.as_view(),
        name="all_tasks_preview",
    ),
    # Mapping
    path(
        "projects/<uuid:pk>/mapping/submit/",
        views.MappingSubmitView.as_view(),
        name="schedule_mapping_submit",
    ),
    path(
        "projects/<uuid:pk>/detect-columns/",
        views.DetectColumnsView.as_view(),
        name="schedule_detect_columns",
    ),
    path(
        "projects/<uuid:pk>/mapping-lookup/save/",
        views.SaveMappingLookupView.as_view(),
        name="schedule_save_mapping_lookup",
    ),
    # Analytics
    path(
        "projects/<uuid:pk>/wbs-heatmap/",
        views.WBSHeatmapView.as_view(),
        name="wbs_heatmap",
    ),
    path(
        "projects/<uuid:pk>/delay-distribution/",
        views.DelayDistributionView.as_view(),
        name="delay_distribution",
    ),
    path(
        "projects/<uuid:pk>/trend-analysis/",
        views.TrendAnalysisView.as_view(),
        name="trend_analysis",
    ),
    path(
        "projects/<uuid:pk>/monte-carlo/",
        views.MonteCarloView.as_view(),
        name="monte_carlo",
    ),
    path(
        "projects/<uuid:pk>/completion-ml/",
        views.CompletionMLView.as_view(),
        name="completion_ml",
    ),
    path(
        "projects/<uuid:pk>/timelocation/",
        views.TimeLocationView.as_view(),
        name="timelocation",
    ),
    path(
        "projects/<uuid:pk>/audit/section-mismatches/",
        views.ScheduleAuditSectionMismatchView.as_view(),
        name="audit_section_mismatches",
    ),
    path(
        "projects/<uuid:pk>/delay-rootcause/",
        views.DelayRootCauseView.as_view(),
        name="delay_rootcause",
    ),
    path(
        "projects/<uuid:pk>/cashflow/",
        views.CashFlowView.as_view(),
        name="cashflow",
    ),
    path(
        "projects/<uuid:pk>/dcma-check/",
        views.DCMACheckView.as_view(),
        name="dcma_check",
    ),
    path(
        "projects/<uuid:pk>/anomalies/",
        views.AnomalyDetectionView.as_view(),
        name="anomaly_detection",
    ),
    path(
        "projects/<uuid:pk>/floor-health/",
        views.FloorHealthView.as_view(),
        name="floor_health",
    ),
    path(
        "projects/<uuid:pk>/decision-summary/",
        views.DecisionSummaryView.as_view(),
        name="decision_summary",
    ),
    path(
        "projects/<uuid:pk>/report/",
        views.ScheduleReportView.as_view(),
        name="schedule_report",
    ),
    # Autolink / param-link
    path(
        "projects/<uuid:pk>/link/smart/",
        views.AutoLinkView.as_view(),
        name="schedule_link_smart",
    ),
    path(
        "projects/<uuid:pk>/link/param/",
        views.LinkParamView.as_view(),
        name="schedule_link_param",
    ),
    # Task list / detail / Gantt / CPM
    path(
        "projects/<uuid:pk>/tasks/",
        views.TaskListPartialView.as_view(),
        name="task_list_partial",
    ),
    path(
        "projects/<uuid:pk>/tasks/<uuid:task_pk>/delete/",
        views.TaskDeleteView.as_view(),
        name="task_delete",
    ),
    path(
        "projects/<uuid:pk>/tasks/<uuid:task_pk>/actual-dates/",
        views.TaskActualDateView.as_view(),
        name="task_actual_dates",
    ),
    path(
        "projects/<uuid:pk>/gantt-data/",
        views.GanttDataView.as_view(),
        name="gantt_data",
    ),
    path(
        "projects/<uuid:pk>/task-detail/<uuid:task_pk>/",
        views.TaskDetailView.as_view(),
        name="task_detail",
    ),
    path(
        "projects/<uuid:pk>/critical-path/",
        views.CriticalPathView.as_view(),
        name="critical_path",
    ),
    path(
        "projects/<uuid:pk>/evm/",
        views.EVMDataView.as_view(),
        name="evm_data",
    ),
    # Intelligence (folded from castor.intelligence)
    path(
        "projects/<uuid:pk>/intelligence/",
        views.ScheduleIntelligenceView.as_view(),
        name="schedule_intelligence",
    ),
    path(
        "projects/<uuid:pk>/intelligence/status/",
        views.IntelligenceStatusView.as_view(),
        name="intelligence_status",
    ),
    path(
        "projects/<uuid:pk>/intelligence/embed/",
        views.IntelligenceEmbedView.as_view(),
        name="intelligence_embed",
    ),
    path(
        "projects/<uuid:pk>/intelligence/ask/",
        views.IntelligenceAskView.as_view(),
        name="intelligence_ask",
    ),
    path(
        "projects/<uuid:pk>/chat/",
        views.ScheduleChatView.as_view(),
        name="schedule_chat",
    ),
    path(
        "projects/<uuid:pk>/lookahead/",
        views.LookaheadDataView.as_view(),
        name="lookahead_data",
    ),
    path(
        "projects/<uuid:pk>/health-check/",
        views.ScheduleHealthCheckView.as_view(),
        name="schedule_health_check",
    ),
    path(
        "projects/<uuid:pk>/comprehension/",
        views.ProjectComprehensionView.as_view(),
        name="schedule_comprehension",
    ),
    # Link Review — binding review tab
    path(
        "projects/<uuid:pk>/review/",
        views.LinkReviewView.as_view(),
        name="review",
    ),
    path(
        "projects/<uuid:pk>/review/<uuid:binding_pk>/accept/",
        views.BindingAcceptView.as_view(),
        name="binding_accept",
    ),
    path(
        "projects/<uuid:pk>/review/<uuid:binding_pk>/remove/",
        views.BindingRemoveView.as_view(),
        name="binding_remove",
    ),
    path(
        "projects/<uuid:pk>/review/bulk-accept/",
        views.BulkAcceptView.as_view(),
        name="binding_bulk_accept",
    ),
    path(
        "projects/<uuid:pk>/review/export/",
        views.BindingExportView.as_view(),
        name="binding_export",
    ),
    path(
        "projects/<uuid:pk>/review/add/",
        views.BindingAddView.as_view(),
        name="binding_add",
    ),
    path(
        "projects/<uuid:pk>/review/search/",
        views.BindingSearchView.as_view(),
        name="binding_search",
    ),
    path(
        "projects/<uuid:pk>/review/task/<uuid:task_pk>/toggle-physical/",
        views.TaskToggleNonPhysicalView.as_view(),
        name="task_toggle_physical",
    ),
    # Schedule writeback
    path(
        "projects/<uuid:pk>/writeback/",
        views.ScheduleWritebackView.as_view(),
        name="schedule_writeback",
    ),
    # Manual element linking (tasks ↔ IFC entities)
    path(
        "projects/<uuid:pk>/tasks/<uuid:task_pk>/link-element/",
        views.LinkElementView.as_view(),
        name="link_element",
    ),
    path(
        "projects/<uuid:pk>/tasks/<uuid:task_pk>/unlink-element/",
        views.UnlinkElementView.as_view(),
        name="unlink_element",
    ),
    path(
        "projects/<uuid:pk>/elements/unlink-all/",
        views.UnlinkAllElementView.as_view(),
        name="unlink_all_element",
    ),
    path(
        "projects/<uuid:pk>/elements/tasks-for-link/",
        views.TasksForLinkView.as_view(),
        name="tasks_for_link",
    ),
    path(
        "projects/<uuid:pk>/elements/bulk-link/",
        views.BulkLinkElementView.as_view(),
        name="bulk_link_element",
    ),
]
