# Generated by Django 5.2.11 on 2026-03-30 20:31

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("environments", "0002_alter_project_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "query_text",
                    models.TextField(help_text="The original user request.", verbose_name="Query"),
                ),
                (
                    "query_embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1024,
                        help_text="1024-dim embedding from EmbeddingService.embed_query().",
                        null=True,
                    ),
                ),
                (
                    "intent_json",
                    models.JSONField(
                        default=dict,
                        help_text="Structured modification intent (operation, filter, pset, etc.).",
                        verbose_name="Intent",
                    ),
                ),
                (
                    "entity_types",
                    models.JSONField(
                        default=list,
                        help_text='IFC classes targeted, e.g. ["IfcWall", "IfcSlab"]. Used for pre-filter.',
                        verbose_name="Entity Types",
                    ),
                ),
                (
                    "outcome_tier",
                    models.IntegerField(
                        help_text="RSAA tier at resolution (1, 2, or 3).", verbose_name="Tier"
                    ),
                ),
                (
                    "was_approved",
                    models.BooleanField(
                        default=False, help_text="True if a human reviewer approved the proposal."
                    ),
                ),
                (
                    "commit_success",
                    models.BooleanField(
                        default=False,
                        help_text="True if the IFC write and Git commit completed successfully.",
                    ),
                ),
                (
                    "is_organic",
                    models.BooleanField(
                        default=True,
                        help_text="False for seeded/synthetic examples from dev_cases.jsonl.",
                    ),
                ),
                (
                    "generated_code",
                    models.TextField(
                        blank=True,
                        help_text="Tier 3 only: the IfcOpenShell code that was generated and executed.",
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source project. Null for global synthetic examples.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skill_examples",
                        to="environments.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill Example",
                "verbose_name_plural": "Skill Examples",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["was_approved", "commit_success"], name="skill_approval_gate_idx"
                    )
                ],
            },
        ),
    ]
