# Generated by Django 5.2.11 on 2026-03-31 19:46

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0002_alter_project_options_and_more"),
        ("metacastor", "0001_initial"),
        ("writeback", "0007_modificationproposal_linked_conflict_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailureRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("query_text", models.TextField(verbose_name="Query")),
                (
                    "query_embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1024,
                        help_text="Nullable — Ollama may be unavailable at failure time.",
                        null=True,
                    ),
                ),
                ("intent_json", models.JSONField(default=dict, verbose_name="Intent")),
                (
                    "tier",
                    models.IntegerField(
                        blank=True,
                        help_text="RSAA tier at failure time. Null for early VALIDATION failures.",
                        null=True,
                    ),
                ),
                (
                    "failure_phase",
                    models.CharField(
                        choices=[
                            ("VALIDATION", "Validation"),
                            ("EXECUTION", "Execution"),
                            ("SANDBOX", "Sandbox"),
                        ],
                        max_length=20,
                        verbose_name="Phase",
                    ),
                ),
                ("error_type", models.CharField(max_length=40, verbose_name="Error Type")),
                ("error_detail", models.TextField(verbose_name="Error Detail")),
                ("diagnosis", models.TextField(verbose_name="Diagnosis")),
                (
                    "ifc_context",
                    models.JSONField(
                        default=dict,
                        help_text="Extracted IFC context: {operation, ifc_type, pset, property, value}.",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("RETRYABLE", "Retryable"), ("NON_RETRYABLE", "Non-Retryable")],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failure_records",
                        to="environments.project",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for VALIDATION-phase failures (no proposal created yet).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failure_records",
                        to="writeback.modificationproposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Failure Record",
                "verbose_name_plural": "Failure Records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "category", "-created_at"],
                        name="metacastor__project_2b4ac0_idx",
                    ),
                    models.Index(
                        fields=["error_type", "-created_at"], name="metacastor__error_t_fba714_idx"
                    ),
                ],
            },
        ),
    ]
