# Generated by Django 5.2.11 on 2026-05-04 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metacastor", "0002_failurerecord"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SkillExample",
        ),
    ]
