# Generated by Django 5.2.11 on 2026-09-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metacastor", "0003_delete_skillexample"),
    ]

    operations = [
        migrations.AlterField(
            model_name="failurerecord",
            name="failure_phase",
            field=models.CharField(
                choices=[
                    ("GENERATE", "Generate"),
                    ("VALIDATION", "Validation"),
                    ("EXECUTION", "Execution"),
                    ("SANDBOX", "Sandbox"),
                ],
                max_length=20,
                verbose_name="Phase",
            ),
        ),
        migrations.AlterField(
            model_name="failurerecord",
            name="tier",
            field=models.IntegerField(
                blank=True,
                help_text="V2 RSAA tier at failure time. Null on V3 failures.",
                null=True,
            ),
        ),
    ]
