# Generated by Django 5.2.11 on 2026-04-21 21:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("environments", "0004_permission_consolidation"),
        ("ifc_processor", "0010_add_data_issue_dedup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. 'Uniclass 2015', 'OmniClass', 'MasterFormat'",
                        max_length=128,
                        verbose_name="Name",
                    ),
                ),
                (
                    "edition",
                    models.CharField(
                        blank=True,
                        help_text="Edition / version marker (optional)",
                        max_length=32,
                        verbose_name="Edition",
                    ),
                ),
                (
                    "source",
                    models.URLField(
                        blank=True,
                        help_text="Publisher URL for the taxonomy (optional)",
                        verbose_name="Source URL",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifications",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classification System",
                "verbose_name_plural": "Classification Systems",
                "ordering": ["name", "edition"],
            },
        ),
        migrations.CreateModel(
            name="ClassificationReference",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="The code as it appears in the taxonomy",
                        max_length=64,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable label for the code",
                        max_length=255,
                        verbose_name="Label",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="facilities.classification",
                        verbose_name="Classification System",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classification Reference",
                "verbose_name_plural": "Classification References",
                "ordering": ["classification__name", "code"],
            },
        ),
        migrations.CreateModel(
            name="FacilityAsset",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_tag",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Human-readable code (e.g. AHU-04). Unique per project when set.",
                        max_length=64,
                        verbose_name="Asset Tag",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=255, verbose_name="Manufacturer"),
                ),
                (
                    "model_number",
                    models.CharField(blank=True, max_length=128, verbose_name="Model Number"),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, verbose_name="Serial Number"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=128, verbose_name="Barcode / QR"),
                ),
                (
                    "commissioning_date",
                    models.DateField(blank=True, null=True, verbose_name="Commissioning Date"),
                ),
                (
                    "expected_service_life_years",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Expected Service Life (years)"
                    ),
                ),
                (
                    "decommissioned_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When set, the asset is treated as retired from the register.",
                        null=True,
                        verbose_name="Decommissioned At",
                    ),
                ),
                (
                    "condition_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="0–100 (higher is better). Traffic-light thresholds: ≥70 green, 40–69 amber, <40 red.",
                        null=True,
                        verbose_name="Condition Score",
                    ),
                ),
                (
                    "warranty_start",
                    models.DateField(blank=True, null=True, verbose_name="Warranty Start"),
                ),
                (
                    "warranty_end",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="Warranty End"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "classifications",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assets",
                        to="facilities.classificationreference",
                        verbose_name="Classifications",
                    ),
                ),
                (
                    "ifc_entity",
                    models.ForeignKey(
                        help_text="The physical IFC entity this asset record overlays",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_assets",
                        to="ifc_processor.ifcentity",
                        verbose_name="IFC Entity",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_assets",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "responsible_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_assets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsible Party",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility Asset",
                "verbose_name_plural": "Facility Assets",
                "ordering": ["asset_tag", "ifc_entity__name"],
            },
        ),
        migrations.CreateModel(
            name="AssetInventory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Original Value",
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Current Value",
                    ),
                ),
                (
                    "total_replacement_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Total Replacement Cost",
                    ),
                ),
                (
                    "depreciated_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Depreciated Value",
                    ),
                ),
                (
                    "acquisition_date",
                    models.DateField(blank=True, null=True, verbose_name="Acquisition Date"),
                ),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="facilities.facilityasset",
                        verbose_name="Facility Asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Inventory",
                "verbose_name_plural": "Asset Inventories",
            },
        ),
        migrations.AddIndex(
            model_name="classification",
            index=models.Index(fields=["project", "name"], name="facilities__project_cd9559_idx"),
        ),
        migrations.AddConstraint(
            model_name="classification",
            constraint=models.UniqueConstraint(
                fields=("project", "name", "edition"), name="uniq_classification_per_project"
            ),
        ),
        migrations.AddIndex(
            model_name="classificationreference",
            index=models.Index(
                fields=["classification", "code"], name="facilities__classif_053c91_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="classificationreference",
            constraint=models.UniqueConstraint(
                fields=("classification", "code"), name="uniq_classification_reference_code"
            ),
        ),
        migrations.AddIndex(
            model_name="facilityasset",
            index=models.Index(
                fields=["project", "asset_tag"], name="facilities__project_a4e27e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facilityasset",
            index=models.Index(
                fields=["project", "condition_score"], name="facilities__project_194af5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facilityasset",
            index=models.Index(
                fields=["project", "warranty_end"], name="facilities__project_e1a017_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facilityasset",
            index=models.Index(
                fields=["project", "decommissioned_at"], name="facilities__project_61f9be_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="facilityasset",
            constraint=models.UniqueConstraint(
                fields=("project", "ifc_entity"), name="uniq_facility_asset_per_entity"
            ),
        ),
        migrations.AddConstraint(
            model_name="facilityasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("asset_tag__gt", "")),
                fields=("project", "asset_tag"),
                name="uniq_facility_asset_tag_per_project",
            ),
        ),
    ]
