# Generated by Django 5.2.11 on 2026-04-22 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0004_permission_consolidation"),
        ("facilities", "0001_initial"),
        ("ifc_processor", "0010_add_data_issue_dedup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facilityasset",
            options={
                "ordering": ["asset_tag", "name", "ifc_entity__name"],
                "verbose_name": "Facility Asset",
                "verbose_name_plural": "Facility Assets",
            },
        ),
        migrations.RemoveConstraint(
            model_name="facilityasset",
            name="uniq_facility_asset_per_entity",
        ),
        migrations.AddField(
            model_name="facilityasset",
            name="ifc_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="IFC type label (e.g. IfcUnitaryEquipment, IfcFurniture). Required for orphan assets; left blank when linked to an IFC entity (read from the entity).",
                max_length=100,
                verbose_name="IFC Type",
            ),
        ),
        migrations.AddField(
            model_name="facilityasset",
            name="location_text",
            field=models.CharField(
                blank=True,
                help_text="Free-text location for orphans with no spatial anchor (vehicles, mobile tools).",
                max_length=255,
                verbose_name="Location (free text)",
            ),
        ),
        migrations.AddField(
            model_name="facilityasset",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Display name. Required for orphan assets; left blank when linked to an IFC entity.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="facilityasset",
            name="spatial_container",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional room/floor/building anchor for an orphan asset. Ignored when the asset is linked to an IFC entity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orphan_assets",
                to="ifc_processor.ifcspatialelement",
                verbose_name="Spatial Container",
            ),
        ),
        migrations.AlterField(
            model_name="facilityasset",
            name="ifc_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="The physical IFC entity this asset record overlays. Leave blank for orphan assets (items not present in the IFC model).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facility_assets",
                to="ifc_processor.ifcentity",
                verbose_name="IFC Entity",
            ),
        ),
        migrations.AddConstraint(
            model_name="facilityasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ifc_entity__isnull", False)),
                fields=("project", "ifc_entity"),
                name="uniq_facility_asset_per_entity",
            ),
        ),
        migrations.AddConstraint(
            model_name="facilityasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ifc_entity__isnull", False),
                    models.Q(
                        models.Q(("name", ""), _negated=True),
                        models.Q(("ifc_type", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="facility_asset_linked_or_orphan_complete",
            ),
        ),
    ]
