# Generated by Django 5.2.11 on 2026-04-22 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0004_permission_consolidation"),
        ("facilities", "0002_alter_facilityasset_options_and_more"),
        ("ifc_processor", "0010_add_data_issue_dedup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="facilityasset",
            name="facility_asset_linked_or_orphan_complete",
        ),
        migrations.AlterField(
            model_name="facilityasset",
            name="ifc_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Optional grouping label (e.g. 'Fire extinguisher', 'IfcUnitaryEquipment', 'Service vehicle'). For linked assets the entity's IFC type is used; for orphans it's free text — leave blank if you don't need filtering by type.",
                max_length=100,
                verbose_name="Type / category",
            ),
        ),
        migrations.AddConstraint(
            model_name="facilityasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ifc_entity__isnull", False),
                    models.Q(("name", ""), _negated=True),
                    _connector="OR",
                ),
                name="facility_asset_linked_or_orphan_complete",
            ),
        ),
    ]
