# Generated by Django 5.2.11 on 2026-04-22 19:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0004_permission_consolidation"),
        (
            "facilities",
            "0003_remove_facilityasset_facility_asset_linked_or_orphan_complete_and_more",
        ),
        ("ifc_processor", "0010_add_data_issue_dedup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilityasset",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Display name. Required for orphan assets. For linked assets, an optional override: when set, it takes precedence over the IFC entity's Name and round-trips to IfcRoot.Name on export.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.CreateModel(
            name="ExportProfile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="default", max_length=64, verbose_name="Name")),
                (
                    "is_default",
                    models.BooleanField(
                        default=True,
                        help_text="The profile used when Export IFC is triggered without an explicit choice.",
                        verbose_name="Is Default",
                    ),
                ),
                (
                    "enabled_operations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Subset of SET_PROPERTY / ADD_PSET / SET_CLASSIFICATION / SET_ATTRIBUTE.",
                        verbose_name="Enabled Operations",
                    ),
                ),
                (
                    "enabled_pset_allowlist",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Psets that may be written or merged by the export. Empty list = no allowlist (all).",
                        verbose_name="Enabled Pset Allowlist",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fm_export_profiles",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Profile",
                "verbose_name_plural": "Export Profiles",
                "ordering": ["project", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="planning",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the apply phase begins.",
                        null=True,
                        verbose_name="Started At",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Completed At"),
                ),
                ("delta_count", models.PositiveIntegerField(default=0, verbose_name="Delta Count")),
                (
                    "entity_count",
                    models.PositiveIntegerField(default=0, verbose_name="Entity Count"),
                ),
                (
                    "conflict_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Deltas superseded by a later delta on the same target.",
                        verbose_name="Conflict Count",
                    ),
                ),
                (
                    "commit_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Git commit produced by the export (populated on success).",
                        max_length=40,
                        verbose_name="Commit Hash",
                    ),
                ),
                ("error_reason", models.TextField(blank=True, verbose_name="Error Reason")),
                (
                    "ifc_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fm_export_jobs",
                        to="ifc_processor.ifcfile",
                        verbose_name="IFC File",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_fm_export_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Initiated By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fm_export_jobs",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "export_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="facilities.exportprofile",
                        verbose_name="Export Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Job",
                "verbose_name_plural": "Export Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FMDelta",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_guid",
                    models.CharField(
                        db_index=True,
                        help_text="IFC GlobalId of the target entity. Denormalized from the asset at insert; immutable.",
                        max_length=64,
                        verbose_name="Entity GlobalId",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("SET_PROPERTY", "Set Property"),
                            ("ADD_PSET", "Add/Merge Property Set"),
                            ("SET_CLASSIFICATION", "Set Classification"),
                            ("SET_ATTRIBUTE", "Set Attribute"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Operation",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Operation-specific payload. Shapes: SET_PROPERTY / ADD_PSET → {pset, property, value, old_value}; SET_CLASSIFICATION → {action, system, code, name}; SET_ATTRIBUTE → {attribute, value, old_value}.",
                        verbose_name="Payload",
                    ),
                ),
                (
                    "applied_to_ifc_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Set when the export that carried this delta commits successfully.",
                        null=True,
                        verbose_name="Applied To IFC At",
                    ),
                ),
                (
                    "superseded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when an export's plan phase collapses this delta under a later delta on the same (entity_guid, operation, target) tuple. Kept for audit; not replayed.",
                        null=True,
                        verbose_name="Superseded At",
                    ),
                ),
                (
                    "ifc_commit_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Mirror of export_job.commit_hash, denormalized for fast audit queries.",
                        max_length=40,
                        verbose_name="IFC Commit Hash",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="The asset whose mutation produced this delta. May be null if the asset has been deleted after the delta was queued.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fm_deltas",
                        to="facilities.facilityasset",
                        verbose_name="Facility Asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_fm_deltas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "export_job",
                    models.ForeignKey(
                        blank=True,
                        help_text="The export run that applied or superseded this delta.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deltas",
                        to="facilities.exportjob",
                        verbose_name="Export Job",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fm_deltas",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "FM Delta",
                "verbose_name_plural": "FM Deltas",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="exportprofile",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="uniq_export_profile_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="exportprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("project",),
                name="uniq_default_export_profile_per_project",
            ),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(
                fields=["project", "-created_at"], name="facilities__project_576061_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(fields=["project", "status"], name="facilities__project_80638d_idx"),
        ),
        migrations.AddIndex(
            model_name="fmdelta",
            index=models.Index(
                condition=models.Q(
                    ("applied_to_ifc_at__isnull", True), ("superseded_at__isnull", True)
                ),
                fields=["project"],
                name="fm_delta_pending_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fmdelta",
            index=models.Index(
                fields=["project", "entity_guid"], name="facilities__project_23a8cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fmdelta",
            index=models.Index(
                fields=["project", "-created_at"], name="facilities__project_7a5dce_idx"
            ),
        ),
    ]
