# Generated by Django 5.2.11 on 2026-04-23 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0004_exports_m2"),
        ("ifc_processor", "0010_add_data_issue_dedup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportjob",
            name="ifc_file",
            field=models.ForeignKey(
                blank=True,
                help_text="The IFC file targeted by this export. Goes NULL if the file or its parent project is later deleted; the job is kept for audit (commit_hash and counts remain).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fm_export_jobs",
                to="ifc_processor.ifcfile",
                verbose_name="IFC File",
            ),
        ),
    ]
