# Generated by Django 5.2.11 on 2026-04-24 00:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0004_permission_consolidation"),
        ("facilities", "0005_alter_exportjob_ifc_file"),
        ("ifc_processor", "0010_add_data_issue_dedup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionRequest",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short summary, e.g. 'Meeting room 3-B is cold'.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        db_index=True,
                        default="medium",
                        max_length=8,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("triaged", "Triaged"),
                            ("escalated", "Escalated"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "triage_note",
                    models.TextField(
                        blank=True,
                        help_text="FM-side notes from triage / dismissal.",
                        verbose_name="Triage Note",
                    ),
                ),
                (
                    "affected_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_requests",
                        to="facilities.facilityasset",
                        verbose_name="Affected Asset",
                    ),
                ),
                (
                    "affected_spatial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_requests",
                        to="ifc_processor.ifcspatialelement",
                        verbose_name="Affected Space",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_requests",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_action_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Submitted By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action Request",
                "verbose_name_plural": "Action Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wo_number",
                    models.CharField(
                        help_text="Human-readable code, auto-generated as WO-NNNNN per project.",
                        max_length=32,
                        verbose_name="Work Order Number",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 — Critical"),
                            (2, "2 — High"),
                            (3, "3 — Normal"),
                            (4, "4 — Low"),
                            (5, "5 — Backlog"),
                        ],
                        db_index=True,
                        default=3,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("corrective", "Corrective"),
                            ("preventive", "Preventive"),
                            ("inspection", "Inspection"),
                            ("installation", "Installation"),
                            ("decommission", "Decommission"),
                        ],
                        db_index=True,
                        default="corrective",
                        max_length=32,
                        verbose_name="Category",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Draft"),
                            (10, "Submitted"),
                            (20, "Triaged"),
                            (30, "Assigned"),
                            (40, "Scheduled"),
                            (50, "In progress"),
                            (60, "Completed"),
                            (70, "Verified"),
                            (80, "Closed"),
                            (90, "Cancelled"),
                        ],
                        db_index=True,
                        default=0,
                        verbose_name="Status",
                    ),
                ),
                (
                    "assignee_vendor",
                    models.CharField(
                        blank=True,
                        help_text="Free-text vendor name in V1 — becomes a Vendor FK in a later milestone.",
                        max_length=255,
                        verbose_name="Assignee (Vendor)",
                    ),
                ),
                (
                    "scheduled_start",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Scheduled Start"
                    ),
                ),
                (
                    "scheduled_end",
                    models.DateTimeField(blank=True, null=True, verbose_name="Scheduled End"),
                ),
                (
                    "actual_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Stamped when the WO transitions to In Progress.",
                        null=True,
                        verbose_name="Actual Start",
                    ),
                ),
                (
                    "actual_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="Stamped when the WO transitions to Completed.",
                        null=True,
                        verbose_name="Actual End",
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Due At"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Verified At"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Closed At"),
                ),
                (
                    "source_intent_batch_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="When set, groups WOs that were created together by an Intent-to-WO batch. Mirrors the FMIntentProposal primary key (M3.E).",
                        null=True,
                        verbose_name="Source Intent Batch",
                    ),
                ),
                (
                    "affected_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="facilities.facilityasset",
                        verbose_name="Affected Asset",
                    ),
                ),
                (
                    "affected_spatial",
                    models.ForeignKey(
                        blank=True,
                        help_text="Space-level anchor when no specific asset applies.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="ifc_processor.ifcspatialelement",
                        verbose_name="Affected Space",
                    ),
                ),
                (
                    "assignee_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_work_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assignee (User)",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_orders",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_work_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
                (
                    "source_action_request",
                    models.ForeignKey(
                        blank=True,
                        help_text="The AR this WO was escalated from (when applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="facilities.actionrequest",
                        verbose_name="Source Action Request",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_work_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Order",
                "verbose_name_plural": "Work Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Permit",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permit_number",
                    models.CharField(
                        help_text="Issuing authority's reference (free text). Unique per project.",
                        max_length=64,
                        verbose_name="Permit Number",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("hot_work", "Hot work"),
                            ("confined_space", "Confined space"),
                            ("electrical", "Electrical isolation"),
                            ("working_at_height", "Working at height"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=32,
                        verbose_name="Kind",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "issued_to",
                    models.CharField(
                        blank=True,
                        help_text="The contractor / responsible party named on the permit.",
                        max_length=255,
                        verbose_name="Issued To",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(blank=True, null=True, verbose_name="Valid From"),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Valid Until"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permits",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "work_orders",
                    models.ManyToManyField(
                        blank=True,
                        related_name="permits",
                        to="facilities.workorder",
                        verbose_name="Work Orders",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permit",
                "verbose_name_plural": "Permits",
                "ordering": ["-valid_until", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderAttachment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="fm/work_orders/%Y/%m/", verbose_name="File")),
                ("caption", models.CharField(blank=True, max_length=255, verbose_name="Caption")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("document", "Document"),
                            ("signoff", "Sign-off"),
                        ],
                        default="photo",
                        max_length=16,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_work_order_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="facilities.workorder",
                        verbose_name="Work Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Order Attachment",
                "verbose_name_plural": "Work Order Attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderStatusEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Draft"),
                            (10, "Submitted"),
                            (20, "Triaged"),
                            (30, "Assigned"),
                            (40, "Scheduled"),
                            (50, "In progress"),
                            (60, "Completed"),
                            (70, "Verified"),
                            (80, "Closed"),
                            (90, "Cancelled"),
                        ],
                        help_text="Null on the initial creation event.",
                        null=True,
                        verbose_name="From Status",
                    ),
                ),
                (
                    "to_status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Draft"),
                            (10, "Submitted"),
                            (20, "Triaged"),
                            (30, "Assigned"),
                            (40, "Scheduled"),
                            (50, "In progress"),
                            (60, "Completed"),
                            (70, "Verified"),
                            (80, "Closed"),
                            (90, "Cancelled"),
                        ],
                        verbose_name="To Status",
                    ),
                ),
                (
                    "actor_role",
                    models.CharField(
                        blank=True,
                        help_text="ProjectRole.role snapshot at transition time (e.g. 'facilitiesmanager').",
                        max_length=32,
                        verbose_name="Actor Role",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_order_status_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_events",
                        to="facilities.workorder",
                        verbose_name="Work Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Order Status Event",
                "verbose_name_plural": "Work Order Status Events",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="actionrequest",
            index=models.Index(fields=["project", "status"], name="facilities__project_d23e4f_idx"),
        ),
        migrations.AddIndex(
            model_name="actionrequest",
            index=models.Index(
                fields=["project", "-created_at"], name="facilities__project_6e960e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionrequest",
            index=models.Index(
                fields=["project", "severity"], name="facilities__project_8a3d25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["project", "status"], name="facilities__project_1c1c86_idx"),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["project", "due_at"], name="facilities__project_6d0e7d_idx"),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["project", "scheduled_start"], name="facilities__project_d843bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["project", "assignee_user", "status"], name="facilities__project_6934c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["project", "-created_at"], name="facilities__project_bcd266_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.UniqueConstraint(
                fields=("project", "wo_number"), name="uniq_work_order_number_per_project"
            ),
        ),
        migrations.AddIndex(
            model_name="permit",
            index=models.Index(fields=["project", "status"], name="facilities__project_53430a_idx"),
        ),
        migrations.AddIndex(
            model_name="permit",
            index=models.Index(
                fields=["project", "valid_until"], name="facilities__project_b5e6f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permit",
            index=models.Index(fields=["project", "kind"], name="facilities__project_c4f168_idx"),
        ),
        migrations.AddConstraint(
            model_name="permit",
            constraint=models.UniqueConstraint(
                fields=("project", "permit_number"), name="uniq_permit_number_per_project"
            ),
        ),
        migrations.AddIndex(
            model_name="workorderattachment",
            index=models.Index(
                fields=["work_order", "-created_at"], name="facilities__work_or_a5cf6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorderstatusevent",
            index=models.Index(
                fields=["work_order", "created_at"], name="facilities__work_or_df7727_idx"
            ),
        ),
    ]
