# Generated by Django 5.2.11 on 2026-04-24 01:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0004_permission_consolidation"),
        ("facilities", "0006_work_orders"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FMIntentProposal",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message", models.TextField(verbose_name="User Message")),
                (
                    "plan_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parsed LLM output: {explanation, confidence, work_orders: [...]}.",
                        verbose_name="Plan JSON",
                    ),
                ),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="0–100. The planner's self-rating.",
                        null=True,
                        verbose_name="Confidence",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Applied At"),
                ),
                (
                    "created_wo_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="UUID strings of the WorkOrder rows materialized by confirm().",
                        verbose_name="Created WO IDs",
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Failure reason — LLM timeout, parse failure, or apply error.",
                        verbose_name="Error",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fm_intent_proposals",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fm_intent_proposals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "FM Intent Proposal",
                "verbose_name_plural": "FM Intent Proposals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-created_at"], name="facilities__project_79685b_idx"
                    ),
                    models.Index(
                        fields=["project", "status"], name="facilities__project_2c5db3_idx"
                    ),
                ],
            },
        ),
    ]
