# Generated by Django 5.2.11 on 2026-04-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0007_fm_intent_proposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionrequest",
            name="draft_confidence",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="0–100 self-reported confidence from the intake LLM (M4).",
                null=True,
                verbose_name="LLM Confidence",
            ),
        ),
        migrations.AddField(
            model_name="actionrequest",
            name="draft_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Parsed LLM output used to draft this request (M4).",
                verbose_name="LLM Draft Payload",
            ),
        ),
        migrations.AddField(
            model_name="actionrequest",
            name="user_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Raw text the occupant typed in the portal (M4).",
                verbose_name="Occupant Text",
            ),
        ),
    ]
