# Generated by Django 6.0.2 on 2026-07-11 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_name'),
        ('facilities', '0015_workorder_category_expansion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='assets',
            field=models.ManyToManyField(blank=True, help_text='IFC-anchored (or orphan) assets this permit covers. Linking a permit here surfaces it on the asset detail page and vice versa.', related_name='permits', to='facilities.facilityasset', verbose_name='Assets'),
        ),
        migrations.CreateModel(
            name='AssetDocumentFolder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="User-chosen label, e.g. 'Manuals', 'Certificates', 'Service reports'.", max_length=120, verbose_name='Folder Name')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='facilities.facilityasset', verbose_name='Asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('documents', models.ManyToManyField(blank=True, help_text='Project documents linked into this folder.', related_name='asset_folders', to='documents.document', verbose_name='Documents')),
            ],
            options={
                'verbose_name': 'Asset Document Folder',
                'verbose_name_plural': 'Asset Document Folders',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('asset', 'name'), name='uniq_asset_document_folder_name')],
            },
        ),
    ]
