# Generated by Django 6.0.2 on 2026-05-14 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0005_projectrole_assigned_space'),
        ('ifc_processor', '0011_ifcentity_ifc_description_ifcentity_tag'),
        ('islam_scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('excel', 'Excel (.xlsx)'), ('csv', 'CSV (.csv)'), ('xer', 'Primavera P6 (.xer)'), ('msp', 'MS Project (.xml)'), ('manual', 'Manual entry')], default='manual', max_length=20, verbose_name='Source'),
        ),
        migrations.CreateModel(
            name='LinkFeedback',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=None, help_text='None=pending review, True=accepted, False=rejected', null=True, verbose_name='Accepted')),
                ('method', models.CharField(choices=[('embedding', 'Embedding similarity'), ('parameter', 'Parameter match'), ('manual', 'Manual selection')], default='embedding', max_length=20, verbose_name='Linking method')),
                ('confidence_at_time', models.FloatField(blank=True, null=True, verbose_name='Confidence score at suggestion time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_to', models.ForeignKey(blank=True, help_text='Populated when the user selects a different entity than the suggestion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_feedback', to='ifc_processor.ifcentity', verbose_name='Corrected entity')),
                ('ifc_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_feedback', to='ifc_processor.ifcentity', verbose_name='Suggested IFC Entity')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_feedback', to='islam_scheduling.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Link Feedback',
                'verbose_name_plural': 'Link Feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'accepted'], name='islam_sched_task_id_bec3ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='MappingProfile',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Profile Name')),
                ('column_mapping', models.JSONField(help_text='Maps canonical fields (name, start_date, …) to actual column header strings', verbose_name='Column Mapping')),
                ('ifc_parameter_name', models.CharField(default='ActivityCode', help_text='IFC property that holds the activity code for parameter-based linking', max_length=255, verbose_name='IFC Parameter Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_profiles', to='environments.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Mapping Profile',
                'verbose_name_plural': 'Mapping Profiles',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
