# Generated by Django 6.0.2 on 2026-05-14 15:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("islam_scheduling", "0002_alter_task_source_linkfeedback_mappingprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskEntityBinding",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_global_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="IFC Entity GlobalId"
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0,
                        help_text="0.0–1.0 score assigned by the linking algorithm",
                        verbose_name="Confidence",
                    ),
                ),
                (
                    "link_method",
                    models.CharField(
                        choices=[
                            ("exact", "Exact match"),
                            ("normalized", "Normalized match"),
                            ("heuristic", "Type heuristic"),
                            ("embedding", "Embedding similarity"),
                        ],
                        default="exact",
                        max_length=20,
                        verbose_name="Link Method",
                    ),
                ),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False,
                        help_text="True when confidence is below the auto-accept threshold (0.95)",
                        verbose_name="Needs Review",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_bindings",
                        to="islam_scheduling.task",
                        verbose_name="Task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Entity Binding",
                "verbose_name_plural": "Task Entity Bindings",
                "ordering": ["-confidence", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "needs_review"], name="islam_sched_task_id_f70ae1_idx"
                    ),
                    models.Index(
                        fields=["entity_global_id"], name="islam_sched_entity__bdcf30_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "entity_global_id"), name="unique_task_entity_binding"
                    )
                ],
            },
        ),
    ]
