# Generated by Django 6.0.2 on 2026-05-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islam_scheduling', '0003_task_entity_binding'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_end',
            field=models.DateField(blank=True, null=True, verbose_name='Actual End'),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_start',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Start'),
        ),
    ]
