# Generated by Django 6.0.2 on 2026-05-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("islam_scheduling", "0004_task_actual_end_task_actual_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Task cost from schedule. Overrides IFC element cost when set.",
                max_digits=14,
                null=True,
                verbose_name="Cost",
            ),
        ),
    ]
