# Generated by Django 6.0.2 on 2026-05-15 12:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0005_projectrole_assigned_space"),
        ("islam_scheduling", "0006_task_activity_type_task_is_non_physical_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="weight",
            field=models.FloatField(
                default=1.0,
                help_text="Used by the Custom Weight progress mode. Defaults to 1.0 for equal weighting.",
                verbose_name="Custom Weight",
            ),
        ),
        migrations.CreateModel(
            name="IslamProgressMode",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("count", "By Task Count"),
                            ("cost", "By Cost"),
                            ("duration", "By Duration"),
                            ("weight", "Custom Weight"),
                        ],
                        default="count",
                        max_length=20,
                        verbose_name="Progress Mode",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="islam_progress_mode",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progress Mode",
                "verbose_name_plural": "Progress Modes",
            },
        ),
    ]
