# Generated by Django 6.0.2 on 2026-05-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("islam_scheduling", "0007_task_weight_islamprogressmode"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("substructure", "Substructure"),
                    ("structure", "Structure"),
                    ("envelope", "Envelope"),
                    ("mep", "MEP"),
                    ("finishes", "Finishes"),
                    ("external", "External Works"),
                ],
                db_index=True,
                help_text="Construction stage auto-detected from task name keywords. Blank = unassigned.",
                max_length=20,
                verbose_name="Stage",
            ),
        ),
    ]
