# Generated by Django 6.0.2 on 2026-05-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islam_scheduling', '0008_task_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sub_stage',
            field=models.CharField(blank=True, choices=[('excavation', 'Excavation'), ('blinding', 'Blinding'), ('waterproofing', 'Waterproofing'), ('backfill', 'Backfill'), ('piling', 'Piling'), ('formwork', 'Formwork'), ('rebar', 'Rebar'), ('concrete', 'Concrete'), ('stripping', 'Stripping'), ('steel_erection', 'Steel Erection'), ('precast', 'Precast'), ('blockwork', 'Blockwork'), ('cladding', 'Cladding'), ('glazing', 'Glazing'), ('roofing', 'Roofing'), ('insulation', 'Insulation'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC'), ('firefighting', 'Firefighting'), ('lv_systems', 'LV Systems'), ('plaster', 'Plaster'), ('painting', 'Painting'), ('flooring', 'Flooring'), ('tiling', 'Tiling'), ('ceiling', 'Ceiling'), ('joinery', 'Joinery'), ('landscaping', 'Landscaping'), ('paving', 'Paving'), ('fencing', 'Fencing'), ('hardscape', 'Hardscape')], db_index=True, help_text='Trade-level detail within the parent stage. Auto-detected; also sets parent stage.', max_length=30, verbose_name='Sub-Stage'),
        ),
    ]
