# Generated by Django 6.0.2 on 2026-05-15 19:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("islam_scheduling", "0009_task_sub_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="early_finish",
            field=models.DateField(blank=True, null=True, verbose_name="Early Finish"),
        ),
        migrations.AddField(
            model_name="task",
            name="early_start",
            field=models.DateField(blank=True, null=True, verbose_name="Early Start"),
        ),
        migrations.AddField(
            model_name="task",
            name="is_critical",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True when total float == 0 (on the critical path).",
                verbose_name="Critical",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="late_finish",
            field=models.DateField(blank=True, null=True, verbose_name="Late Finish"),
        ),
        migrations.AddField(
            model_name="task",
            name="late_start",
            field=models.DateField(blank=True, null=True, verbose_name="Late Start"),
        ),
        migrations.AddField(
            model_name="task",
            name="total_float",
            field=models.IntegerField(blank=True, null=True, verbose_name="Total Float (days)"),
        ),
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dep_type",
                    models.CharField(
                        choices=[
                            ("FS", "Finish-to-Start"),
                            ("SS", "Start-to-Start"),
                            ("FF", "Finish-to-Finish"),
                            ("SF", "Start-to-Finish"),
                        ],
                        default="FS",
                        max_length=2,
                        verbose_name="Dependency Type",
                    ),
                ),
                (
                    "lag_days",
                    models.IntegerField(
                        default=0,
                        help_text="Positive = lag, negative = lead.",
                        verbose_name="Lag (days)",
                    ),
                ),
                (
                    "predecessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="successors",
                        to="islam_scheduling.task",
                        verbose_name="Predecessor",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predecessors",
                        to="islam_scheduling.task",
                        verbose_name="Successor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Dependency",
                "verbose_name_plural": "Task Dependencies",
                "ordering": ["predecessor__start_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("predecessor", "successor", "dep_type"),
                        name="unique_task_dependency",
                    )
                ],
            },
        ),
    ]
