# Generated by Django 6.0.2 on 2026-05-18 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islam_scheduling', '0011_schedulesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='schedule_source',
            field=models.ForeignKey(blank=True, help_text='Import event that last created or updated this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='islam_scheduling.schedulesource', verbose_name='Schedule Source'),
        ),
    ]
