# Generated by Django 6.0.2 on 2026-05-22 06:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0005_projectrole_assigned_space"),
        ("islam_scheduling", "0013_islamtaskembedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColumnMappingLookup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename_pattern",
                    models.CharField(
                        blank=True,
                        help_text="Base filename (no extension) of the file that produced this mapping",
                        max_length=255,
                        verbose_name="Filename Pattern",
                    ),
                ),
                (
                    "column_fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-1 of sorted, lowercased header names — used as the lookup key",
                        max_length=64,
                        verbose_name="Column Fingerprint",
                    ),
                ),
                (
                    "mapping",
                    models.JSONField(
                        help_text="Maps canonical Task fields to original header strings, e.g. {name: 'Task Name'}",
                        verbose_name="Column Mapping",
                    ),
                ),
                ("hit_count", models.IntegerField(default=1, verbose_name="Hit Count")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_mapping_lookups",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Column Mapping Lookup",
                "verbose_name_plural": "Column Mapping Lookups",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "column_fingerprint"],
                        name="islam_sched_project_b9efd3_idx",
                    )
                ],
                "unique_together": {("project", "column_fingerprint")},
            },
        ),
    ]
