# Generated by Django 6.0.2 on 2026-05-29 13:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0005_projectrole_assigned_space"),
        ("islam_scheduling", "0016_add_manual_link_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulesource",
            name="source_format",
            field=models.CharField(
                choices=[
                    ("excel", "Excel (.xlsx)"),
                    ("csv", "CSV (.csv)"),
                    ("xer", "Primavera P6 (.xer)"),
                    ("msp", "MS Project (.xml)"),
                    ("p6xml", "Primavera P6 XML (.xml)"),
                    ("manual", "Manual entry"),
                ],
                default="excel",
                max_length=20,
                verbose_name="Format",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="source",
            field=models.CharField(
                choices=[
                    ("excel", "Excel (.xlsx)"),
                    ("csv", "CSV (.csv)"),
                    ("xer", "Primavera P6 (.xer)"),
                    ("msp", "MS Project (.xml)"),
                    ("p6xml", "Primavera P6 XML (.xml)"),
                    ("manual", "Manual entry"),
                ],
                default="manual",
                max_length=20,
                verbose_name="Source",
            ),
        ),
        migrations.CreateModel(
            name="P6ResourceAssignment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "p6_activity_object_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="P6 Activity ObjectId"
                    ),
                ),
                (
                    "p6_resource_object_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="P6 Resource ObjectId"
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        help_text="Material, Labor, or Equipment.",
                        max_length=50,
                        verbose_name="Resource Type",
                    ),
                ),
                (
                    "planned_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=16, verbose_name="Planned Cost"
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=16, verbose_name="Actual Cost"
                    ),
                ),
                (
                    "remaining_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=16, verbose_name="Remaining Cost"
                    ),
                ),
                (
                    "at_completion_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="At Completion Cost",
                    ),
                ),
                (
                    "planned_units",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=16, verbose_name="Planned Units"
                    ),
                ),
                (
                    "actual_units",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=16, verbose_name="Actual Units"
                    ),
                ),
                (
                    "is_pending",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="True until the user confirms the import; False once linked to a ScheduleSource.",
                        verbose_name="Pending",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p6_resource_assignments",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "schedule_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p6_resource_assignments",
                        to="islam_scheduling.schedulesource",
                        verbose_name="Schedule Source",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resolved after import by matching p6_activity_object_id → Task._p6_obj_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="p6_resource_assignments",
                        to="islam_scheduling.task",
                        verbose_name="Task",
                    ),
                ),
            ],
            options={
                "verbose_name": "P6 Resource Assignment",
                "verbose_name_plural": "P6 Resource Assignments",
                "indexes": [
                    models.Index(
                        fields=["project", "is_pending"], name="islam_sched_project_5d1af0_idx"
                    ),
                    models.Index(fields=["task"], name="islam_sched_task_id_9f4742_idx"),
                    models.Index(
                        fields=["p6_activity_object_id"], name="islam_sched_p6_acti_0b0401_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="P6WBSNode",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "p6_object_id",
                    models.CharField(db_index=True, max_length=50, verbose_name="P6 ObjectId"),
                ),
                (
                    "p6_parent_object_id",
                    models.CharField(blank=True, max_length=50, verbose_name="P6 Parent ObjectId"),
                ),
                ("code", models.CharField(blank=True, max_length=100, verbose_name="WBS Code")),
                ("name", models.CharField(max_length=500, verbose_name="WBS Name")),
                (
                    "original_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="Original Budget",
                    ),
                ),
                (
                    "sequence_number",
                    models.IntegerField(blank=True, null=True, verbose_name="Sequence Number"),
                ),
                (
                    "is_pending",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="True until the user confirms the import; False once linked to a ScheduleSource.",
                        verbose_name="Pending",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p6_wbs_nodes",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "schedule_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p6_wbs_nodes",
                        to="islam_scheduling.schedulesource",
                        verbose_name="Schedule Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "P6 WBS Node",
                "verbose_name_plural": "P6 WBS Nodes",
                "ordering": ["sequence_number", "code"],
                "indexes": [
                    models.Index(
                        fields=["project", "is_pending"], name="islam_sched_project_490cae_idx"
                    ),
                    models.Index(
                        fields=["project", "p6_object_id"], name="islam_sched_project_7723fb_idx"
                    ),
                ],
            },
        ),
    ]
