# Generated by Django 6.0.2 on 2026-05-29 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0005_projectrole_assigned_space'),
        ('islam_scheduling', '0017_p6_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='calendar_object_id',
            field=models.CharField(blank=True, help_text='P6 calendar assigned to this activity; used for working-day CPM.', max_length=50, verbose_name='P6 Calendar ObjectId'),
        ),
        migrations.AddField(
            model_name='task',
            name='constraint_date',
            field=models.DateField(blank=True, null=True, verbose_name='Constraint Date'),
        ),
        migrations.AddField(
            model_name='task',
            name='constraint_type',
            field=models.CharField(blank=True, help_text="P6 scheduling constraint: 'Start On or After', 'Mandatory Finish', etc.", max_length=50, verbose_name='Constraint Type'),
        ),
        migrations.CreateModel(
            name='P6Calendar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('p6_calendar_id', models.CharField(db_index=True, max_length=50, verbose_name='P6 Calendar ObjectId')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('hours_per_day', models.FloatField(default=8.0, verbose_name='Hours per Day')),
                ('working_days', models.JSONField(default=list, help_text='List of working day names, e.g. ["Sunday", "Monday", ...]', verbose_name='Working Day Names')),
                ('holidays', models.JSONField(default=list, help_text='ISO-date strings of non-working exception days.', verbose_name='Holiday Exceptions')),
                ('is_pending', models.BooleanField(db_index=True, default=True, verbose_name='Pending')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p6_calendars', to='environments.project', verbose_name='Project')),
                ('schedule_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p6_calendars', to='islam_scheduling.schedulesource', verbose_name='Schedule Source')),
            ],
            options={
                'verbose_name': 'P6 Calendar',
                'verbose_name_plural': 'P6 Calendars',
                'indexes': [models.Index(fields=['project', 'is_pending'], name='islam_sched_project_f68a20_idx'), models.Index(fields=['project', 'p6_calendar_id'], name='islam_sched_project_991a7e_idx')],
            },
        ),
    ]
