# Generated by Django 5.2.11 on 2026-02-03 23:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('documents', '0001_initial'),
        ('environments', '0001_initial'),
        ('ifc_processor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitCommit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commit_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('parent_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('message', models.TextField()),
                ('entities_modified', models.PositiveIntegerField(default=0)),
                ('entities_added', models.PositiveIntegerField(default=0)),
                ('entities_removed', models.PositiveIntegerField(default=0)),
                ('diff_data', models.JSONField(default=dict)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='git_commits', to=settings.AUTH_USER_MODEL)),
                ('ifc_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='ifc_processor.ifcfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModificationProposal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_text', models.TextField()),
                ('explanation', models.TextField()),
                ('changes', models.JSONField(default=list)),
                ('diff_preview', models.TextField()),
                ('affected_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_proposals', to=settings.AUTH_USER_MODEL)),
                ('git_commit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal', to='writeback.gitcommit')),
                ('ifc_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='ifc_processor.ifcfile')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='chat.message')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ifc_value', models.TextField()),
                ('document_value', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('document_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='documents.documentchunk')),
                ('ifc_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='ifc_processor.ifcentity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='environments.project')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
                'indexes': [models.Index(fields=['project', 'status', '-severity'], name='writeback_c_project_b6cb85_idx'), models.Index(fields=['project', 'status', '-created_at'], name='writeback_c_project_8393d4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='gitcommit',
            index=models.Index(fields=['ifc_file', '-created_at'], name='writeback_g_ifc_fil_e17c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='gitcommit',
            index=models.Index(fields=['author', '-created_at'], name='writeback_g_author__bb9b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='modificationproposal',
            index=models.Index(fields=['ifc_file', 'status'], name='writeback_m_ifc_fil_a836b8_idx'),
        ),
        migrations.AddIndex(
            model_name='modificationproposal',
            index=models.Index(fields=['created_by', '-created_at'], name='writeback_m_created_1ba0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='modificationproposal',
            index=models.Index(fields=['status', '-created_at'], name='writeback_m_status_51b599_idx'),
        ),
    ]
