# Generated by Django 5.2.11 on 2026-02-04 19:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_chatsession_options_alter_message_options_and_more"),
        ("documents", "0002_alter_document_options_alter_documentchunk_options_and_more"),
        ("environments", "0002_alter_project_options_and_more"),
        ("ifc_processor", "0002_alter_ifcentity_building_and_more"),
        ("writeback", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conflict",
            options={
                "ordering": ["-severity", "-created_at"],
                "verbose_name": "Conflict",
                "verbose_name_plural": "Conflicts",
            },
        ),
        migrations.AlterModelOptions(
            name="gitcommit",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Git Commit",
                "verbose_name_plural": "Git Commits",
            },
        ),
        migrations.AlterModelOptions(
            name="modificationproposal",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Modification Proposal",
                "verbose_name_plural": "Modification Proposals",
            },
        ),
        migrations.AlterField(
            model_name="conflict",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="conflict",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="conflict",
            name="document_chunk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conflicts",
                to="documents.documentchunk",
                verbose_name="Document Chunk",
            ),
        ),
        migrations.AlterField(
            model_name="conflict",
            name="document_value",
            field=models.TextField(
                help_text="Value found in the document", verbose_name="Document Value"
            ),
        ),
        migrations.AlterField(
            model_name="conflict",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="conflict",
            name="ifc_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conflicts",
                to="ifc_processor.ifcentity",
                verbose_name="IFC Entity",
            ),
        ),
        migrations.AlterField(
            model_name="conflict",
            name="ifc_value",
            field=models.TextField(
                help_text="Value found in the IFC model", verbose_name="IFC Value"
            ),
        ),
        migrations.AlterField(
            model_name="conflict",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conflicts",
                to="environments.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="conflict",
            name="resolution_note",
            field=models.TextField(blank=True, verbose_name="Resolution Note"),
        ),
        migrations.AlterField(
            model_name="conflict",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Resolved At"),
        ),
        migrations.AlterField(
            model_name="conflict",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_conflicts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Resolved By",
            ),
        ),
        migrations.AlterField(
            model_name="conflict",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                db_index=True,
                default="medium",
                max_length=20,
                verbose_name="Severity",
            ),
        ),
        migrations.AlterField(
            model_name="conflict",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("resolved", "Resolved"), ("ignored", "Ignored")],
                db_index=True,
                default="open",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="conflict",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="conflict",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="gitcommit",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="git_commits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="gitcommit",
            name="commit_hash",
            field=models.CharField(
                db_index=True, max_length=64, unique=True, verbose_name="Commit Hash"
            ),
        ),
        migrations.AlterField(
            model_name="gitcommit",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="gitcommit",
            name="diff_data",
            field=models.JSONField(
                default=dict,
                help_text="Detailed diff information as JSON",
                verbose_name="Diff Data",
            ),
        ),
        migrations.AlterField(
            model_name="gitcommit",
            name="entities_added",
            field=models.PositiveIntegerField(default=0, verbose_name="Entities Added"),
        ),
        migrations.AlterField(
            model_name="gitcommit",
            name="entities_modified",
            field=models.PositiveIntegerField(default=0, verbose_name="Entities Modified"),
        ),
        migrations.AlterField(
            model_name="gitcommit",
            name="entities_removed",
            field=models.PositiveIntegerField(default=0, verbose_name="Entities Removed"),
        ),
        migrations.AlterField(
            model_name="gitcommit",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="gitcommit",
            name="ifc_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commits",
                to="ifc_processor.ifcfile",
                verbose_name="IFC File",
            ),
        ),
        migrations.AlterField(
            model_name="gitcommit",
            name="message",
            field=models.TextField(verbose_name="Commit Message"),
        ),
        migrations.AlterField(
            model_name="gitcommit",
            name="parent_hash",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="Parent Hash"
            ),
        ),
        migrations.AlterField(
            model_name="gitcommit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="affected_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Affected Entities"),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="changes",
            field=models.JSONField(
                default=list,
                help_text="Structured list of entity modifications",
                verbose_name="Changes",
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_proposals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="diff_preview",
            field=models.TextField(
                help_text="Human-readable preview of changes", verbose_name="Diff Preview"
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="explanation",
            field=models.TextField(
                help_text="AI-generated explanation of proposed changes", verbose_name="Explanation"
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="git_commit",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposal",
                to="writeback.gitcommit",
                verbose_name="Git Commit",
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="ifc_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to="ifc_processor.ifcfile",
                verbose_name="IFC File",
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="message",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposal",
                to="chat.message",
                verbose_name="Source Message",
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="Rejection Reason"),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="request_text",
            field=models.TextField(
                help_text="Original natural language modification request", verbose_name="Request"
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Reviewed At"),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_proposals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewed By",
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("applied", "Applied"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
