# Generated by Django 5.2.11 on 2026-03-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("writeback", "0004_modificationproposal_verification_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conflict",
            name="suggested_fix",
            field=models.TextField(
                blank=True,
                help_text="LLM-generated modify prompt to resolve this conflict",
                verbose_name="Suggested Fix",
            ),
        ),
        migrations.AlterField(
            model_name="conflict",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("resolved", "Resolved"),
                    ("ignored", "Ignored"),
                    ("dismissed", "Dismissed"),
                ],
                db_index=True,
                default="open",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
