# Generated by Django 5.2.11 on 2026-03-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("writeback", "0006_conflict_confidence_conflict_content_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modificationproposal",
            name="linked_conflict_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of Conflict UUIDs (as strings) linked when this proposal was created via 'Fix in Modify'",
                verbose_name="Linked Conflict IDs",
            ),
        ),
    ]
