# Generated by Django 5.2.11 on 2026-04-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("writeback", "0007_modificationproposal_linked_conflict_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modificationproposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("applied", "Applied"),
                    ("failed", "Failed"),
                    ("superseded", "Superseded"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
