# Generated by Django 5.2.11 on 2026-05-05 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("writeback", "0008_alter_modificationproposal_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="modificationproposal",
            name="code_review_acknowledged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the user ticked 'I have reviewed this code and accept responsibility' on a Tier 3 proposal. Tier 3 approval is refused if blank.",
                null=True,
                verbose_name="Code Review Acknowledged At",
            ),
        ),
        migrations.AddField(
            model_name="modificationproposal",
            name="code_review_acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="code_acknowledged_proposals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Code Review Acknowledged By",
            ),
        ),
    ]
