# Generated by Django 5.2.11 on 2026-08-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("writeback", "0010_supersede_pre_journal_proposals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modificationproposal",
            name="code_review_acknowledged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the user ticked 'I have reviewed this code and accept responsibility' on a proposal containing generated code. Approval of such a proposal is refused if blank.",
                null=True,
                verbose_name="Code Review Acknowledged At",
            ),
        ),
    ]
