# Generated by Django 5.2.11 on 2026-09-14 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("writeback", "0011_alter_modificationproposal_code_review_acknowledged_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="modificationproposal",
            name="base_fingerprint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 of the original file when proposed; approval refuses on mismatch",
                max_length=64,
                verbose_name="Base Fingerprint",
            ),
        ),
        migrations.AddField(
            model_name="modificationproposal",
            name="code",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The select()/modify() block that produced the diff; runs once, at proposal time",
                verbose_name="Generated Code",
            ),
        ),
        migrations.AddField(
            model_name="modificationproposal",
            name="diff",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="IfcDiff.as_dict(): what the code did to the scratch copy, measured by the harness",
                verbose_name="Diff",
            ),
        ),
        migrations.AddField(
            model_name="modificationproposal",
            name="explainer_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The model that wrote the blind explanation",
                max_length=100,
                verbose_name="Explainer Model",
            ),
        ),
        migrations.AddField(
            model_name="modificationproposal",
            name="flags_acknowledged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user ticked every flagged diff row in the approve request",
                null=True,
                verbose_name="Flags Acknowledged At",
            ),
        ),
        migrations.AddField(
            model_name="modificationproposal",
            name="guardian_skipped",
            field=models.BooleanField(
                default=False,
                help_text="The user switched the document check off for this request",
                verbose_name="Guardian Skipped",
            ),
        ),
        migrations.AddField(
            model_name="modificationproposal",
            name="scratch_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The reviewed copy that replaces the original on approval",
                max_length=500,
                verbose_name="Scratch Path",
            ),
        ),
        migrations.AddField(
            model_name="modificationproposal",
            name="target_global_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="What select() returned; the only entities modify() may touch",
                verbose_name="Target GlobalIds",
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="changes",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="V2 mutation journal. Null on V3 proposals",
                null=True,
                verbose_name="Changes (V2)",
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="code_review_acknowledged_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Code Review Acknowledged At (V2)"
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="code_review_acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="code_acknowledged_proposals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Code Review Acknowledged By (V2)",
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="confidence",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="V2 classification confidence. Null on V3 proposals",
                null=True,
                verbose_name="Confidence (V2)",
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="diff_preview",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="V2 rendered diff rows as JSON text. Null on V3 proposals",
                null=True,
                verbose_name="Diff Preview (V2)",
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="filter_spec",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="V2 entity filter. Null on V3 proposals",
                null=True,
                verbose_name="Filter Spec (V2)",
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="intent_json",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="V2 parsed intent. Null on V3 proposals",
                null=True,
                verbose_name="Intent JSON (V2)",
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="operation",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="V2 operation name. Null on V3 proposals",
                max_length=50,
                null=True,
                verbose_name="Operation (V2)",
            ),
        ),
        migrations.AlterField(
            model_name="modificationproposal",
            name="tier",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Tier 1 – Certified Ops (GREEN)"),
                    (2, "Tier 2 – Operation Planner (ORANGE)"),
                    (3, "Tier 3 – IfcOpenShell Direct (RED)"),
                ],
                help_text="V2 tier. Null on V3 proposals",
                null=True,
                verbose_name="RSAA Tier (V2)",
            ),
        ),
    ]
