# Generated by Django 5.2.11 on 2026-09-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("writeback", "0012_proposal_v3_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modificationproposal",
            name="explanation",
            field=models.TextField(
                blank=True,
                help_text="The blind explanation; empty when the explainer failed (the card shows a placeholder)",
                verbose_name="Explanation",
            ),
        ),
    ]
