# Generated by Django 5.2.11 on 2026-05-05 22:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BetaApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Used as the username when an account is created on approval.",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Full name")),
                (
                    "job_title",
                    models.CharField(blank=True, max_length=120, verbose_name="Role / job title"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="What the applicant wants to use Castor for.",
                        verbose_name="Why are you interested?",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("called", "Intro call scheduled"),
                            ("approved", "Approved (account created)"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Private — call summary, vetting context, anything not for the applicant.",
                        verbose_name="Operator notes",
                    ),
                ),
                ("submitted_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("submitted_user_agent", models.CharField(blank=True, default="", max_length=500)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beta_application",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Beta Application",
                "verbose_name_plural": "Beta Applications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="beta_betaap_status_54a50f_idx"
                    )
                ],
            },
        ),
    ]
