# Generated by Django 5.2.11 on 2026-06-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beta", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="betaapplication",
            name="provisioning_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Sample-project provisioning failure trace, if any. Run `manage.py provision_sample_project <user_id> --force-files` to recover.",
                verbose_name="Provisioning error",
            ),
        ),
    ]
