# ifc_processor/tests/test_validators.py
"""Tests for IFC file validation utilities."""

import io

import pytest
from django.core.exceptions import ValidationError

from ifc_processor.services.validators import (
    IFCFileValidator,
    MAX_IFC_FILE_SIZE,
    _has_valid_ifc_signature,
    validate_ifc_file,
)


# ── Helpers ─────────────────────────────────────────────────────────────────


def _make_file(name: str, content: bytes, size: int | None = None):
    """Create a minimal file-like object for testing."""
    f = io.BytesIO(content)
    f.name = name
    f.size = size if size is not None else len(content)
    return f


VALID_IFC_CONTENT = b"ISO-10303-21;\nHEADER;\nENDSEC;\nDATA;\nENDSEC;\nEND-ISO-10303-21;"
VALID_IFC_CONTENT_FILE_DESC = b"FILE_DESCRIPTION(('Description'),'2;1');"
VALID_IFC_CONTENT_IFC4 = b"/* Generated by IfcOpenShell */\nIFC4;"


# ── validate_ifc_file ───────────────────────────────────────────────────────


class TestValidateIfcFile:
    """Tests for the validate_ifc_file() function."""

    def test_valid_ifc_file_returns_true(self):
        """Valid .ifc file with proper header returns (True, '')."""
        f = _make_file("model.ifc", VALID_IFC_CONTENT)
        is_valid, msg = validate_ifc_file(f)
        assert is_valid is True
        assert msg == ""

    def test_file_description_header_is_valid(self):
        """File with FILE_DESCRIPTION header is accepted."""
        f = _make_file("model.ifc", VALID_IFC_CONTENT_FILE_DESC)
        is_valid, _ = validate_ifc_file(f)
        assert is_valid is True

    def test_wrong_extension_returns_false(self):
        """Non-.ifc extension returns validation error."""
        f = _make_file("model.txt", VALID_IFC_CONTENT)
        is_valid, msg = validate_ifc_file(f)
        assert is_valid is False
        assert ".ifc" in msg or "extension" in msg.lower()

    def test_pdf_extension_returns_false(self):
        """PDF extension is rejected."""
        f = _make_file("model.pdf", VALID_IFC_CONTENT)
        is_valid, msg = validate_ifc_file(f)
        assert is_valid is False

    def test_uppercase_extension_accepted(self):
        """Uppercase .IFC extension is normalized and accepted."""
        f = _make_file("MODEL.IFC", VALID_IFC_CONTENT)
        # Extension check uses .lower() internally
        is_valid, _ = validate_ifc_file(f)
        # Depends on implementation — lowercase normalizes
        # The function does filename.lower() so .ifc extension is found
        assert is_valid is True

    def test_empty_file_returns_false(self):
        """Empty file returns validation error."""
        f = _make_file("model.ifc", b"", size=0)
        is_valid, msg = validate_ifc_file(f)
        assert is_valid is False
        assert "empty" in msg.lower()

    def test_oversized_file_returns_false(self):
        """File exceeding MAX_IFC_FILE_SIZE returns validation error."""
        f = _make_file("model.ifc", VALID_IFC_CONTENT, size=MAX_IFC_FILE_SIZE + 1)
        is_valid, msg = validate_ifc_file(f)
        assert is_valid is False
        assert "large" in msg.lower() or "MB" in msg

    def test_invalid_content_returns_false(self):
        """File with wrong content (not IFC/STEP format) returns error."""
        f = _make_file("model.ifc", b"This is definitely not an IFC file content here")
        is_valid, msg = validate_ifc_file(f)
        assert is_valid is False
        assert "Invalid" in msg or "format" in msg.lower()

    def test_seek_position_restored_after_validation(self):
        """File seek position is restored to original after validation."""
        f = _make_file("model.ifc", VALID_IFC_CONTENT)
        f.seek(10)  # Seek to non-zero position
        validate_ifc_file(f)
        assert f.tell() == 10  # Position restored


# ── _has_valid_ifc_signature ────────────────────────────────────────────────


class TestHasValidIfcSignature:
    """Tests for the _has_valid_ifc_signature() helper."""

    def test_iso_10303_signature_is_valid(self):
        """ISO-10303-21 header is recognized."""
        assert _has_valid_ifc_signature(b"ISO-10303-21;\nDATA;") is True

    def test_file_description_signature_is_valid(self):
        """FILE_DESCRIPTION header is recognized."""
        assert _has_valid_ifc_signature(b"FILE_DESCRIPTION(('test'),'2;1');") is True

    def test_ifc2x_signature_is_valid(self):
        """IFC2X version string is recognized."""
        assert _has_valid_ifc_signature(b"/* IFC2X3 SCHEMA */") is True

    def test_ifc4_signature_is_valid(self):
        """IFC4 version string is recognized."""
        assert _has_valid_ifc_signature(b"FILE_SCHEMA(('IFC4'));") is True

    def test_random_bytes_returns_false(self):
        """Random binary content is not recognized as IFC."""
        assert _has_valid_ifc_signature(b"\x00\x01\x02\x03\x04\x05garbage") is False

    def test_empty_bytes_returns_false(self):
        """Empty byte string returns False."""
        assert _has_valid_ifc_signature(b"") is False

    def test_case_insensitive_detection(self):
        """IFC signatures are detected case-insensitively."""
        assert _has_valid_ifc_signature(b"iso-10303-21;") is True


# ── IFCFileValidator ────────────────────────────────────────────────────────


class TestIFCFileValidator:
    """Tests for the IFCFileValidator Django validator class."""

    def test_valid_file_does_not_raise(self):
        """Valid IFC file passes validation without raising."""
        validator = IFCFileValidator()
        f = _make_file("model.ifc", VALID_IFC_CONTENT)
        # Should not raise
        validator(f)

    def test_invalid_file_raises_validation_error(self):
        """Invalid file raises Django ValidationError."""
        validator = IFCFileValidator()
        f = _make_file("model.txt", VALID_IFC_CONTENT)
        with pytest.raises(ValidationError):
            validator(f)

    def test_equality_same_max_size(self):
        """Two validators with same max_size are equal."""
        v1 = IFCFileValidator(max_size=1000)
        v2 = IFCFileValidator(max_size=1000)
        assert v1 == v2

    def test_inequality_different_max_size(self):
        """Validators with different max_size are not equal."""
        v1 = IFCFileValidator(max_size=1000)
        v2 = IFCFileValidator(max_size=2000)
        assert v1 != v2

    def test_custom_max_size_stored(self):
        """Custom max_size is stored on the validator instance."""
        validator = IFCFileValidator(max_size=10)
        assert validator.max_size == 10

    def test_not_equal_to_different_type(self):
        """Validator is not equal to non-validator objects."""
        v = IFCFileValidator()
        assert v != "not a validator"
        assert v != 42
