# Generated by Django 6.0.2 on 2026-06-03 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castor_ifc_insights', '0004_clear_explicit_table_names'),
        ('environments', '0007_add_audit_name_cache_to_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='environments.project'),
        ),
    ]
