# Generated by Django 5.2.11 on 2026-02-03 23:03

import uuid

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models

import ifc_processor.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("environments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IFCFile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("file", models.FileField(upload_to=ifc_processor.models.ifc_upload_path)),
                ("file_hash", models.CharField(db_index=True, max_length=64)),
                ("schema_version", models.CharField(blank=True, max_length=20)),
                ("project_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("entity_count", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ifc_files",
                        to="environments.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "IFC File",
                "verbose_name_plural": "IFC Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IFCEntity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("global_id", models.CharField(db_index=True, max_length=64)),
                ("ifc_type", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(blank=True, db_index=True, max_length=255)),
                ("building", models.CharField(blank=True, max_length=255)),
                ("building_storey", models.CharField(blank=True, db_index=True, max_length=255)),
                ("space", models.CharField(blank=True, max_length=255)),
                ("properties", models.JSONField(default=dict)),
                ("description", models.TextField(blank=True)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768, null=True)),
                (
                    "ifc_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="ifc_processor.ifcfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "IFC Entity",
                "verbose_name_plural": "IFC Entities",
                "ordering": ["ifc_type", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="ifcfile",
            index=models.Index(fields=["project", "status"], name="ifc_process_project_5efda6_idx"),
        ),
        migrations.AddIndex(
            model_name="ifcfile",
            index=models.Index(
                fields=["project", "-created_at"], name="ifc_process_project_f70044_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ifcentity",
            index=models.Index(
                fields=["ifc_file", "ifc_type"], name="ifc_process_ifc_fil_7af777_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ifcentity",
            index=models.Index(
                fields=["ifc_file", "global_id"], name="ifc_process_ifc_fil_744927_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ifcentity",
            index=models.Index(
                fields=["ifc_file", "building_storey"], name="ifc_process_ifc_fil_c3b7d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ifcentity",
            index=models.Index(fields=["ifc_type", "name"], name="ifc_process_ifc_typ_6695a1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="ifcentity",
            unique_together={("ifc_file", "global_id")},
        ),
    ]
