# Generated by Django 5.2.11 on 2026-02-04 19:42

import django.db.models.deletion
import ifc_processor.models
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0002_alter_project_options_and_more'),
        ('ifc_processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifcentity',
            name='building',
            field=models.CharField(blank=True, max_length=255, verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='ifcentity',
            name='building_storey',
            field=models.CharField(blank=True, db_index=True, help_text='Floor/level where this entity is located', max_length=255, verbose_name='Building Storey'),
        ),
        migrations.AlterField(
            model_name='ifcentity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='ifcentity',
            name='description',
            field=models.TextField(blank=True, help_text='AI-generated semantic description for search', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ifcentity',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name='ifcentity',
            name='global_id',
            field=models.CharField(db_index=True, help_text='Unique IFC GUID', max_length=64, verbose_name='Global ID'),
        ),
        migrations.AlterField(
            model_name='ifcentity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ifcentity',
            name='ifc_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='ifc_processor.ifcfile', verbose_name='IFC File'),
        ),
        migrations.AlterField(
            model_name='ifcentity',
            name='ifc_type',
            field=models.CharField(db_index=True, help_text='e.g., IfcDoor, IfcWall, IfcWindow', max_length=100, verbose_name='IFC Type'),
        ),
        migrations.AlterField(
            model_name='ifcentity',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ifcentity',
            name='properties',
            field=models.JSONField(blank=True, default=dict, help_text='IFC properties and property sets as JSON', verbose_name='Properties'),
        ),
        migrations.AlterField(
            model_name='ifcentity',
            name='space',
            field=models.CharField(blank=True, help_text='Room or space containing this entity', max_length=255, verbose_name='Space'),
        ),
        migrations.AlterField(
            model_name='ifcentity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='ifcfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='ifcfile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ifcfile',
            name='entity_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of IFC entities extracted', verbose_name='Entity Count'),
        ),
        migrations.AlterField(
            model_name='ifcfile',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details if processing failed', verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='ifcfile',
            name='file',
            field=models.FileField(help_text='IFC file (.ifc format)', max_length=500, upload_to=ifc_processor.models.ifc_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='ifcfile',
            name='file_hash',
            field=models.CharField(db_index=True, help_text='SHA-256 hash for detecting changes', max_length=64, verbose_name='File Hash'),
        ),
        migrations.AlterField(
            model_name='ifcfile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ifcfile',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='ifcfile',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processed At'),
        ),
        migrations.AlterField(
            model_name='ifcfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifc_files', to='environments.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='ifcfile',
            name='project_name',
            field=models.CharField(blank=True, help_text='Project name extracted from IFC header', max_length=255, verbose_name='IFC Project Name'),
        ),
        migrations.AlterField(
            model_name='ifcfile',
            name='schema_version',
            field=models.CharField(blank=True, help_text='e.g., IFC2X3, IFC4', max_length=20, verbose_name='IFC Schema Version'),
        ),
        migrations.AlterField(
            model_name='ifcfile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ifcfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
