# Generated by Django 5.2.11 on 2026-02-04 21:53

import django.db.models.deletion
import ifc_processor.models
import ifc_processor.services.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifc_processor', '0002_alter_ifcentity_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifcfile',
            name='file',
            field=models.FileField(help_text='IFC file (.ifc format)', max_length=500, upload_to=ifc_processor.models.ifc_upload_path, validators=[ifc_processor.services.validators.IFCFileValidator()], verbose_name='File'),
        ),
        migrations.CreateModel(
            name='IFCDataIssue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('duplicate_guid', 'Duplicate GlobalID'), ('invalid_geometry', 'Invalid Geometry'), ('missing_property', 'Missing Required Property')], max_length=50)),
                ('global_id', models.CharField(max_length=64)),
                ('ifc_type', models.CharField(max_length=100)),
                ('raw_data', models.JSONField(help_text='The properties and metadata of the conflicting element.')),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('ifc_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_issues', to='ifc_processor.ifcfile')),
            ],
            options={
                'verbose_name': 'IFC Data Issue',
                'verbose_name_plural': 'IFC Data Issues',
            },
        ),
    ]
