# Generated by Django 5.2.11 on 2026-02-10 01:34

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ifc_processor", "0003_alter_ifcfile_file_ifcdataissue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ifcentity",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
