# Generated by Django 5.2.11 on 2026-03-23 21:37

from django.db import migrations, models

import ifc_processor.models
import ifc_processor.services.validators


class Migration(migrations.Migration):
    dependencies = [
        ("ifc_processor", "0004_alter_ifcentity_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ifcentity",
            name="building",
            field=models.CharField(blank=True, max_length=2000, verbose_name="Building"),
        ),
        migrations.AlterField(
            model_name="ifcentity",
            name="building_storey",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Floor/level where this entity is located",
                max_length=2000,
                verbose_name="Building Storey",
            ),
        ),
        migrations.AlterField(
            model_name="ifcentity",
            name="ifc_type",
            field=models.CharField(
                db_index=True,
                help_text="e.g., IfcDoor, IfcWall, IfcWindow",
                max_length=2000,
                verbose_name="IFC Type",
            ),
        ),
        migrations.AlterField(
            model_name="ifcentity",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=2000, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="ifcentity",
            name="space",
            field=models.CharField(
                blank=True,
                help_text="Room or space containing this entity",
                max_length=2000,
                verbose_name="Space",
            ),
        ),
        migrations.AlterField(
            model_name="ifcfile",
            name="file",
            field=models.FileField(
                help_text="IFC file (.ifc format)",
                max_length=2000,
                upload_to=ifc_processor.models.ifc_upload_path,
                validators=[ifc_processor.services.validators.IFCFileValidator()],
                verbose_name="File",
            ),
        ),
    ]
