# Generated by Django 5.2.11 on 2026-03-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ifc_processor", "0005_alter_ifcentity_building_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ifcdataissue",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("duplicate_guid", "Duplicate GlobalID"),
                    ("invalid_geometry", "Invalid Geometry"),
                    ("missing_property", "Missing Required Property"),
                    ("orphaned_element", "Orphaned Element (No Spatial Placement)"),
                ],
                max_length=50,
            ),
        ),
    ]
