# Generated by Django 5.2.11 on 2026-04-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ifc_processor", "0006_alter_ifcdataissue_issue_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ifcfile",
            name="project_units",
            field=models.JSONField(
                blank=True,
                help_text='Declared units from IfcUnitAssignment, e.g. {"LENGTHUNIT": "mm", "AREAUNIT": "m²"}',
                null=True,
                verbose_name="Project Units",
            ),
        ),
    ]
