# Generated by Django 5.2.11 on 2026-04-15 16:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ifc_processor", "0007_ifcfile_project_units"),
    ]

    operations = [
        migrations.CreateModel(
            name="IFCElementType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "global_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique IFC GUID of the type object",
                        max_length=64,
                        verbose_name="Global ID",
                    ),
                ),
                (
                    "ifc_type",
                    models.CharField(
                        db_index=True,
                        help_text="e.g., IfcDoorType, IfcBeamType, IfcWallType",
                        max_length=2000,
                        verbose_name="IFC Type",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Type name, e.g. 'Door-Single-Panel', 'Standard Footing 300x400'",
                        max_length=2000,
                        verbose_name="Name",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "applicable_occurrence",
                    models.CharField(
                        blank=True,
                        help_text="IFC ApplicableOccurrence attribute — subtype filter string",
                        max_length=2000,
                        verbose_name="Applicable Occurrence",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        help_text="IFC Tag attribute — user-defined identifier",
                        max_length=255,
                        verbose_name="Tag",
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-level property sets extracted from the IFC type object",
                        verbose_name="Properties",
                    ),
                ),
                (
                    "ifc_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="element_types",
                        to="ifc_processor.ifcfile",
                        verbose_name="IFC File",
                    ),
                ),
            ],
            options={
                "verbose_name": "IFC Element Type",
                "verbose_name_plural": "IFC Element Types",
                "ordering": ["ifc_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="ifcentity",
            name="element_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Defining type object (e.g. IfcDoorType) via IfcRelDefinesByType",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrences",
                to="ifc_processor.ifcelementtype",
                verbose_name="Element Type",
            ),
        ),
        migrations.AddIndex(
            model_name="ifcentity",
            index=models.Index(
                fields=["ifc_file", "ifc_type", "element_type"],
                name="ifc_process_ifc_fil_7425d5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ifcelementtype",
            index=models.Index(
                fields=["ifc_file", "ifc_type"], name="ifc_process_ifc_fil_b47d41_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ifcelementtype",
            unique_together={("ifc_file", "global_id")},
        ),
    ]
