# Generated by Django 5.2.11 on 2026-04-15 20:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ifc_processor", "0008_add_ifc_element_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="IFCSpatialElement",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spatial_type",
                    models.CharField(
                        choices=[
                            ("site", "Site"),
                            ("building", "Building"),
                            ("building_storey", "Building Storey"),
                            ("space", "Space"),
                            ("facility", "Facility"),
                            ("facility_part", "Facility Part"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Spatial Type",
                    ),
                ),
                (
                    "long_name",
                    models.CharField(
                        blank=True,
                        help_text="IFC LongName attribute",
                        max_length=2000,
                        verbose_name="Long Name",
                    ),
                ),
                (
                    "composition_type",
                    models.CharField(
                        blank=True,
                        help_text="ELEMENT, COMPLEX, or PARTIAL",
                        max_length=20,
                        verbose_name="Composition Type",
                    ),
                ),
                (
                    "elevation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Elevation value (IfcBuildingStorey only)",
                        max_digits=12,
                        null=True,
                        verbose_name="Elevation",
                    ),
                ),
            ],
            options={
                "verbose_name": "IFC Spatial Element",
                "verbose_name_plural": "IFC Spatial Elements",
                "ordering": ["spatial_type", "entity__name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="ifcentity",
            name="ifc_process_ifc_fil_c3b7d1_idx",
        ),
        migrations.RemoveField(
            model_name="ifcentity",
            name="building",
        ),
        migrations.RemoveField(
            model_name="ifcentity",
            name="building_storey",
        ),
        migrations.RemoveField(
            model_name="ifcentity",
            name="space",
        ),
        migrations.AddField(
            model_name="ifcspatialelement",
            name="entity",
            field=models.OneToOneField(
                help_text="The IFCEntity record holding this spatial element's data",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spatial_node",
                to="ifc_processor.ifcentity",
                verbose_name="Entity",
            ),
        ),
        migrations.AddField(
            model_name="ifcspatialelement",
            name="ifc_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spatial_elements",
                to="ifc_processor.ifcfile",
                verbose_name="IFC File",
            ),
        ),
        migrations.AddField(
            model_name="ifcspatialelement",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent spatial element (IfcRelAggregates)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="ifc_processor.ifcspatialelement",
                verbose_name="Parent",
            ),
        ),
        migrations.AddField(
            model_name="ifcentity",
            name="spatial_container",
            field=models.ForeignKey(
                blank=True,
                help_text="Direct spatial container (IfcRelContainedInSpatialStructure)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contained_entities",
                to="ifc_processor.ifcspatialelement",
                verbose_name="Spatial Container",
            ),
        ),
        migrations.AddIndex(
            model_name="ifcentity",
            index=models.Index(
                fields=["ifc_file", "spatial_container"], name="ifc_process_ifc_fil_698907_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ifcspatialelement",
            index=models.Index(
                fields=["ifc_file", "spatial_type"], name="ifc_process_ifc_fil_fada60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ifcspatialelement",
            index=models.Index(
                fields=["ifc_file", "parent"], name="ifc_process_ifc_fil_042a78_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ifcspatialelement",
            constraint=models.UniqueConstraint(
                fields=("ifc_file", "entity"), name="unique_spatial_element_per_entity"
            ),
        ),
    ]
