# Generated by Django 5.2.11 on 2026-04-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ifc_processor", "0010_add_data_issue_dedup"),
    ]

    operations = [
        migrations.AddField(
            model_name="ifcentity",
            name="ifc_description",
            field=models.TextField(
                blank=True,
                help_text="IFC `Description` attribute on the occurrence (IfcRoot.Description). Distinct from `description`, which is the AI-generated semantic summary used by RAG.",
                verbose_name="IFC Description",
            ),
        ),
        migrations.AddField(
            model_name="ifcentity",
            name="tag",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="IFC `Tag` attribute on the occurrence — user-defined identifier (typically the source-app element id).",
                max_length=255,
                verbose_name="Tag",
            ),
        ),
    ]
