# Generated by Django 5.2.11 on 2026-08-05 21:59

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ifc_processor", "0011_ifcentity_ifc_description_ifcentity_tag"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ifcentity",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="ifcentity_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
