# Generated by Django 5.2.11 on 2026-02-03 23:03

import django.db.models.deletion
import documents.models
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('txt', 'Text File'), ('other', 'Other')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='environments.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('page_number', models.PositiveIntegerField(db_index=True, null=True)),
                ('chunk_index', models.PositiveIntegerField(db_index=True)),
                ('start_char', models.PositiveIntegerField(null=True)),
                ('end_char', models.PositiveIntegerField(null=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', 'status'], name='documents_d_project_cdca86_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', 'document_type'], name='documents_d_project_4f1b21_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', '-created_at'], name='documents_d_project_e576e0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='documents_d_documen_8ea6ce_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'page_number'], name='documents_d_documen_1a14ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('document', 'chunk_index')},
        ),
    ]
