# Generated by Django 5.2.11 on 2026-02-04 19:42

import uuid

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models

import documents.models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        ("environments", "0002_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="documentchunk",
            options={
                "ordering": ["document", "chunk_index"],
                "verbose_name": "Document Chunk",
                "verbose_name_plural": "Document Chunks",
            },
        ),
        migrations.AlterField(
            model_name="document",
            name="chunk_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of text chunks extracted", verbose_name="Chunk Count"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("docx", "Word Document"),
                    ("txt", "Text File"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Document Type",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="error_message",
            field=models.TextField(
                blank=True,
                help_text="Error details if processing failed",
                verbose_name="Error Message",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                help_text="Supported formats: PDF, DOCX, TXT",
                max_length=500,
                upload_to=documents.models.document_upload_path,
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="File Name"),
        ),
        migrations.AlterField(
            model_name="document",
            name="page_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Page Count"),
        ),
        migrations.AlterField(
            model_name="document",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Processed At"),
        ),
        migrations.AlterField(
            model_name="document",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="environments.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="chunk_index",
            field=models.PositiveIntegerField(
                db_index=True,
                help_text="Sequential index of this chunk within the document",
                verbose_name="Chunk Index",
            ),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="content",
            field=models.TextField(help_text="Text content of this chunk", verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="documents.document",
                verbose_name="Document",
            ),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="end_char",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="End Character"),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="page_number",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="Page Number"
            ),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="start_char",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Start Character"
            ),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
