# Generated by Django 5.2.11 on 2026-02-10 01:34

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_alter_document_options_alter_documentchunk_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
