# Generated by Django 5.2.11 on 2026-03-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_alter_documentchunk_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="has_visual_content",
            field=models.BooleanField(
                default=False,
                help_text="Set when initial ingestion detects image-dominant or zero-text pages",
                verbose_name="Has Visual Content",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="ocr_engine",
            field=models.CharField(
                blank=True,
                help_text="Engine identifier, e.g. 'glm-ocr:latest'",
                max_length=100,
                null=True,
                verbose_name="OCR Engine",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="ocr_page_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of pages processed by OCR",
                null=True,
                verbose_name="OCR Page Count",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="ocr_processed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="OCR Processed At"),
        ),
        migrations.AddField(
            model_name="document",
            name="ocr_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="none",
                max_length=20,
                verbose_name="OCR Status",
            ),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="chunk_source",
            field=models.CharField(
                choices=[
                    ("text_parser", "Text Parser"),
                    ("glm_ocr", "GLM-OCR"),
                    ("hybrid", "Hybrid"),
                ],
                db_index=True,
                default="text_parser",
                max_length=20,
                verbose_name="Chunk Source",
            ),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="extracted_from_image",
            field=models.BooleanField(
                default=False,
                help_text="True when this chunk was produced by OCR from a raster image",
                verbose_name="Extracted from Image",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("docx", "Word Document"),
                    ("txt", "Text File"),
                    ("scanned_pdf", "Scanned PDF"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Document Type",
            ),
        ),
    ]
