# Generated by Django 5.2.11 on 2026-03-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_document_has_visual_content_document_ocr_engine_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(db_index=True, max_length=1500, verbose_name="File Name"),
        ),
    ]
