# Generated by Django 5.2.11 on 2026-08-05 21:59

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_alter_document_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="documentchunk",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="docchunk_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
