# Generated by Django 5.2.11 on 2026-02-04 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('environments', '0002_alter_project_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Chat Session', 'verbose_name_plural': 'Chat Sessions'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='messagefeedback',
            options={'verbose_name': 'Message Feedback', 'verbose_name_plural': 'Message Feedbacks'},
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this is the current active session', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='mode',
            field=models.CharField(choices=[('ask', 'Ask'), ('modify', 'Modify')], db_index=True, default='ask', max_length=20, verbose_name='Mode'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='environments.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, help_text='Auto-generated from first message', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='message',
            name='has_proposal',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this message contains a modification proposal', verbose_name='Has Proposal'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='retrieved_context',
            field=models.JSONField(blank=True, default=list, help_text='Sources used to generate the response', verbose_name='Retrieved Context'),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], db_index=True, max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='message',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='messagefeedback',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional feedback details', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='messagefeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='messagefeedback',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='messagefeedback',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chat.message', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='messagefeedback',
            name='rating',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=20, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='messagefeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='messagefeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
