# Generated by Django 5.2.11 on 2026-04-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_chatsession_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="compacted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this message was summarized into a compaction summary",
                null=True,
                verbose_name="Compacted At",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_compaction_summary",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this message is a compacted summary of older messages",
                verbose_name="Compaction Summary",
            ),
        ),
    ]
