# scheduling/services/executive_controls/methodology.py
"""E8-v1 metric methodology registry — extends E2-F pattern without breaking e2-f-v1."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from scheduling.services.executive_controls.contracts import E8MetricDefinition, E8MetricResult
from scheduling.services.executive_controls.enums import AnalyticalState, MetricAuthority
from scheduling.services.governance.policy import TRUSTED_BINDING_POLICY_ID

E8_METHODOLOGY_VERSION = "e8-v1"

BASELINE_SEMANTICS = (
    "Current Reference/Baseline Fields from Imported Schedule — "
    "not a contractual baseline until BaselineVersion exists."
)
DATA_DATE_SEMANTICS = (
    "Metrics computed as-of ScheduleSource.data_date when present; else system date."
)
LIVE_STATE = AnalyticalState.LIVE_CURRENT.value
REIMPORT_CAVEAT = "Results may change after schedule or model re-import because no frozen analytical snapshot is selected."


def _def(
    metric_id: str,
    label: str,
    business_question: str,
    formula: str,
    numerator: str,
    denominator: str,
    *,
    weighting: str = "none",
    source: str,
    source_authority: str,
    inclusion: str,
    exclusion: str,
    missing: str = "Report unavailable with reason — never fabricate values.",
    coverage_metric: str = "",
    authority: str = MetricAuthority.DERIVED.value,
    caveat: str = "",
    drilldown: str = "executive_controls_delays",
    drilldown_filter: dict[str, str] | None = None,
    filters: tuple[str, ...] = (),
) -> E8MetricDefinition:
    return E8MetricDefinition(
        metric_id=metric_id,
        label=label,
        business_question=business_question,
        formula=formula,
        numerator_definition=numerator,
        denominator_definition=denominator,
        weighting_method=weighting,
        primary_source=source,
        source_authority=source_authority,
        inclusion_rules=inclusion,
        exclusion_rules=exclusion,
        baseline_semantics=BASELINE_SEMANTICS,
        data_date_semantics=DATA_DATE_SEMANTICS,
        missing_data_behavior=missing,
        coverage_metric=coverage_metric,
        authority_level=authority,
        caveat=caveat or REIMPORT_CAVEAT,
        drilldown_route=drilldown,
        drilldown_filter=drilldown_filter or {},
        compatible_filters=filters,
        version=E8_METHODOLOGY_VERSION,
    )


E8_METRIC_REGISTRY: dict[str, E8MetricDefinition] = {
    # Schedule counts
    "e8.all_activity_count": _def(
        "e8.all_activity_count",
        "All schedule activities",
        "How many activities exist in the imported schedule?",
        "COUNT(Task)",
        "All Task rows",
        "N/A",
        source="Task",
        source_authority="current_schedule",
        inclusion="All tasks in project",
        exclusion="None",
        authority=MetricAuthority.AUTHORITATIVE.value,
        drilldown="executive_controls_delays",
    ),
    "e8.schedulable_activity_count": _def(
        "e8.schedulable_activity_count",
        "Schedulable activities",
        "How many activities have start and end dates for CPM/EVM?",
        "COUNT(Task WHERE start_date AND end_date)",
        "Tasks with both dates",
        "All tasks",
        source="Task",
        source_authority="current_schedule",
        inclusion="Tasks with start_date and end_date",
        exclusion="Dateless activities",
        coverage_metric="e8.schedule_field_coverage",
        authority=MetricAuthority.AUTHORITATIVE.value,
    ),
    # Schedule progress
    "e8.planned_progress": _def(
        "e8.planned_progress",
        "Planned progress %",
        "How much work should be complete by the data date?",
        "Σ(weight × planned_pct) / Σ(weight)",
        "Weighted planned completion at data date",
        "Weighted in-scope tasks",
        weighting="BAC if cost_evm else duration",
        source="scheduling.services.evm.compute_evm",
        source_authority="current_schedule",
        inclusion="Physical tasks with dates",
        exclusion="Non-physical without explicit scope filter",
        authority=MetricAuthority.DERIVED.value,
        caveat=BASELINE_SEMANTICS,
        drilldown="executive_controls_evm",
    ),
    "e8.actual_progress": _def(
        "e8.actual_progress",
        "Actual progress %",
        "How much work is actually complete?",
        "Σ(weight × earned_pct) / Σ(weight)",
        "Weighted earned completion",
        "Same weight scope as planned",
        weighting="BAC if cost_evm else duration",
        source="scheduling.services.evm.compute_evm",
        source_authority="actual_progress",
        inclusion="Tasks with physical_pct, duration_pct, or linear fallback",
        exclusion="None at task level",
        authority=MetricAuthority.DERIVED.value,
        drilldown="executive_controls_evm",
    ),
    "e8.schedule_variance": _def(
        "e8.schedule_variance",
        "Schedule performance variance %",
        "How far ahead or behind is actual progress vs planned?",
        "actual_progress − planned_progress",
        "Variance in percentage points",
        "N/A",
        source="derived from e8.planned_progress and e8.actual_progress",
        source_authority="calculated",
        inclusion="Same scope as progress metrics",
        exclusion="None",
        authority=MetricAuthority.DERIVED.value,
    ),
    # Delay counts
    "e8.completed_late_count": _def(
        "e8.completed_late_count",
        "Completed late",
        "How many finished activities finished after baseline finish?",
        "COUNT(completed AND actual_end > baseline_finish)",
        "Completed late tasks",
        "Completed tasks with baseline finish",
        source="DelayClassificationService",
        source_authority="baseline_schedule",
        inclusion="Status=complete with actual_end and end_date",
        exclusion="Missing baseline or actual finish",
        authority=MetricAuthority.DERIVED.value,
        drilldown_filter={"delay_type": "completed_late"},
        filters=("delay_type", "stage", "scope_classification"),
    ),
    "e8.currently_late_count": _def(
        "e8.currently_late_count",
        "Currently late",
        "How many unfinished activities should have finished before the data date?",
        "COUNT(NOT complete AND required_finish < data_date)",
        "Currently late tasks",
        "Unfinished tasks with forecast finish",
        source="DelayClassificationService",
        source_authority="current_schedule",
        inclusion="Planned, active, delayed status",
        exclusion="Completed tasks",
        authority=MetricAuthority.DERIVED.value,
        drilldown_filter={"delay_type": "currently_late"},
    ),
    "e8.forecast_late_count": _def(
        "e8.forecast_late_count",
        "Forecast late",
        "How many unfinished activities forecast to finish after baseline?",
        "COUNT(NOT complete AND forecast_finish > baseline_finish)",
        "Forecast late tasks",
        "Unfinished with baseline and forecast",
        source="DelayClassificationService",
        source_authority="current_schedule",
        inclusion="Incomplete tasks",
        exclusion="Completed tasks (use completed_late instead)",
        authority=MetricAuthority.DERIVED.value,
        drilldown_filter={"delay_type": "forecast_late"},
    ),
    "e8.critical_count": _def(
        "e8.critical_count",
        "Critical activities",
        "How many activities are on the critical path?",
        "COUNT(is_critical=True)",
        "Critical tasks",
        "Schedulable tasks",
        source="Task.is_critical from CPM",
        source_authority="calculated",
        inclusion="Tasks with CPM recomputed",
        exclusion="Non-physical unless filtered",
        authority=MetricAuthority.AUTHORITATIVE.value,
        drilldown_filter={"delay_type": "critical"},
    ),
    "e8.negative_float_count": _def(
        "e8.negative_float_count",
        "Negative float",
        "How many activities have negative total float?",
        "COUNT(total_float < 0)",
        "Negative float tasks",
        "Tasks with float computed",
        source="Task.total_float",
        source_authority="calculated",
        inclusion="CPM-computed tasks",
        exclusion="Missing float",
        authority=MetricAuthority.AUTHORITATIVE.value,
        drilldown_filter={"delay_type": "negative_float"},
    ),
    "e8.zero_float_count": _def(
        "e8.zero_float_count",
        "Zero float",
        "How many activities have exactly zero total float?",
        "COUNT(total_float = 0)",
        "Zero float tasks",
        "Tasks with float computed",
        source="Task.total_float",
        source_authority="calculated",
        inclusion="CPM-computed tasks",
        exclusion="Missing float",
        authority=MetricAuthority.AUTHORITATIVE.value,
        drilldown_filter={"delay_type": "zero_float"},
    ),
    "e8.near_critical_count": _def(
        "e8.near_critical_count",
        "Near critical",
        "How many activities have positive float within the near-critical threshold?",
        "COUNT(0 < total_float <= threshold)",
        "Near-critical tasks",
        "Tasks with float computed",
        source="Task.total_float",
        source_authority="calculated",
        inclusion="Default threshold 5 working days",
        exclusion="Critical and negative float",
        authority=MetricAuthority.DERIVED.value,
        drilldown_filter={"delay_type": "near_critical"},
    ),
    "e8.project_finish_variance": _def(
        "e8.project_finish_variance",
        "Project finish variance (days)",
        "How many days is forecast project completion after baseline completion?",
        "working_day_diff(baseline_project_finish, forecast_project_finish)",
        "Project finish slip days",
        "N/A",
        source="DelayClassificationService.project_finish_variance",
        source_authority="calculated",
        inclusion="Physical/schedulable tasks",
        exclusion="Missing dates",
        authority=MetricAuthority.DERIVED.value,
        caveat=BASELINE_SEMANTICS,
    ),
    # Cost / EVM
    "e8.pv": _def(
        "e8.pv",
        "Planned Value (PV)",
        "What is the budgeted cost of work scheduled by the data date?",
        "Σ BAC × planned_pct",
        "PV at data date",
        "BAC",
        weighting="cost or duration per mode",
        source="compute_evm",
        source_authority="baseline_schedule",
        inclusion="cost_evm or schedule_performance mode",
        exclusion="Tasks without dates",
        authority=MetricAuthority.DERIVED.value,
        drilldown="executive_controls_evm",
    ),
    "e8.ev": _def(
        "e8.ev",
        "Earned Value (EV) / Earned Progress",
        "What is the earned value or progress-weighted earned amount?",
        "Σ BAC × earned_pct",
        "EV at data date",
        "BAC",
        source="compute_evm",
        source_authority="actual_progress",
        inclusion="Per performance mode",
        exclusion="None",
        authority=MetricAuthority.DERIVED.value,
        caveat="Label follows performance_mode — not monetary EV in schedule_performance mode.",
        drilldown="executive_controls_evm",
    ),
    "e8.ac": _def(
        "e8.ac",
        "Actual Cost (AC)",
        "What actual cost has been recorded?",
        "Σ ResourceAssignment.actual_cost (canonical preferred; P6 fallback)",
        "Total actual cost",
        "N/A",
        source="ResourceAssignment / P6ResourceAssignment",
        source_authority="actual_cost",
        inclusion="Tasks with actual_cost > 0",
        exclusion="Unavailable when no actual cost imported",
        missing="N/A — unavailable when ac_available=False",
        authority=MetricAuthority.AUTHORITATIVE.value,
        drilldown="executive_controls_evm",
    ),
    "e8.bac": _def(
        "e8.bac",
        "Budget at Completion (BAC)",
        "What is the total budget for in-scope work?",
        "Σ task cost or QTO or duration proxy",
        "Total BAC",
        "N/A",
        source="compute_evm",
        source_authority="baseline_schedule",
        inclusion="Per cost_basis",
        exclusion="None",
        authority=MetricAuthority.DERIVED.value,
        drilldown="executive_controls_evm",
    ),
    "e8.spi": _def(
        "e8.spi",
        "Schedule Performance Index (SPI)",
        "Is the project ahead or behind schedule?",
        "EV / PV",
        "SPI",
        "N/A",
        source="compute_evm",
        source_authority="calculated",
        inclusion="When PV > 0",
        exclusion="None",
        authority=MetricAuthority.DERIVED.value,
        drilldown="executive_controls_evm",
    ),
    "e8.cpi": _def(
        "e8.cpi",
        "Cost Performance Index (CPI)",
        "Is the project over or under budget?",
        "EV / AC",
        "CPI",
        "N/A",
        source="compute_evm",
        source_authority="actual_cost",
        inclusion="cost_evm with ac_available",
        exclusion="Unavailable when AC missing",
        missing="Unavailable — never fabricated",
        authority=MetricAuthority.AUTHORITATIVE.value,
        drilldown="executive_controls_evm",
    ),
    "e8.etc": _def(
        "e8.etc",
        "Estimate to Complete (ETC)",
        "How much cost remains to complete?",
        "(BAC − EV) / CPI when CPI available",
        "ETC",
        "N/A",
        source="compute_evm",
        source_authority="calculated",
        inclusion="cost_evm with AC",
        exclusion="Unavailable without CPI",
        authority=MetricAuthority.DERIVED.value,
        drilldown="executive_controls_evm",
    ),
    "e8.eac": _def(
        "e8.eac",
        "Estimate at Completion (EAC)",
        "What is the forecast total cost?",
        "AC + ETC or BAC/CPI",
        "EAC",
        "N/A",
        source="compute_evm",
        source_authority="calculated",
        inclusion="cost_evm with AC",
        exclusion="Unavailable without AC",
        authority=MetricAuthority.DERIVED.value,
        drilldown="executive_controls_evm",
    ),
    "e8.vac": _def(
        "e8.vac",
        "Variance at Completion (VAC)",
        "How much over/under budget at completion?",
        "BAC − EAC",
        "VAC",
        "N/A",
        source="compute_evm",
        source_authority="calculated",
        inclusion="cost_evm with AC",
        exclusion="Unavailable without AC",
        authority=MetricAuthority.DERIVED.value,
        drilldown="executive_controls_evm",
    ),
    "e8.tcpi": _def(
        "e8.tcpi",
        "To-Complete Performance Index (TCPI)",
        "What CPI is needed to meet BAC?",
        "(BAC − EV) / (BAC − AC)",
        "TCPI",
        "N/A",
        source="trend_engine / compute_evm",
        source_authority="calculated",
        inclusion="cost_evm with AC",
        exclusion="Unavailable without AC",
        authority=MetricAuthority.DERIVED.value,
        drilldown="executive_controls_evm",
    ),
    "e8.schedule_performance_index": _def(
        "e8.schedule_performance_index",
        "Schedule Performance Index (duration proxy)",
        "Progress vs plan when cost data is unavailable — NOT monetary EVM.",
        "EV / PV using duration-weighted BAC",
        "SPI in schedule_performance mode",
        "N/A",
        source="compute_evm",
        source_authority="duration_progress",
        inclusion="schedule_performance mode only",
        exclusion="Never labelled as Cost EVM",
        authority=MetricAuthority.PROXY.value,
        caveat="Duration-weighted schedule performance — not Earned Value Management.",
        drilldown="executive_controls_evm",
    ),
    # Resources
    "e8.planned_manhours": _def(
        "e8.planned_manhours",
        "Planned manhours",
        "How many labor hours are planned?",
        "Σ P6ResourceAssignment.planned_units (Labor)",
        "Planned labor units",
        "N/A",
        source="P6ResourceAssignment",
        source_authority="resource_assignment",
        inclusion="Labor resource type",
        exclusion="Non-labor resources",
        authority=MetricAuthority.AUTHORITATIVE.value,
        drilldown="executive_controls_resources",
    ),
    "e8.actual_manhours": _def(
        "e8.actual_manhours",
        "Actual manhours",
        "How many labor hours are recorded as actual?",
        "Σ actual_units (Labor)",
        "Actual labor units",
        "N/A",
        source="P6ResourceAssignment",
        source_authority="resource_assignment",
        inclusion="Labor with actual_units > 0",
        exclusion="Non-labor",
        authority=MetricAuthority.AUTHORITATIVE.value,
        drilldown="executive_controls_resources",
    ),
    "e8.remaining_manhours": _def(
        "e8.remaining_manhours",
        "Remaining manhours",
        "How many labor hours remain?",
        "planned − actual per assignment",
        "Remaining labor units",
        "N/A",
        source="P6ResourceAssignment",
        source_authority="resource_assignment",
        inclusion="Labor assignments",
        exclusion="None",
        authority=MetricAuthority.DERIVED.value,
        drilldown="executive_controls_resources",
    ),
    "e8.equivalent_workforce": _def(
        "e8.equivalent_workforce",
        "Equivalent Workforce (FTE-equivalent)",
        "What FTE-equivalent effort do recorded manhours represent?",
        "actual_hrs / (hours_per_day × working_days_in_period)",
        "FTE-equivalent count",
        "N/A",
        source="derived from manhours + P6Calendar",
        source_authority="calculated",
        inclusion="When labor manhours and calendar available",
        exclusion="Never labelled as actual site headcount",
        missing="Unavailable when manhours or calendar assumptions missing",
        authority=MetricAuthority.PROXY.value,
        caveat="Equivalent Workforce (FTE-equivalent from recorded manhours) — not attendance.",
        drilldown="executive_controls_resources",
    ),
    # Coverage
    "e8.schedule_field_coverage": _def(
        "e8.schedule_field_coverage",
        "Schedule field coverage",
        "What share of tasks have core schedule dates?",
        "tasks_with_dates / all_tasks",
        "Tasks with start and end",
        "All tasks",
        source="Task",
        source_authority="current_schedule",
        inclusion="All tasks",
        exclusion="None",
        authority=MetricAuthority.AUTHORITATIVE.value,
        drilldown="executive_controls_coverage",
    ),
    "e8.baseline_coverage": _def(
        "e8.baseline_coverage",
        "Baseline/reference finish coverage",
        "What share of tasks have a reference finish (end_date)?",
        "tasks_with_end_date / all_tasks",
        "Tasks with end_date",
        "All tasks",
        source="Task.end_date",
        source_authority="baseline_schedule",
        inclusion="All tasks",
        exclusion="None",
        caveat=BASELINE_SEMANTICS,
        authority=MetricAuthority.AUTHORITATIVE.value,
        drilldown="executive_controls_coverage",
    ),
    "e8.progress_coverage": _def(
        "e8.progress_coverage",
        "Progress field coverage",
        "What share of in-flight tasks have physical or duration progress?",
        "tasks_with_progress / in_progress_tasks",
        "Tasks with progress fields",
        "In-progress + complete tasks",
        source="Task.physical_percent_complete, duration_percent_complete",
        source_authority="actual_progress",
        inclusion="Active or complete tasks",
        exclusion="Not-started without progress",
        authority=MetricAuthority.AUTHORITATIVE.value,
        drilldown="executive_controls_coverage",
    ),
    "e8.cost_coverage": _def(
        "e8.cost_coverage",
        "Cost baseline coverage",
        "What share of tasks have schedule cost or resource planned cost?",
        "tasks_with_cost / schedulable_tasks",
        "Tasks with cost",
        "Schedulable tasks",
        source="Task.cost, P6ResourceAssignment",
        source_authority="baseline_schedule",
        inclusion="Schedulable tasks",
        exclusion="None",
        authority=MetricAuthority.AUTHORITATIVE.value,
        drilldown="executive_controls_coverage",
    ),
    "e8.actual_cost_coverage": _def(
        "e8.actual_cost_coverage",
        "Actual cost coverage",
        "What share of cost-bearing tasks have actual cost?",
        "tasks_with_actual_cost / tasks_with_planned_cost",
        "Tasks with actual cost",
        "Tasks with planned cost",
        source="ResourceAssignment.actual_cost (canonical preferred)",
        source_authority="actual_cost",
        inclusion="Cost-bearing tasks",
        exclusion="None",
        authority=MetricAuthority.AUTHORITATIVE.value,
        drilldown="executive_controls_coverage",
    ),
    "e8.scope_classification_coverage": _def(
        "e8.scope_classification_coverage",
        "Scope classification coverage",
        "What share of tasks have authoritative scope classification?",
        "authoritative_classified / all_tasks",
        "Authoritatively classified tasks",
        "All tasks",
        source="ScopeClassificationResolver",
        source_authority="calculated",
        inclusion="Explicit P6 activity_type or governed mapping",
        exclusion="Keyword suggestions and unknown",
        authority=MetricAuthority.GOVERNED.value,
        drilldown="executive_controls_coverage",
    ),
    "e8.hierarchy_coverage": _def(
        "e8.hierarchy_coverage",
        "Hierarchy coverage",
        "What share of tasks map to WBS or stage proxy?",
        "mapped_tasks / all_tasks",
        "Tasks with stage or future WBS link",
        "All tasks",
        source="Task.stage, P6WBSNode (future FK)",
        source_authority="current_schedule",
        inclusion="Tasks with stage set",
        exclusion="Unmapped tasks",
        caveat="WBS node FK not yet linked — stage is proxy hierarchy.",
        authority=MetricAuthority.DERIVED.value,
        drilldown="executive_controls_coverage",
    ),
    "e8.trusted_task_link_coverage": _def(
        "e8.trusted_task_link_coverage",
        "Trusted task-link coverage",
        "What share of schedule activities have at least one trusted binding?",
        "trusted_tasks / all_tasks",
        "Distinct trusted-linked tasks",
        "All schedule activities",
        source="BindingGovernanceReader",
        source_authority="trusted_binding",
        inclusion="All schedule tasks",
        exclusion="Review and legacy M2M",
        caveat=f"Trust policy: {TRUSTED_BINDING_POLICY_ID}.",
        authority=MetricAuthority.GOVERNED.value,
        drilldown="link_governance_overview",
    ),
    "e8.trusted_entity_link_coverage": _def(
        "e8.trusted_entity_link_coverage",
        "Trusted entity-link coverage",
        "What share of indexed IFC entities have trusted bindings?",
        "trusted_entities / indexed_entities",
        "Distinct trusted entities",
        "Indexed entities on completed IFC files",
        source="BindingGovernanceReader + IFCEntity",
        source_authority="trusted_binding",
        inclusion="Completed IFC index",
        exclusion="Review, property hints, legacy M2M",
        authority=MetricAuthority.GOVERNED.value,
        drilldown="link_governance_overview",
    ),
    "e8.review_coverage": _def(
        "e8.review_coverage",
        "Review suggestion coverage",
        "How many bindings await review?",
        "COUNT(active review bindings)",
        "Review binding rows",
        "N/A",
        source="BindingGovernanceReader.review_bindings_qs",
        source_authority="review_suggestion",
        inclusion="Active review queue",
        exclusion="Never combined into trusted counts",
        authority=MetricAuthority.SUGGESTION.value,
        drilldown="link_governance_review_queue",
        drilldown_filter={"mode": "review"},
    ),
    "e8.unknown_scope_count": _def(
        "e8.unknown_scope_count",
        "Unknown / unclassified scope",
        "How many tasks lack authoritative scope classification?",
        "COUNT(scope=unknown)",
        "Unknown scope tasks",
        "All tasks",
        source="ScopeClassificationResolver",
        source_authority="unknown",
        inclusion="Tasks without authoritative class",
        exclusion="Suggestion-only classifications from authoritative denominators",
        authority=MetricAuthority.UNAVAILABLE.value,
        drilldown="executive_controls_delays",
        drilldown_filter={"scope_classification": "unknown"},
    ),
    # E8-C — Group / matrix metrics
    "e8.group_activity_count": _def(
        "e8.group_activity_count",
        "Group activity count",
        "How many activities are in this hierarchy group?",
        "COUNT(Task in group)",
        "Tasks matching group key",
        "Filtered population",
        source="Task",
        source_authority="current_schedule",
        inclusion="Tasks in selected group",
        exclusion="Tasks outside filter context",
        authority=MetricAuthority.AUTHORITATIVE.value,
        drilldown="executive_controls_matrix_activities",
    ),
    "e8.group_planned_progress": _def(
        "e8.group_planned_progress",
        "Group planned progress",
        "How much work should be complete in this group by the data date?",
        "Σ(weight × planned_pct) / Σ(weight)",
        "Weighted planned completion",
        "Included schedulable tasks in group",
        weighting="cost | quantity | duration | count",
        source="ScheduleProgressAggregationService",
        source_authority="calculated",
        inclusion="Schedulable tasks in group",
        exclusion="Dateless tasks",
        authority=MetricAuthority.DERIVED.value,
        caveat="Not cost EVM — see weighting mode label.",
        drilldown="executive_controls_matrix",
    ),
    "e8.group_actual_progress": _def(
        "e8.group_actual_progress",
        "Group actual progress",
        "How much work is complete in this group?",
        "Σ(weight × earned_pct) / Σ(weight)",
        "Weighted earned completion",
        "Included schedulable tasks in group",
        weighting="cost | quantity | duration | count",
        source="ScheduleProgressAggregationService",
        source_authority="calculated",
        inclusion="Schedulable tasks in group",
        exclusion="Duration proxy labelled separately",
        authority=MetricAuthority.DERIVED.value,
        drilldown="executive_controls_matrix",
    ),
    "e8.group_variance": _def(
        "e8.group_variance",
        "Group schedule variance",
        "How far ahead or behind is this group?",
        "actual_progress − planned_progress",
        "Variance in percent points",
        "Same weighting as group progress",
        source="derived",
        source_authority="calculated",
        inclusion="Group with defensible progress mode",
        exclusion="Unavailable when progress unavailable",
        authority=MetricAuthority.DERIVED.value,
        drilldown="executive_controls_matrix",
    ),
    "e8.group_budget_materiality": _def(
        "e8.group_budget_materiality",
        "Group budget / materiality",
        "What is the cost materiality of this group?",
        "SUM(Task.cost) where cost > 0",
        "Tasks with cost",
        "All tasks in group",
        source="Task.cost",
        source_authority="current_schedule",
        inclusion="Tasks with imported cost",
        exclusion="Tasks without cost — disclosed in coverage",
        authority=MetricAuthority.AUTHORITATIVE.value,
        drilldown="executive_controls_matrix_activities",
    ),
    "e8.group_trusted_task_impact": _def(
        "e8.group_trusted_task_impact",
        "Group trusted task impact",
        "How many trusted-linked tasks are in this group?",
        "COUNT(trusted tasks in group)",
        "Trusted-linked tasks",
        "All tasks in group",
        source="BindingGovernanceReader",
        source_authority="trusted_binding",
        inclusion="Accepted active bindings",
        exclusion="Review, property, legacy M2M",
        authority=MetricAuthority.GOVERNED.value,
        drilldown="link_governance_overview",
    ),
    "e8.group_trusted_entity_impact": _def(
        "e8.group_trusted_entity_impact",
        "Group trusted entity impact",
        "How many trusted entity links attach to tasks in this group?",
        "SUM(entity count per trusted task)",
        "Entity links on trusted tasks",
        "Trusted tasks in group",
        source="BindingGovernanceReader",
        source_authority="trusted_binding",
        inclusion="Accepted bindings",
        exclusion="Not distinct GlobalId dedupe across tasks",
        caveat="Non-additive across groups when entities map to multiple tasks.",
        authority=MetricAuthority.GOVERNED.value,
        drilldown="link_governance_overview",
    ),
    "e8.prioritization_index": _def(
        "e8.prioritization_index",
        "Prioritization index",
        "Which groups merit investigation first?",
        "Weighted sum of public components",
        "Documented components",
        "N/A",
        source="TradePackageAnalysisService",
        source_authority="calculated",
        inclusion="Underperforming groups with materiality data",
        exclusion="Not a performance truth score",
        authority=MetricAuthority.PROXY.value,
        caveat="Ranking aid only — components displayed separately.",
        drilldown="executive_controls_trades",
    ),
    # E8-D — current-point and derived as-of series
    "e8.current_pv": _def(
        "e8.current_pv",
        "Current Planned Value (PV)",
        "What is the cumulative planned value at the data date?",
        "Σ(weight × planned_pct) at data date",
        "Weighted planned value",
        "BAC or duration weight",
        source="compute_evm",
        source_authority="current_schedule",
        inclusion="Physical tasks with dates",
        exclusion="Non-physical without filter",
        authority=MetricAuthority.DERIVED.value,
        caveat="Current point only — historical=false.",
        drilldown="executive_controls_evm",
    ),
    "e8.derived_asof_pv_curve": _def(
        "e8.derived_asof_pv_curve",
        "Derived as-of PV curve",
        "How does planned value accumulate over the current schedule spine?",
        "Weekly cumulative PV from current task dates",
        "PV series points",
        "BAC",
        source="DerivedAsOfSCurveService",
        source_authority="current_snapshot_reconstruction",
        inclusion="Schedulable tasks",
        exclusion="Dateless tasks",
        authority=MetricAuthority.DERIVED.value,
        caveat="Current-snapshot reconstruction — not imported historical time-phasing.",
        drilldown="executive_controls_evm",
    ),
    "e8.derived_asof_ev_curve": _def(
        "e8.derived_asof_ev_curve",
        "Derived as-of EV curve",
        "How does earned value accumulate on the current snapshot spine?",
        "Weekly cumulative EV capped at data date",
        "EV series points",
        "BAC",
        source="DerivedAsOfSCurveService",
        source_authority="current_snapshot_reconstruction",
        inclusion="Tasks with progress or completion",
        exclusion="Future actual_start beyond data date",
        authority=MetricAuthority.DERIVED.value,
        drilldown="executive_controls_evm",
    ),
    "e8.derived_asof_ac_curve": _def(
        "e8.derived_asof_ac_curve",
        "Derived as-of AC curve",
        "How does actual cost accumulate when authoritative AC exists?",
        "Step attribution at actual_end or data date",
        "AC series points",
        "BAC",
        source="DerivedAsOfSCurveService",
        source_authority="authoritative",
        inclusion="Tasks with ResourceAssignment actual_cost (canonical preferred)",
        exclusion="Unavailable without AC import",
        authority=MetricAuthority.AUTHORITATIVE.value,
        drilldown="executive_controls_evm",
    ),
    "e8.imported_historical_unavailable": _def(
        "e8.imported_historical_unavailable",
        "Imported historical series",
        "Can we show imported past performance curves?",
        "N/A — blocked",
        "N/A",
        "N/A",
        source="AnalyticalSnapshot (not implemented)",
        source_authority="unavailable",
        inclusion="None",
        exclusion="All until snapshot schema exists",
        authority=MetricAuthority.UNAVAILABLE.value,
        missing="Requires AnalyticalSnapshot or schedule version history.",
        drilldown="executive_controls_evm",
    ),
}


def build_e8_metric_result(
    definition: E8MetricDefinition,
    *,
    available: bool,
    value: int | float | None = None,
    unit: str = "count",
    numerator: int | float | None = None,
    denominator: int | float | None = None,
    authority: str | None = None,
    coverage: dict[str, Any] | None = None,
    caveats: list[str] | None = None,
    data_date: str | None = None,
    calculated_at: str | None = None,
) -> E8MetricResult:
    """Build a metric result; percentage only when denominator is positive."""
    pct: float | None = None
    if denominator is not None and denominator > 0 and numerator is not None:
        pct = round(100.0 * float(numerator) / float(denominator), 2)
    return E8MetricResult(
        metric_id=definition.metric_id,
        label=definition.label,
        available=available,
        value=value if value is not None else numerator,
        unit=unit,
        numerator=numerator,
        denominator=denominator,
        percentage=pct,
        source=definition.primary_source,
        authority=authority or definition.authority_level,
        methodology_version=E8_METHODOLOGY_VERSION,
        coverage=coverage,
        caveats=caveats or ([definition.caveat] if definition.caveat else []),
        data_date=data_date,
        calculated_at=calculated_at or datetime.now(UTC).isoformat(),
        analytical_state=LIVE_STATE,
        drilldown_route=definition.drilldown_route,
        drilldown_filter=dict(definition.drilldown_filter),
    )


def methodology_registry_payload() -> list[dict[str, Any]]:
    """Export all e8-v1 definitions for API/UI methodology drawer."""
    return [d.to_dict() for d in E8_METRIC_REGISTRY.values()]
