# ifc_processor/schema_data/__init__.py
"""Lazy access to the generated IFC schema metadata tables.

The per-schema modules (``entities_ifc4.py``, ``psets_ifc4.py``, ...) are
generated by ``scripts/generate_schema_data.py`` from buildingSMART-derived
tables — see their docstrings for provenance. This package loads them on
first use, keyed by a tolerant schema identifier ("IFC4", "IFC4X3_ADD2",
"ifc2x3" all resolve).

High-level queries (type expansion, property-term resolution) live in
:mod:`ifc_processor.schema_data.lookup`.
"""

from __future__ import annotations

from functools import lru_cache
from importlib import import_module

SUPPORTED_SCHEMAS = ("IFC2X3", "IFC4", "IFC4X3")


def normalize_schema(schema: str) -> str:
    """Map any IFC schema identifier to a supported table key.

    Unknown or future schemas fall back to IFC4 — the least-wrong default
    for metadata lookups.
    """
    upper = (schema or "").upper()
    for known in ("IFC4X3", "IFC2X3"):
        if upper.startswith(known):
            return known
    return "IFC4"


@lru_cache(maxsize=len(SUPPORTED_SCHEMAS))
def entities(schema: str = "IFC4") -> dict[str, dict]:
    """Entity hierarchy table: {name: {parent, abstract, predefined_types, attributes}}."""
    key = normalize_schema(schema).lower()
    return import_module(f"ifc_processor.schema_data.entities_{key}").ENTITIES


@lru_cache(maxsize=len(SUPPORTED_SCHEMAS))
def psets(schema: str = "IFC4") -> dict[str, dict]:
    """Standard pset table: {name: {applicable, properties: {prop: {kind, data_type, enum}}}}."""
    key = normalize_schema(schema).lower()
    return import_module(f"ifc_processor.schema_data.psets_{key}").PSETS
