# Generated by Django 5.2.11 on 2026-02-07 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='error', max_length=20, verbose_name='Severity')),
                ('message', models.TextField(help_text='Short error description', verbose_name='Error Message')),
                ('exception_type', models.CharField(db_index=True, help_text='e.g., ValueError, KeyError, etc.', max_length=255, verbose_name='Exception Type')),
                ('stacktrace', models.TextField(help_text='Full Python stacktrace', verbose_name='Stack Trace')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Request URL')),
                ('method', models.CharField(blank=True, help_text='GET, POST, etc.', max_length=10, verbose_name='HTTP Method')),
                ('view_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='View Name')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='GET/POST parameters (sensitive data filtered)', verbose_name='Request Data')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='Resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Resolution Note')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'severity'], name='core_errorl_created_bce940_idx'), models.Index(fields=['is_resolved', '-created_at'], name='core_errorl_is_reso_8d538a_idx'), models.Index(fields=['exception_type', '-created_at'], name='core_errorl_excepti_3ba3ac_idx'), models.Index(fields=['view_name', '-created_at'], name='core_errorl_view_na_1f8f69_idx')],
            },
        ),
    ]
