# Generated by Django 5.2.11 on 2026-03-10 21:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_userllmconfig_delete_llmconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamNote",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("body", models.TextField(help_text="Rich-text HTML content", verbose_name="Body")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bug", "Bug"),
                            ("question", "Question"),
                            ("suggestion", "Suggestion"),
                            ("todo", "To-Do"),
                            ("note", "Note"),
                        ],
                        db_index=True,
                        default="note",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "page_url",
                    models.CharField(
                        blank=True,
                        help_text="Auto-captured from the browser",
                        max_length=500,
                        verbose_name="Page URL",
                    ),
                ),
                (
                    "browser_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User agent, screen size, etc.",
                        verbose_name="Browser Info",
                    ),
                ),
                (
                    "author_username",
                    models.CharField(
                        db_index=True,
                        help_text="Username of the note creator",
                        max_length=150,
                        verbose_name="Author",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(db_index=True, default=False, verbose_name="Resolved"),
                ),
                (
                    "resolved_by",
                    models.CharField(blank=True, max_length=150, verbose_name="Resolved By"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Resolved At"),
                ),
                ("resolution_note", models.TextField(blank=True, verbose_name="Resolution Note")),
                (
                    "sent_to_supabase",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Sent to Supabase"
                    ),
                ),
                (
                    "supabase_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID from Supabase to prevent duplicate imports",
                        null=True,
                        unique=True,
                        verbose_name="Supabase ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Note",
                "verbose_name_plural": "Team Notes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "category"], name="core_teamno_created_0bdd52_idx"
                    ),
                    models.Index(
                        fields=["is_resolved", "-created_at"], name="core_teamno_is_reso_2b737f_idx"
                    ),
                    models.Index(
                        fields=["author_username", "-created_at"],
                        name="core_teamno_author__7423c8_idx",
                    ),
                ],
            },
        ),
    ]
