# Generated by Django 5.2.11 on 2026-04-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_teamnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="userllmconfig",
            name="theme",
            field=models.CharField(
                choices=[("dark", "Dark"), ("light", "Light")],
                default="dark",
                help_text="UI color theme.",
                max_length=8,
                verbose_name="Theme",
            ),
        ),
    ]
