# Generated by Django 5.2.11 on 2026-05-05 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0009_sitellmconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokenBudget',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='token_budget', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('daily_cap', models.PositiveIntegerField(default=50000, help_text='Total tokens (input + output) allowed per UTC day. 0 = unlimited.', verbose_name='Daily Cap (tokens)')),
                ('used_today', models.PositiveIntegerField(default=0, help_text='Tokens consumed since the last reset.', verbose_name='Used Today')),
                ('last_reset_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Reset')),
                ('hard_blocked', models.BooleanField(default=False, help_text='When set, refuse all cloud LLM calls regardless of remaining budget.', verbose_name='Hard Blocked')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Token Budget',
                'verbose_name_plural': 'User Token Budgets',
            },
        ),
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('purpose', models.CharField(choices=[('ask', 'Ask'), ('modify', 'Modify')], db_index=True, max_length=10)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Estimated USD cost — provider price table × token counts.', max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('succeeded', models.BooleanField(db_index=True, default=True)),
                ('error_type', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Call Log',
                'verbose_name_plural': 'LLM Call Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_llmcal_user_id_815b1a_idx'), models.Index(fields=['provider', '-created_at'], name='core_llmcal_provide_1ada39_idx')],
            },
        ),
    ]
