# Generated by Django 5.2.11 on 2026-06-05 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_sitestorageconfig_userstoragequota"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="llmcalllog",
            name="byok",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True if this call used the user's own API key (excluded from managed-pool spend).",
                verbose_name="BYOK",
            ),
        ),
        migrations.AddField(
            model_name="userllmconfig",
            name="anthropic_api_key_ciphertext",
            field=models.TextField(
                blank=True, default="", verbose_name="Anthropic API key (encrypted)"
            ),
        ),
        migrations.AddField(
            model_name="userllmconfig",
            name="anthropic_api_key_hint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Masked display form, e.g. 'sk-ant-…12345'.",
                max_length=24,
                verbose_name="Anthropic key hint",
            ),
        ),
        migrations.AddField(
            model_name="userllmconfig",
            name="anthropic_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Curated Anthropic model identifier (see core.llm_catalog).",
                max_length=100,
                verbose_name="Anthropic model",
            ),
        ),
        migrations.AddField(
            model_name="userllmconfig",
            name="ask_provider_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Use site default"),
                    ("ollama", "Local Ollama"),
                    ("anthropic", "Anthropic (my key)"),
                    ("groq", "Groq (my key)"),
                ],
                default="",
                help_text="Per-purpose override. Blank = follow SiteLLMConfig.",
                max_length=20,
                verbose_name="Ask provider override",
            ),
        ),
        migrations.AddField(
            model_name="userllmconfig",
            name="groq_api_key_ciphertext",
            field=models.TextField(blank=True, default="", verbose_name="Groq API key (encrypted)"),
        ),
        migrations.AddField(
            model_name="userllmconfig",
            name="groq_api_key_hint",
            field=models.CharField(
                blank=True, default="", max_length=24, verbose_name="Groq key hint"
            ),
        ),
        migrations.AddField(
            model_name="userllmconfig",
            name="groq_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Curated Groq model identifier (see core.llm_catalog).",
                max_length=100,
                verbose_name="Groq model",
            ),
        ),
        migrations.AddField(
            model_name="userllmconfig",
            name="keys_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Keys last updated"),
        ),
        migrations.AddField(
            model_name="userllmconfig",
            name="modify_provider_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Use site default"),
                    ("ollama", "Local Ollama"),
                    ("anthropic", "Anthropic (my key)"),
                    ("groq", "Groq (my key)"),
                ],
                default="",
                max_length=20,
                verbose_name="Modify provider override",
            ),
        ),
        migrations.AddIndex(
            model_name="llmcalllog",
            index=models.Index(fields=["byok", "-created_at"], name="core_llmcal_byok_574ca3_idx"),
        ),
    ]
