# Generated by Django 5.2.11 on 2026-06-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_llmcalllog_byok_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitellmconfig",
            name="expose_ollama_to_users",
            field=models.BooleanField(
                default=False,
                help_text="When on, end users can pick 'Local Ollama' from the For Ask / For Modify dropdowns in Settings → Bring Your Own Key. Leave off for cloud-hosted deployments where the user's browser can't reach their own Ollama. Self-hosted Castor installs flip this on once. Independent of force_local_ollama, which is a separate emergency kill switch.",
                verbose_name="Expose Ollama to users",
            ),
        ),
    ]
