# Generated by Django 5.2.11 on 2026-09-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_sitellmconfig_expose_ollama_to_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitellmconfig",
            name="ask_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Model identifier for the Ask provider. Blank = .env default (OLLAMA_MODEL).",
                max_length=100,
                verbose_name="Ask Model",
            ),
        ),
        migrations.AlterField(
            model_name="sitellmconfig",
            name="modify_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Model identifier for the Modify provider. Blank = .env default (MODIFY_MODEL, a code-tuned Ollama tag).",
                max_length=100,
                verbose_name="Modify Model",
            ),
        ),
    ]
