# Generated by Django 5.2.11 on 2026-04-17 18:01

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0002_alter_project_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectRole",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("buildingowner", "Building Owner"),
                            ("facilitiesmanager", "Facilities Manager"),
                            ("maintenanceengineer", "Maintenance Engineer"),
                            ("contractor", "Contractor"),
                            ("subcontractor", "Subcontractor"),
                            ("tenant", "Tenant"),
                            ("occupant", "Occupant"),
                            ("auditor", "Auditor"),
                            ("consultant", "Consultant"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Role",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="Valid From"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Leave blank for an open-ended assignment.",
                        null=True,
                        verbose_name="Valid Until",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_roles",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Role",
                "verbose_name_plural": "Project Roles",
                "ordering": ["-valid_from"],
                "indexes": [
                    models.Index(
                        fields=["user", "project", "role"], name="environment_user_id_22b50e_idx"
                    ),
                    models.Index(fields=["project", "role"], name="environment_project_178c33_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "project", "role", "valid_from"),
                        name="uniq_user_project_role_validfrom",
                    )
                ],
            },
        ),
    ]
