# Generated by Django 5.2.11 on 2026-04-27 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0004_permission_consolidation"),
        ("ifc_processor", "0010_add_data_issue_dedup"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectrole",
            name="assigned_space",
            field=models.ForeignKey(
                blank=True,
                help_text="Spatial container the user occupies (TENANT / OCCUPANT only). Pre-fills location on Occupant Portal requests; never granted automatically — set explicitly when seating the user.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ifc_processor.ifcspatialelement",
                verbose_name="Assigned Space",
            ),
        ),
    ]
