# Generated by Django 5.2.11 on 2026-06-09 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0007_add_audit_name_cache_to_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                help_text="Denormalized pointer to the user holding the OWNER membership. Kept in sync by ProjectAccessService. When the user is deleted, the project and its full tree (memberships, IFC files, documents, chats, modify proposals, facility data) cascade with them.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
    ]
