#!/usr/bin/env bash
# =============================================================================
# worktree_db_setup.sh — Castor Project (v2)
#
# Creates a STANDALONE docker-compose file for the worktree DB.
# This runs as a completely separate container — it NEVER touches castor-db.
#
# Usage: bash scripts/worktree_db_setup.sh <worktree-name> <worktree-dir>
# =============================================================================

set -euo pipefail

WORKTREE_NAME="${1:?Usage: worktree_db_setup.sh <worktree-name> <worktree-dir>}"
WORKTREE_DIR="${2:?Usage: worktree_db_setup.sh <worktree-name> <worktree-dir>}"

# Repo root = where this script lives, one level up from scripts/
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# ---------------------------------------------------------------------------
# Castor DB config (hardcoded to match docker/docker-compose.yml)
# ---------------------------------------------------------------------------
DB_IMAGE="pgvector/pgvector:pg16"
DB_USER="castor"
DB_PASSWORD="castor"
DB_NAME="castor"
INIT_SQL="${REPO_ROOT}/init-db.sql"

# ---------------------------------------------------------------------------
# Port allocation: unique port per worktree (range 5500-5599)
# ---------------------------------------------------------------------------
HASH=$(echo -n "${WORKTREE_NAME}" | cksum | awk '{print $1}')
PORT=$(( 5500 + (HASH % 100) ))

MAX_ATTEMPTS=100
ATTEMPT=0
while ss -tlnp 2>/dev/null | grep -q ":${PORT} " || \
      netstat -an 2>/dev/null | grep -q ":${PORT} " || \
      docker ps --format '{{.Ports}}' 2>/dev/null | grep -q "0.0.0.0:${PORT}->"; do
    PORT=$(( PORT + 1 ))
    ATTEMPT=$(( ATTEMPT + 1 ))
    if [ "${ATTEMPT}" -ge "${MAX_ATTEMPTS}" ]; then
        echo "ERROR: Could not find a free port in range 5500-5599" >&2
        exit 1
    fi
done

VOLUME_NAME="castor_wt_${WORKTREE_NAME}"
CONTAINER_NAME="castor-db-wt-${WORKTREE_NAME}"

# ---------------------------------------------------------------------------
# init-db.sql mount (if it exists)
# ---------------------------------------------------------------------------
if [ -f "${INIT_SQL}" ]; then
    # Convert to absolute path for Docker mount
    INIT_SQL_ABS="$(cd "$(dirname "${INIT_SQL}")" && pwd)/$(basename "${INIT_SQL}")"
    INIT_SQL_MOUNT="      - ${INIT_SQL_ABS}:/docker-entrypoint-initdb.d/init-db.sql:ro"
    INIT_SQL_STATUS="mounted"
else
    INIT_SQL_MOUNT=""
    INIT_SQL_STATUS="not found (WARNING)"
fi

# ---------------------------------------------------------------------------
# Generate docker-compose.worktree.yml (STANDALONE — not an override)
#
# This defines a unique service name (db_wt_<name>) so it is completely
# independent from the main castor-db service. Running this file will
# NEVER stop, recreate, or interfere with castor-db.
# ---------------------------------------------------------------------------
cat > "${WORKTREE_DIR}/docker-compose.worktree.yml" <<EOF
# =============================================================================
# AUTO-GENERATED by worktree_db_setup.sh (v2)
# Worktree: ${WORKTREE_NAME}
# Standalone Castor DB on port ${PORT}
#
# Usage:
#   docker compose -f docker-compose.worktree.yml up -d
#   docker compose -f docker-compose.worktree.yml down -v
#
# This is NOT an override — it runs independently from castor-db.
# =============================================================================

services:
  db_wt_${WORKTREE_NAME}:
    image: ${DB_IMAGE}
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${PORT}:5432"
    volumes:
      - ${VOLUME_NAME}:/var/lib/postgresql/data
${INIT_SQL_MOUNT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  ${VOLUME_NAME}:
    driver: local
EOF

# ---------------------------------------------------------------------------
# Generate .env.worktree for Django settings auto-detection
# ---------------------------------------------------------------------------
cat > "${WORKTREE_DIR}/.env.worktree" <<EOF
# AUTO-GENERATED — Castor worktree DB config: ${WORKTREE_NAME}
WORKTREE_DB_PORT=${PORT}
WORKTREE_DB_HOST=localhost
WORKTREE_DB_NAME=${DB_NAME}
WORKTREE_DB_USER=${DB_USER}
WORKTREE_DB_PASSWORD=${DB_PASSWORD}
WORKTREE_DB_CONTAINER=${CONTAINER_NAME}
DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@localhost:${PORT}/${DB_NAME}
EOF

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo ""
echo "============================================="
echo " Castor Worktree DB Ready"
echo "============================================="
echo " Worktree:  ${WORKTREE_DIR}"
echo " Branch:    worktree-${WORKTREE_NAME}"
echo " Container: ${CONTAINER_NAME}"
echo " Image:     ${DB_IMAGE}"
echo " Port:      ${PORT} (main castor-db stays on 5432)"
echo " Volume:    ${VOLUME_NAME}"
echo " DB:        ${DB_NAME} (user: ${DB_USER})"
echo " Init SQL:  ${INIT_SQL_STATUS}"
echo "============================================="
echo ""
echo " To start:  cd ${WORKTREE_DIR} && docker compose -f docker-compose.worktree.yml up -d"
echo " To stop:   cd ${WORKTREE_DIR} && docker compose -f docker-compose.worktree.yml down -v"
echo ""
echo " SAFE: This does NOT touch castor-db on port 5432."
echo ""