# Generated by Django 5.2.11 on 2026-09-06 18:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0008_alter_project_owner'),
        ('takeoff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityPreparationConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Draft')], default='draft', max_length=20, verbose_name='Status')),
                ('contract_version', models.CharField(default='qty-prep-config-v1', max_length=64, verbose_name='Contract version')),
                ('basis_rules', models.JSONField(default=dict, help_text='Map of IFC class → Quantity Basis enum (session measurement rules).', verbose_name='Basis rules')),
                ('schema_fields', models.JSONField(default=dict, help_text='Map of editable schema field key → included bool.', verbose_name='Schema fields')),
                ('source_mappings', models.JSONField(default=dict, help_text='Map of editable mapping field key → source-type intent enum.', verbose_name='Source mappings')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last used at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quantity_preparation_configs_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_preparation_configs', to='environments.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Quantity Preparation Config',
                'verbose_name_plural': 'Quantity Preparation Configs',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['project', '-updated_at'], name='takeoff_qua_project_a87401_idx'), models.Index(fields=['project', 'status'], name='takeoff_qua_project_6888ed_idx')],
            },
        ),
    ]
