# Generated by Django 5.2.11 on 2026-09-07 13:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("environments", "0008_alter_project_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FiveDDataModel",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "contract_version",
                    models.CharField(
                        default="fived-snapshot-f2-v1",
                        help_text="Persistence contract for Stage 1 preparation snapshots.",
                        max_length=64,
                        verbose_name="Contract version",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fived_data_models_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fived_data_models",
                        to="environments.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "5D Preparation Model",
                "verbose_name_plural": "5D Preparation Models",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FiveDModelVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_label", models.CharField(max_length=64, verbose_name="Version label")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("qty_prep_session", "Quantity prep session"),
                            ("qty_prep_export", "Quantity prep export"),
                            ("rebuild", "Rebuild"),
                        ],
                        db_index=True,
                        default="qty_prep_session",
                        max_length=32,
                        verbose_name="Source",
                    ),
                ),
                (
                    "settings_snapshot",
                    models.JSONField(blank=True, default=dict, verbose_name="Settings snapshot"),
                ),
                (
                    "boundary_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stage 1 preparation boundaries — not BOQ, not cost, not EVM, not writeback.",
                        verbose_name="Boundary snapshot",
                    ),
                ),
                (
                    "session_annotations_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Session annotations snapshot"
                    ),
                ),
                (
                    "unresolved_register_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Unresolved register snapshot"
                    ),
                ),
                (
                    "source_query",
                    models.JSONField(blank=True, default=dict, verbose_name="Source query"),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Content hash"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("frozen", "Frozen"),
                            ("superseded", "Superseded"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="frozen",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0, verbose_name="Row count")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fived_model_versions_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "data_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="fived.fiveddatamodel",
                        verbose_name="Preparation model",
                    ),
                ),
            ],
            options={
                "verbose_name": "5D Preparation Model Version",
                "verbose_name_plural": "5D Preparation Model Versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FiveDModelRow",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_row_key",
                    models.CharField(db_index=True, max_length=512, verbose_name="Source row key"),
                ),
                (
                    "model_group",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="Model group"
                    ),
                ),
                (
                    "ifc_class",
                    models.CharField(db_index=True, max_length=128, verbose_name="IFC class"),
                ),
                (
                    "type_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Type name"
                    ),
                ),
                (
                    "quantity_basis",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Quantity basis"
                    ),
                ),
                (
                    "quantity_source",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Quantity source"
                    ),
                ),
                (
                    "unit_basis",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Unit basis"
                    ),
                ),
                (
                    "total_quantity",
                    models.FloatField(blank=True, null=True, verbose_name="Total quantity"),
                ),
                (
                    "total_quantity_display",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Total quantity display"
                    ),
                ),
                (
                    "quantity_provenance",
                    models.JSONField(blank=True, default=dict, verbose_name="Quantity provenance"),
                ),
                (
                    "basis_unresolved",
                    models.BooleanField(default=False, verbose_name="Basis unresolved"),
                ),
                (
                    "missing_quantity_source",
                    models.BooleanField(
                        default=False, verbose_name="Missing selected quantity source"
                    ),
                ),
                (
                    "classification_code",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Classification code"
                    ),
                ),
                (
                    "classification_origin",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="Classification origin"
                    ),
                ),
                (
                    "classification_source_intent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Classification source intent",
                    ),
                ),
                (
                    "missing_classification",
                    models.BooleanField(default=False, verbose_name="Missing classification"),
                ),
                (
                    "package_mapping",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Copied from Quantities package field — schema field name only, not BOQ output.",
                        max_length=120,
                        verbose_name="Package mapping",
                    ),
                ),
                (
                    "package_mapping_origin",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="Package mapping origin"
                    ),
                ),
                (
                    "package_mapping_source_intent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Package mapping source intent",
                    ),
                ),
                (
                    "missing_package_mapping",
                    models.BooleanField(default=False, verbose_name="Missing package mapping"),
                ),
                (
                    "work_package",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Work package"
                    ),
                ),
                (
                    "work_package_origin",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="Work package origin"
                    ),
                ),
                (
                    "work_package_source_intent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Work package source intent",
                    ),
                ),
                (
                    "missing_work_package",
                    models.BooleanField(default=False, verbose_name="Missing work package"),
                ),
                (
                    "manual_mapping_applied",
                    models.BooleanField(default=False, verbose_name="Manual mapping applied"),
                ),
                (
                    "manual_mapping_fields",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Manual mapping fields"
                    ),
                ),
                (
                    "session_review_status",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Session review status"
                    ),
                ),
                (
                    "session_review_note",
                    models.TextField(blank=True, default="", verbose_name="Session review note"),
                ),
                (
                    "computed_status",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Computed gap status"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("incomplete", "Incomplete"),
                            ("structurally_ready", "Structurally ready"),
                        ],
                        db_index=True,
                        default="incomplete",
                        help_text="Structural completeness only — not cost-approved, not QS-certified.",
                        max_length=32,
                        verbose_name="Structural status",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="fived.fivedmodelversion",
                        verbose_name="Version",
                    ),
                ),
            ],
            options={
                "verbose_name": "5D Preparation Model Row",
                "verbose_name_plural": "5D Preparation Model Rows",
                "ordering": ["ifc_class", "type_name", "source_row_key"],
            },
        ),
        migrations.AddIndex(
            model_name="fiveddatamodel",
            index=models.Index(
                fields=["project", "-updated_at"], name="fived_fived_project_c7766e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fiveddatamodel",
            index=models.Index(fields=["project", "status"], name="fived_fived_project_ccaa34_idx"),
        ),
        migrations.AddIndex(
            model_name="fivedmodelversion",
            index=models.Index(
                fields=["data_model", "-created_at"], name="fived_fived_data_mo_a0d40e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fivedmodelversion",
            index=models.Index(
                fields=["data_model", "status"], name="fived_fived_data_mo_f1b7e8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fivedmodelversion",
            constraint=models.UniqueConstraint(
                fields=("data_model", "version_label"), name="uniq_fived_version_label_per_model"
            ),
        ),
        migrations.AddIndex(
            model_name="fivedmodelrow",
            index=models.Index(
                fields=["version", "ifc_class"], name="fived_fived_version_9cd987_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fivedmodelrow",
            index=models.Index(fields=["version", "status"], name="fived_fived_version_f6a153_idx"),
        ),
        migrations.AddConstraint(
            model_name="fivedmodelrow",
            constraint=models.UniqueConstraint(
                fields=("version", "source_row_key"), name="uniq_fived_row_source_key_per_version"
            ),
        ),
    ]
